In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar bases

In [2]:
cols_usar = ['Equipo', 'tiempo', 'Minuto.video', 'Evento', 'Subevento',
       'Jugador.1', 'Jugador.2', 'coord.inicial',
       'coord.final', 'partido', 'segundos', 'remate-Gol', 'remate-Fuera',
       'remate-Al-arco', 'remate-Interceptado', 'remate-Cabeza',
       'pase-Asistencia', 'pase-Completado', 'pase-Interceptado', 'pase-Fuera',
       'pase-Inteligente', 'centro-Asistencia', 'centro-Completado',
       'centro-Interceptado', 'centro-Bloqueado', 'centro-Fuera',
       'duelo-Aereo-Perdido', 'duelo-Aereo-Ganado',
       'duelo-Disputa-suelo-Perdida', 'duelo-Disputa-suelo-Ganada',
       'duelo-Gambeta-contra-Ganada', 'duelo-Gambeta-contra-Perdida',
       'duelo-Gambeta-favor-Perdida', 'duelo-Gambeta-favor-Ganada',
       'duelo-Pivote-Perdido', 'duelo-Pivote-Ganado', 'falta-Cometida',
       'falta-Recibida', 'falta-Penal-cometido', 'falta-Penal-recibido',
       'falta-Offside', 'falta-Tarjeta-amarilla', 'falta-Tarjeta-roja',
       'recuperacion-Robo', 'recuperacion-Encontrada',
       'recuperacion-Intercepcion-suelo', 'recuperacion-Intercepcion-aereo',
       'recuperacion-Intercepcion-anticipo', 'recuperacion-Disputa-suelo',
       'parado-Lateral-interceptado', 'parado-Lateral-completado',
       'parado-Corner-interceptado', 'parado-Corner-completado',
       'parado-Tiro-libre-incompleto','parado-Tiro-libre-completado', 'perdida-Gambeta-favor', 'perdida-Robo',
       'perdida-Intercepcion', 'perdida-Error-tecnico', 'perdida-Balon-fuera',
       'perdida-Situacion-rival', 'perdida-Atajada', 'arquero-Gol-rival',
       'arquero-Atajada', 'arquero-Intercepcion-aerea', 'arquero-Intercepcion',
       'arquero-Anticipo', 'arquero-Saque-mano', 'arquero-Saque-pie',
       'arquero-Saque-meta']

In [3]:
x_max = 273
y_max = 165

# Fecha 1 - Independiente

In [19]:
data1 = pd.read_csv('../Datos generados para la app/reserva22-fecha1-independiente-tabla_filtros.csv')
data1.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/02/21,Fecha 1 vs Independiente,Primer tiempo,14:00:19,16:03:54,pase,NaN,00:06:12,00:06:18,6.0,...,0,0,0,0,0,13.0,92.397213,152.118987,29.808505,15.945522
1,2022/02/21,Fecha 1 vs Independiente,Primer tiempo,14:00:19,16:03:54,perdida,NaN,00:06:24,00:06:30,6.0,...,0,0,0,0,0,NaN,268.589076,NaN,3.335737,NaN
2,2022/02/21,Fecha 1 vs Independiente,Primer tiempo,14:00:19,16:03:54,pelota parada,NaN,00:06:33,00:06:39,6.0,...,0,0,0,0,0,16.0,199.149221,216.096233,35.313667,24.892158
3,2022/02/21,Fecha 1 vs Independiente,Primer tiempo,14:00:19,16:03:54,perdida,NaN,00:06:38,00:06:44,6.0,...,0,0,0,0,0,NaN,183.429679,NaN,92.726643,NaN
4,2022/02/21,Fecha 1 vs Independiente,Primer tiempo,14:00:19,16:03:54,pelota parada,NaN,00:07:25,00:07:31,6.0,...,0,0,0,0,0,12.0,108.846444,89.695443,145.402698,133.984050

In [20]:
data1['Equipo'] = 'Estudiantes'
data1['Minuto.video'] = 10

In [21]:
data1 = data1[cols_usar]

In [22]:
data1['partido'] = data1['partido'].str.replace('Fecha 1 vs Independiente','Independiente')

# Fecha 2 - Huracan

In [23]:
data2 = pd.read_csv('../Datos generados para la app/reserva22-fecha2-huracan-tabla_filtros.csv')
data2.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.0,...,0,0,0,0,0,8.0,100.472415,53.660912,68.042128,72.170061
1,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.0,...,0,0,0,0,0,8.0,103.753228,67.882328,75.127161,93.873726
2,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.0,...,0,0,0,0,0,8.0,51.559598,76.988068,78.439998,82.288766
3,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.0,...,0,0,0,0,0,8.0,49.855822,80.659045,66.149659,100.546433
4,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.0,...,0,0,0,0,0,8.0,115.378423,46.738479,91.083660,76.987687

In [24]:
data2['Equipo'] = 'Estudiantes'
data2['Minuto.video'] = 10

In [25]:
data2 = data2[cols_usar]

# Fecha 5 - Velez

In [26]:
data5 = pd.read_csv('../Datos generados para la app/reserva22-fecha5-velez-tabla_filtros.csv')
data5.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:19:52,00:19:58,6.0,...,0,0,0,0,0,7.0,84.902533,83.778940,7.439407,27.544219
1,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:45,00:19:45,0.0,...,0,0,0,0,0,11.0,119.235468,103.113837,91.095038,95.459428
2,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:48,00:19:48,0.0,...,0,0,0,0,0,8.0,118.163083,70.837468,85.442975,98.126037
3,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:51,00:19:51,0.0,...,0,0,0,0,0,3.0,62.726809,28.964178,79.807722,82.941763
4,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:20:41,00:20:41,0.0,...,0,0,0,0,0,NaN,19.936075,NaN,31.117879,NaN

In [27]:
data5['Equipo'] = 'Estudiantes'
data5['Minuto.video'] = 10

In [28]:
data5 = data5[cols_usar]

# Fecha 6 - Boca

In [29]:
data6 = pd.read_csv('../Datos generados para la app/reserva22-fecha6-boca-tabla_filtros.csv')
data6.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/03/23,Boca,completo,10:52:58,13:12:50,pase,NaN,00:19:50,00:19:56,6.0,...,0,0,0,0,0,10.0,95.926763,114.868893,17.914763,41.389000
1,2022/03/23,Boca,completo,10:52:58,13:12:50,perdida,NaN,00:19:54,00:20:00,6.0,...,0,0,0,0,0,17.0,105.769835,196.351432,2.153665,97.442712
2,2022/03/23,Boca,completo,10:52:58,13:12:50,recuperacion,NaN,00:19:56,00:20:02,6.0,...,0,0,0,0,0,16.0,159.376514,202.154933,17.368989,10.426461
3,2022/03/23,Boca,completo,10:52:58,13:12:50,pase,NaN,00:19:57,00:20:03,6.0,...,0,0,0,0,0,13.0,160.447168,150.907085,38.272667,40.425768
4,2022/03/23,Boca,completo,10:52:58,13:12:50,pase,NaN,00:20:02,00:20:08,6.0,...,0,0,0,0,0,19.0,153.644046,242.660078,19.043486,28.575156

In [30]:
data6['Equipo'] = 'Estudiantes'
data6['Minuto.video'] = 10

In [31]:
data6 = data6[cols_usar]

# Fecha 11 - Tigre

In [32]:
data7 = pd.read_csv('../Datos generados para la app/reserva22-fecha11-tigre-tabla_filtros.csv')
data7.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:05,00:24:05,0.0,...,0,0,0,0,0,NaN,49.295863,NaN,5.407594,NaN
1,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:25,00:24:25,0.0,...,0,0,0,0,0,NaN,178.951017,NaN,64.437918,NaN
2,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:24:36,00:24:36,0.0,...,0,0,0,0,0,NaN,101.810577,NaN,5.066415,NaN
3,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:50,00:24:50,0.0,...,0,0,0,0,0,16.0,205.841514,214.794418,8.485152,27.478753
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:22,00:24:22,0.0,...,0,0,0,0,0,NaN,161.987191,NaN,38.155945,NaN

In [33]:
data7['Equipo'] = 'Estudiantes'
data7['Minuto.video'] = 10
data7 = data7[cols_usar]

In [34]:
data7['partido'] = data7['partido'].str.replace('TIGREPPDP','Tigre')

# Fecha 12 - Colon

In [35]:
data8 = pd.read_csv('../Datos generados para la app/reserva22-fecha12-colon-tabla_filtros.csv')
data8.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/04/28,Colon,COLON1T,08:46:59,09:32:19,perdida,NaN,00:00:35,00:00:35,0.0,...,0,0,0,0,0,NaN,96.049776,NaN,11.227084,NaN
1,2022/04/28,Colon,COLON1T,08:46:59,09:32:19,perdida,NaN,00:00:38,00:00:38,0.0,...,0,0,0,0,0,NaN,97.761199,NaN,27.483089,NaN
2,2022/04/28,Colon,COLON1T,08:46:59,09:32:19,perdida,NaN,00:00:59,00:00:59,0.0,...,0,0,0,0,0,9.0,39.269629,72.476893,126.098041,140.679581
3,2022/04/28,Colon,COLON1T,08:46:59,09:32:19,duelo,NaN,00:01:22,00:01:22,0.0,...,0,0,0,0,0,NaN,20.492382,NaN,18.362701,NaN
4,2022/04/28,Colon,COLON1T,08:46:59,09:32:19,recuperacion,NaN,00:01:24,00:01:24,0.0,...,0,0,0,0,0,NaN,38.385439,NaN,33.518420,NaN

In [36]:
data8['Equipo'] = 'Estudiantes'
data8['Minuto.video'] = 10
data8 = data8[cols_usar]

# Fecha 13 - Aldosivi

In [37]:
data9 = pd.read_csv('../Datos generados para la app/reserva22-fecha13-aldosivi-tabla_filtros.csv')
data9.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:22:43,00:22:43,0.0,...,0,0,0,0,0,17.0,84.816521,185.770536,70.538952,72.716172
1,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:23:10,00:23:10,0.0,...,0,0,0,0,0,NaN,142.256635,NaN,13.409490,NaN
2,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:23:11,00:23:11,0.0,...,0,0,0,0,0,NaN,144.935257,NaN,28.140080,NaN
3,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:24:43,00:24:43,0.0,...,0,0,0,0,0,19.0,193.443449,270.418737,21.426489,8.602968
4,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:25:19,00:25:19,0.0,...,0,0,0,0,0,NaN,97.905671,NaN,83.472949,NaN

In [38]:
data9['Equipo'] = 'Estudiantes'
data9['Minuto.video'] = 10
data9 = data9[cols_usar]

# Fecha 14 - Central

In [39]:
data10 = pd.read_csv('../Datos generados para la app/reserva22-fecha14-central-tabla_filtros.csv')
data10.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/05/08,Rosario Central,CENTRAL_PPRP1,09:22:43,11:51:30,perdida,NaN,00:29:00,00:29:00,0.0,...,0,0,0,0,0,NaN,32.412069,NaN,20.652491,NaN
1,2022/05/08,Rosario Central,CENTRAL_PPRP1,09:22:43,11:51:30,duelo,NaN,00:29:08,00:29:08,0.0,...,0,0,0,0,0,NaN,171.331603,NaN,34.568192,NaN
2,2022/05/08,Rosario Central,CENTRAL_PPRP1,09:22:43,11:51:30,recuperacion,NaN,00:29:10,00:29:10,0.0,...,0,0,0,0,0,NaN,176.426800,NaN,28.864405,NaN
3,2022/05/08,Rosario Central,CENTRAL_PPRP1,09:22:43,11:51:30,perdida,NaN,00:29:15,00:29:15,0.0,...,0,0,0,0,0,NaN,219.494367,NaN,92.455983,NaN
4,2022/05/08,Rosario Central,CENTRAL_PPRP1,09:22:43,11:51:30,pelota parada,NaN,00:29:33,00:29:33,0.0,...,0,0,0,0,0,18.0,201.446435,211.372744,141.771238,152.261491

In [40]:
data10['Equipo'] = 'Estudiantes'
data10['Minuto.video'] = 10
data10 = data10[cols_usar]

# Cuartos - Gimnasia

In [41]:
data11 = pd.read_csv('../Datos generados para la app/reserva22-cuartos-gimnasia-tabla_filtros.csv')
data11.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/05/12,Gimnasia 4tos,GELP_PPRDPfinal,14:50:52,17:17:02,pelota parada,NaN,00:30:10,00:30:10,0.0,...,0,0,0,0,0,22.0,260.423207,272.000000,25.854209,94.132478
1,2022/05/12,Gimnasia 4tos,GELP_PPRDPfinal,14:50:52,17:17:02,pelota parada,NaN,00:40:01,00:40:01,0.0,...,0,0,0,0,0,23.0,234.852508,248.504231,143.790586,131.382562
2,2022/05/12,Gimnasia 4tos,GELP_PPRDPfinal,14:50:52,17:17:02,pelota parada,NaN,00:50:47,00:50:47,0.0,...,0,0,0,0,0,22.0,242.823731,247.181292,144.351383,94.426350
3,2022/05/12,Gimnasia 4tos,GELP_PPRDPfinal,14:50:52,17:17:02,pelota parada,NaN,00:37:56,00:37:56,0.0,...,0,0,0,0,0,20.0,250.852716,252.879441,14.245695,55.723156
4,2022/05/12,Gimnasia 4tos,GELP_PPRDPfinal,14:50:52,17:17:02,pelota parada,NaN,00:18:45,00:18:45,0.0,...,0,0,0,0,0,17.0,150.648043,186.774609,72.064458,84.983548

In [42]:
data11['Equipo'] = 'Estudiantes'
data11['Minuto.video'] = 10
data11 = data11[cols_usar]

# Semis - River

In [43]:
data121 = pd.read_csv('../Datos generados para la app/reserva22-semis_river-tabla_filtros.csv')
data121.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/05/15,River Semifinal,RIVER_PPRPD_FINAL,21:49:50,00:23:00,duelo,NaN,00:26:21,00:26:21,0.0,...,0,0,0,0,0,NaN,60.532205,NaN,37.715922,NaN
1,2022/05/15,River Semifinal,RIVER_PPRPD_FINAL,21:49:50,00:23:00,recuperacion,NaN,00:26:22,00:26:22,0.0,...,0,0,0,0,0,NaN,48.544904,NaN,30.907888,NaN
2,2022/05/15,River Semifinal,RIVER_PPRPD_FINAL,21:49:50,00:23:00,duelo,NaN,00:26:29,00:26:29,0.0,...,0,0,0,0,0,NaN,67.398420,NaN,37.995444,NaN
3,2022/05/15,River Semifinal,RIVER_PPRPD_FINAL,21:49:50,00:23:00,perdida,NaN,00:26:30,00:26:30,0.0,...,0,0,0,0,0,NaN,68.568121,NaN,23.210096,NaN
4,2022/05/15,River Semifinal,RIVER_PPRPD_FINAL,21:49:50,00:23:00,duelo,NaN,00:27:57,00:27:57,0.0,...,0,0,0,0,0,NaN,178.573672,NaN,89.403648,NaN

In [44]:
data122 = pd.read_csv('../Datos generados para la app/reserva22-semis_river-tabla_filtros2.csv')
data122 = data122[data122.Evento != 'perdida'].reset_index(drop=True)
data122.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/05/29,River Semifinal,completo,18:28:07,21:01:17,falta,NaN,00:27:49,00:27:49,0.0,...,0,0,0,0,0,NaN,42.573430,NaN,70.674255,NaN
1,2022/05/29,River Semifinal,completo,18:28:07,21:01:17,pase,NaN,00:27:58,00:27:58,0.0,...,0,0,0,0,0,17.0,179.555406,192.501008,98.022145,87.197707
2,2022/05/29,River Semifinal,completo,18:28:07,21:01:17,pase,NaN,00:28:06,00:28:06,0.0,...,0,0,0,0,0,11.0,122.627918,91.885193,79.949659,69.964820
3,2022/05/29,River Semifinal,completo,18:28:07,21:01:17,pase,NaN,00:28:09,00:28:09,0.0,...,0,0,0,0,0,17.0,126.546757,188.103268,84.060199,70.609322
4,2022/05/29,River Semifinal,completo,18:28:07,21:01:17,pase,NaN,00:28:51,00:28:51,0.0,...,0,0,0,0,0,6.0,34.878082,38.634345,117.282815,162.000000

In [45]:
data12 = pd.concat([data121, data122])

In [46]:
data12['Equipo'] = 'Estudiantes'
data12['Minuto.video'] = 10
data12 = data12[cols_usar]

In [47]:
data12

,Equipo,tiempo,Minuto.video,Evento,Subevento,Jugador.1,Jugador.2,coord.inicial,coord.final,partido,...,perdida-Situacion-rival,perdida-Atajada,arquero-Gol-rival,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta
0,Estudiantes,RIVER_PPRPD_FINAL,10,duelo,aereo,2.0,NaN,"61,38",NaN,River Semifinal,...,0,0,0,0,0,0,0,0,0,0
1,Estudiantes,RIVER_PPRPD_FINAL,10,recuperacion,duelo,2.0,NaN,"49,31",NaN,River Semifinal,...,0,0,0,0,0,0,0,0,0,0
2,Estudiantes,RIVER_PPRPD_FINAL,10,duelo,aereo,3.0,NaN,"67,38",NaN,River Semifinal,...,0,0,0,0,0,0,0,0,0,0
3,Estudiantes,RIVER_PPRPD_FINAL,10,perdida,duelo,3.0,NaN,"69,23",NaN,River Semifinal,...,0,0,0,0,0,0,0,0,0,0
4,Estudiantes,RIVER_PPRPD_FINAL,10,duelo,aereo,11.0,NaN,"179,89",NaN,River Semifinal,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,Estudiantes,completo,10,pase,s arquero pie,1.0,22,"0,83","142,69",River Semifinal,...,0,0,0,0,0,0,0,0,1,1
126,Estudiantes,completo,10,pase,corto,11.0,4,"53,141","64,150",River Semifinal,...,0,0,0,0,0,0,0,0,0,0
127,Estudiantes,completo,10,pase,medio,4.0,11,"69,134","105,139",River Semifinal,...,0,0,0,0,0,0,0,0,0,0
128,Estudiantes,completo,10,pase,corto,11.0,13,"220,131","140,162",River Semifinal,...,0,0,0,0,0,0,0,0,0,0
129,Estudiantes,completo,10,pase,medio,13.0,22,"141,153","205,74",River Semifinal,...,0,0,0,0,0,0,0,0,0,0

# Final - Lanus

In [48]:
data131 = pd.read_csv('../Datos generados para la app/reserva22-final_lanus-tabla_filtros.csv')
data131.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/05/31,Lanus Final,FINALLANUS_ACCIONES2,15:56:23,18:39:23,duelo,NaN,00:23:00,00:23:00,0.0,...,0,0,0,0,0,NaN,158.138716,NaN,1.412692,NaN
1,2022/05/31,Lanus Final,FINALLANUS_ACCIONES2,15:56:23,18:39:23,perdida,NaN,00:23:01,00:23:01,0.0,...,0,0,0,0,0,NaN,162.711347,NaN,26.958672,NaN
2,2022/05/31,Lanus Final,FINALLANUS_ACCIONES2,15:56:23,18:39:23,duelo,NaN,00:23:28,00:23:28,0.0,...,0,0,0,0,0,NaN,83.558890,NaN,76.639874,NaN
3,2022/05/31,Lanus Final,FINALLANUS_ACCIONES2,15:56:23,18:39:23,perdida,NaN,00:23:29,00:23:29,0.0,...,0,0,0,0,0,NaN,78.426324,NaN,70.257678,NaN
4,2022/05/31,Lanus Final,FINALLANUS_ACCIONES2,15:56:23,18:39:23,duelo,NaN,00:23:30,00:23:30,0.0,...,0,0,0,0,0,NaN,61.897691,NaN,63.103258,NaN

In [49]:
data132 = pd.read_csv('../Datos generados para la app/reserva22-final_lanus-tabla_filtros2.csv')
data132 = data132[data132.Evento != 'perdida'].reset_index(drop=True)
data132.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/05/31,Lanus Final,completo,16:25:14,19:08:14,falta,NaN,00:25:09,00:25:09,0.0,...,0,0,0,0,0,NaN,141.483556,NaN,72.695666,NaN
1,2022/05/31,Lanus Final,completo,16:25:14,19:08:14,pase,NaN,00:27:08,00:27:08,0.0,...,0,0,0,0,0,2.0,29.207410,7.601449,98.667601,61.846023
2,2022/05/31,Lanus Final,completo,16:25:14,19:08:14,pase,NaN,00:27:13,00:27:13,0.0,...,0,0,0,0,0,14.0,66.919334,171.237285,37.209992,91.823134
3,2022/05/31,Lanus Final,completo,16:25:14,19:08:14,pase,NaN,00:27:15,00:27:15,0.0,...,0,0,0,0,0,14.0,162.084571,159.042266,89.782271,94.334705
4,2022/05/31,Lanus Final,completo,16:25:14,19:08:14,pase,NaN,00:27:15,00:27:15,0.0,...,0,0,0,0,0,14.0,141.222583,173.651122,100.901186,72.444414

In [50]:
data13 = pd.concat([data131, data132])

In [51]:
data13['Equipo'] = 'Estudiantes'
data13['Minuto.video'] = 10
data13 = data13[cols_usar]

# Combinar

In [52]:
df = pd.concat([data1, data2])
df = pd.concat([df,data5])
df = pd.concat([df,data6])
df = pd.concat([df,data7])
df = pd.concat([df,data8])
df = pd.concat([df,data9])
df = pd.concat([df,data10])
df = pd.concat([df,data11])
df = pd.concat([df,data12])
df = pd.concat([df,data13])
#df.sample(15)
#df = data13
df

,Equipo,tiempo,Minuto.video,Evento,Subevento,Jugador.1,Jugador.2,coord.inicial,coord.final,partido,...,perdida-Situacion-rival,perdida-Atajada,arquero-Gol-rival,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta
0,Estudiantes,Primer tiempo,10,pase,corto,3.0,10,"92,30","152,16",Independiente,...,0,0,0,0,0,0,0,0,0,0
1,Estudiantes,Primer tiempo,10,perdida,duelo,10.0,NaN,"269,3",NaN,Independiente,...,0,0,0,0,0,0,0,0,0,0
2,Estudiantes,Primer tiempo,10,pelota parada,lateral corto,3.0,11,"199,35","216,25",Independiente,...,0,0,0,0,0,0,0,0,0,0
3,Estudiantes,Primer tiempo,10,perdida,duelo,8.0,NaN,"183,93",NaN,Independiente,...,0,0,0,0,0,0,0,0,0,0
4,Estudiantes,Primer tiempo,10,pelota parada,lateral corto,4.0,9,"109,145","90,134",Independiente,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Estudiantes,completo,10,remate pie,media distancia,2.0,Rival,"220,83","265,73",Lanus Final,...,0,0,0,0,0,0,0,0,0,0
274,Estudiantes,completo,10,arquero,salida suelo,1.0,NaN,"34,53",NaN,Lanus Final,...,0,0,0,0,0,0,0,0,0,0
275,Estudiantes,completo,10,pase,s arquero pie,2.0,2,"10,101","29,84",Lanus Final,...,0,0,0,0,0,0,0,0,0,0
276,Estudiantes,completo,10,pase,corto,2.0,20,"24,103","72,138",Lanus Final,...,0,0,0,0,0,0,0,0,0,0
277,Estudiantes,completo,10,remate pie,larga distancia,20.0,Rival,"185,136","244,63",Lanus Final,...,0,0,0,0,0,0,0,0,0,0

In [53]:
df['Temporada'] = "Temp 01-2022"

In [54]:
df

,Equipo,tiempo,Minuto.video,Evento,Subevento,Jugador.1,Jugador.2,coord.inicial,coord.final,partido,...,perdida-Atajada,arquero-Gol-rival,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,Temporada
0,Estudiantes,Primer tiempo,10,pase,corto,3.0,10,"92,30","152,16",Independiente,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
1,Estudiantes,Primer tiempo,10,perdida,duelo,10.0,NaN,"269,3",NaN,Independiente,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
2,Estudiantes,Primer tiempo,10,pelota parada,lateral corto,3.0,11,"199,35","216,25",Independiente,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
3,Estudiantes,Primer tiempo,10,perdida,duelo,8.0,NaN,"183,93",NaN,Independiente,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
4,Estudiantes,Primer tiempo,10,pelota parada,lateral corto,4.0,9,"109,145","90,134",Independiente,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Estudiantes,completo,10,remate pie,media distancia,2.0,Rival,"220,83","265,73",Lanus Final,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
274,Estudiantes,completo,10,arquero,salida suelo,1.0,NaN,"34,53",NaN,Lanus Final,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
275,Estudiantes,completo,10,pase,s arquero pie,2.0,2,"10,101","29,84",Lanus Final,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
276,Estudiantes,completo,10,pase,corto,2.0,20,"24,103","72,138",Lanus Final,...,0,0,0,0,0,0,0,0,0,Temp 01-2022
277,Estudiantes,completo,10,remate pie,larga distancia,20.0,Rival,"185,136","244,63",Lanus Final,...,0,0,0,0,0,0,0,0,0,Temp 01-2022

In [55]:
df.partido.value_counts()

Huracan            842
Boca               699
Lanus Final        490
Velez              489
River Semifinal    360
Colon              332
Rosario Central    242
Independiente      240
Gimnasia 4tos      227
Tigre              224
Aldosivi           203
Name: partido, dtype: int64

In [56]:
df[df.partido=='Lanus Final'].Evento.value_counts()

pase             223
perdida           74
recuperacion      50
duelo             48
pelota parada     40
falta             24
remate pie        13
arquero            6
sustitucion        5
tarjeta            4
remate cabeza      2
gol rival          1
Name: Evento, dtype: int64

# Temporada 02 - 2022

## Fecha 1 - Gimnasia

In [57]:
data211 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha1_gimnasia-tabla_filtros2.csv')
data211.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,duelo,NaN,00:22:41,00:22:41,0.0,...,0,0,0,0,0,NaN,212.499808,NaN,3.801400,NaN
1,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,perdida,NaN,00:22:42,00:22:42,0.0,...,0,0,0,0,0,NaN,222.588488,NaN,9.848426,NaN
2,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,recuperacion,NaN,00:22:44,00:22:44,0.0,...,0,0,0,0,0,NaN,188.469537,NaN,11.370188,NaN
3,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,duelo,NaN,00:22:54,00:22:54,0.0,...,0,0,0,0,0,NaN,147.772110,NaN,71.913737,NaN
4,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,perdida,NaN,00:22:54,00:22:54,0.0,...,0,0,0,0,0,NaN,158.884419,NaN,84.784514,NaN

In [58]:
data212 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha1_gimnasia-tabla_filtros.csv')
data212 = data212[data212.Evento != 'perdida'].reset_index(drop=True)
data212.head()

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:36,00:22:36,0.0,...,0,0,0,0,0,11.0,88.810505,119.505743,95.364507,84.362901
1,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:39,00:22:39,0.0,...,0,0,0,0,0,13.0,119.460746,178.388648,82.274154,6.024686
2,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:50,00:22:50,0.0,...,0,0,0,0,0,17.0,144.822125,209.358816,77.137790,66.835682
3,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:59,00:22:59,0.0,...,0,0,0,0,0,16.0,186.207369,201.258152,67.230667,13.735816
4,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,remate pie,NaN,00:23:02,00:23:02,0.0,...,0,0,0,0,0,22.0,212.781966,264.883817,23.700644,96.012964

In [59]:
data21 = pd.concat([data211, data212])
#data21 = data211

In [60]:
data21['Equipo'] = 'Estudiantes'
data21['Minuto.video'] = 10
data21 = data21[cols_usar]

## Fecha 2 - Aldosivi

In [61]:
data221 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha2_aldosivi-tabla_filtros.csv')
data221.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:12:40,00:12:40,0.0,...,0,0,0,0,0,10.0,79.928216,95.316999,160.758256,34.826540
1,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:02,00:13:02,0.0,...,0,0,0,0,0,NaN,96.047248,NaN,6.933179,NaN
2,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:13:17,00:13:17,0.0,...,0,0,0,0,0,9.0,71.335256,79.122097,149.047373,156.584006
3,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:13:20,00:13:20,0.0,...,0,0,0,0,0,NaN,5.794103,NaN,153.062239,NaN
4,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:21,00:13:21,0.0,...,0,0,0,0,0,NaN,35.589865,NaN,147.592861,NaN

In [62]:
# data22 = pd.concat([data221, data222])
data22 = data221

In [63]:
data22['Equipo'] = 'Estudiantes'
data22['Minuto.video'] = 10
data22 = data22[cols_usar]

## Fecha 3 - Sarmiento

In [64]:
data231 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha3_sarmiento-tabla_filtros.csv')
data231.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,duelo,NaN,00:15:51,00:15:51,0.0,...,0,0,0,0,0,NaN,89.171780,NaN,18.528520,NaN
1,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,recuperacion,NaN,00:15:52,00:15:52,0.0,...,0,0,0,0,0,NaN,124.106822,NaN,16.299078,NaN
2,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,perdida,NaN,00:16:03,00:16:03,0.0,...,0,0,0,0,0,NaN,179.213606,NaN,73.561425,NaN
3,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,recuperacion,NaN,00:16:22,00:16:22,0.0,...,0,0,0,0,0,NaN,6.681701,NaN,131.943869,NaN
4,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,perdida,NaN,00:16:25,00:16:25,0.0,...,0,0,0,0,0,NaN,32.146165,NaN,162.000000,NaN

In [65]:
# data22 = pd.concat([data221, data222])
data23 = data231

In [66]:
data23['Equipo'] = 'Estudiantes'
data23['Minuto.video'] = 10
data23 = data23[cols_usar]

## Fecha 4 - Independiente

In [4]:
data241 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha4_independiente-tabla_filtros.csv')
data241.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,pelota parada,NaN,00:15:41,00:15:41,0.0,...,0,0,0,0,0,9.0,31.363056,78.050632,134.762982,141.461017
1,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,perdida,NaN,00:15:41,00:15:41,0.0,...,0,0,0,0,0,9.0,7.085788,82.156218,153.188710,146.909701
2,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,recuperacion,NaN,00:16:07,00:16:07,0.0,...,0,0,0,0,0,NaN,74.661950,NaN,155.105439,NaN
3,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,perdida,NaN,00:16:10,00:16:10,0.0,...,0,0,0,0,0,NaN,74.587360,NaN,141.068310,NaN
4,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,recuperacion,NaN,00:19:35,00:19:35,0.0,...,0,0,0,0,0,NaN,78.532495,NaN,27.972213,NaN

In [5]:
# data22 = pd.concat([data221, data222])
data24 = data241

In [6]:
data24['Equipo'] = 'Estudiantes'
data24['Minuto.video'] = 10
data24 = data24[cols_usar]

In [7]:
# df = pd.concat([data1, data2])
# df = pd.concat([df,data5])
# df = pd.concat([df,data6])
# df = pd.concat([df,data7])
# df = pd.concat([df,data8])
# df = pd.concat([df,data9])
# df = pd.concat([df,data10])
# df = pd.concat([df,data11])
# df = pd.concat([df,data12])
# df = pd.concat([df,data13])
#df.sample(15)
#df = data13
#df2 = pd.concat([data21, data22,data23])
df2 = data24

In [8]:
df2['Temporada'] = "Temp 02-2022"

C:\Users\ElDuque\AppData\Local\Temp/ipykernel_5092/3826205789.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Temporada'] = "Temp 02-2022"

In [9]:
df2.partido.value_counts()

Independiente    274
Name: partido, dtype: int64

## Unir las dos temporadas

In [10]:
#dftotal = pd.concat([df,df2])
dftotal = df2

## Meter los apellidos

In [11]:
formaciones = pd.read_excel('../Datos generados para la app/Formaciones Reserva 2022.xlsx')
formaciones.head()

         Partido  Numero_jugador   Apellido   Estado     Temporada
0  Independiente             1.0     Zozaya  Titular  Temp 01-2022
1  Independiente             3.0  Fernandez  Titular  Temp 01-2022
2  Independiente             6.0   S. NuÃ±ez  Titular  Temp 01-2022
3  Independiente             2.0     Flores  Titular  Temp 01-2022
4  Independiente             4.0    Rosales  Titular  Temp 01-2022

In [12]:
dftotal2 = dftotal.merge(formaciones,how='left',left_on=(['Temporada','partido','Jugador.1']), right_on=(['Temporada','Partido','Numero_jugador']))
dftotal2.sample(15)

,Equipo,tiempo,Minuto.video,Evento,Subevento,Jugador.1,Jugador.2,coord.inicial,coord.final,partido,...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,Temporada,Partido,Numero_jugador,Apellido,Estado
252,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,error tecnico,15.0,NaN,"224,5",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,15.0,J. Ascacibar,Suplente
154,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,error tecnico,6.0,NaN,"61,41",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,6.0,S. NuÃ±ez,Titular
209,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,recuperacion,duelo,2.0,NaN,"64,129",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,2.0,Flores,Titular
227,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,pelota parada,tiro de esquina,8.0,3,"258,0","239,39",Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,8.0,Trombini,Titular
250,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,interceptado,17.0,NaN,"270,20",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,17.0,Rojas,Suplente
108,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,pelota parada,lateral corto,3.0,11,"268,5","259,29",Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,3.0,T. NuÃ±ez,Titular
127,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,intercepcion aereo,3.0,9,"185,37","232,87",Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,3.0,T. NuÃ±ez,Titular
136,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,duelo,disputa suelo,2.0,NaN,"18,153",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,2.0,Flores,Titular
255,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,recuperacion,duelo,15.0,NaN,"145,30",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,15.0,J. Ascacibar,Suplente
171,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,recuperacion,intercepcion,5.0,NaN,"62,140",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,5.0,PiÃ±eiro,Titular
112,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,duelo,4.0,NaN,"215,145",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,4.0,Caccace,Titular
109,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,robo,11.0,NaN,"250,16",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,11.0,Moreno,Titular
78,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,pelota parada,lateral largo,4.0,11,"88,142","194,125",Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,4.0,Caccace,Titular
96,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,intercepcion aereo,10.0,8,"162,2","174,83",Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,10.0,Amato,Titular
51,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,error tecnico,2.0,NaN,"109,144",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,2.0,Flores,Titular

In [13]:
dftotal2.to_csv("../Datos generados para la app/reserva22-completo.csv",index=False)