In [135]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar bases

In [136]:
cols_usar = ['Equipo', 'tiempo', 'Minuto.video', 'Evento', 'Subevento',
       'Jugador.1', 'Jugador.2', 'coord.inicial',
       'coord.final', 'partido', 'segundos', 'remate-Gol', 'remate-Fuera',
       'remate-Al-arco', 'remate-Interceptado', 'remate-Cabeza',
       'pase-Asistencia', 'pase-Completado', 'pase-Incompleto',
       'pase-Inteligente', 'centro-Asistencia', 'centro-Completado',
       'centro-Interceptado', 'centro-Bloqueado', 'centro-Fuera',
       'duelo-Aereo-Perdido', 'duelo-Aereo-Ganado',
       'duelo-Disputa-suelo-Perdida', 'duelo-Disputa-suelo-Ganada',
       'duelo-Gambeta-contra-Ganada', 'duelo-Gambeta-contra-Perdida',
       'duelo-Gambeta-favor-Perdida', 'duelo-Gambeta-favor-Ganada',
       'duelo-Pivote-Perdido', 'duelo-Pivote-Ganado', 'falta-Cometida',
       'falta-Recibida', 'falta-Penal-cometido', 'falta-Penal-recibido',
       'falta-Offside', 'falta-Tarjeta-amarilla', 'falta-Tarjeta-roja',
       'recuperacion-Robo', 'recuperacion-Encontrada',
       'recuperacion-Intercepcion-suelo', 'recuperacion-Intercepcion-aereo',
       'recuperacion-Intercepcion-anticipo', 'recuperacion-Disputa-suelo',
       'parado-Lateral-interceptado', 'parado-Lateral-completado',
       'parado-Corner-interceptado', 'parado-Corner-completado',
       'parado-Tiro-libre-incompleto','parado-Tiro-libre-completado', 'perdida-Gambeta', 'perdida-Robo',
       'perdida-Intercepcion', 'perdida-Error-tecnico', 'perdida-Balon-fuera',
       'perdida-Error-tactico', 'perdida-Atajada', 'arquero-Gol-rival',
       'arquero-Atajada', 'arquero-Intercepcion-aerea', 'arquero-Intercepcion',
       'arquero-Anticipo', 'arquero-Saque-mano', 'arquero-Saque-pie',
       'arquero-Saque-meta']

In [137]:
x_max = 273
y_max = 165

# Temporada 02 - 2022

## Fecha 1 - Gimnasia

In [138]:
data211 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha1_gimnasia-tabla_filtros2.csv')
data211.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,duelo,NaN,00:22:41,00:22:41,0.0,...,0,0,0,0,0,NaN,191.362583,NaN,3.890036,NaN
1,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,perdida,NaN,00:22:42,00:22:42,0.0,...,0,0,0,0,0,NaN,211.670705,NaN,26.015066,NaN
2,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,recuperacion,NaN,00:22:44,00:22:44,0.0,...,0,0,0,0,0,NaN,215.068522,NaN,38.557102,NaN
3,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,duelo,NaN,00:22:54,00:22:54,0.0,...,0,0,0,0,0,NaN,146.483256,NaN,81.224530,NaN
4,2022/06/09,Gimnasia,GELP_FECHA1T,13:51:08,16:13:33,perdida,NaN,00:22:54,00:22:54,0.0,...,0,0,0,0,0,NaN,150.213901,NaN,80.508624,NaN

In [139]:
data212 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha1_gimnasia-tabla_filtros.csv')
data212 = data212[data212.Evento != 'perdida'].reset_index(drop=True)
data212.head()

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:36,00:22:36,0.0,...,0,0,0,0,0,11.0,98.055424,115.929743,87.232788,86.737519
1,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:39,00:22:39,0.0,...,0,0,0,0,0,13.0,124.870362,160.546943,78.351372,35.436170
2,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:50,00:22:50,0.0,...,0,0,0,0,0,17.0,155.738724,214.970639,81.718026,75.701136
3,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,pase,NaN,00:22:59,00:22:59,0.0,...,0,0,0,0,0,16.0,188.111934,216.714662,95.363577,29.177314
4,2022/06/11,Temp2Fecha1,Gimnasia,15:10:13,17:32:38,remate pie,NaN,00:23:02,00:23:02,0.0,...,0,0,0,0,0,22.0,199.691702,258.842272,37.280697,81.747534

In [140]:
data21 = pd.concat([data211, data212])
#data21 = data211

In [141]:
data21['Equipo'] = 'Estudiantes'
data21['Minuto.video'] = 10
data21 = data21[cols_usar]

## Fecha 2 - Aldosivi

In [142]:
data221 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha2_aldosivi-tabla_filtros.csv')
data221.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:12:40,00:12:40,0.0,...,0,0,0,0,0,10.0,55.580669,120.032733,148.846974,35.158805
1,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:02,00:13:02,0.0,...,0,0,0,0,0,NaN,125.892854,NaN,30.326662,NaN
2,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:13:17,00:13:17,0.0,...,0,0,0,0,0,9.0,82.870794,70.996555,139.192474,136.522403
3,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:13:20,00:13:20,0.0,...,0,0,0,0,0,NaN,5.818923,NaN,162.000000,NaN
4,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:21,00:13:21,0.0,...,0,0,0,0,0,NaN,35.862442,NaN,160.344938,NaN

In [143]:
# data22 = pd.concat([data221, data222])
data22 = data221

In [144]:
data22['Equipo'] = 'Estudiantes'
data22['Minuto.video'] = 10
data22 = data22[cols_usar]

## Fecha 3 - Sarmiento

In [145]:
data231 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha3_sarmiento-tabla_filtros.csv')
data231.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,duelo,NaN,00:15:51,00:15:51,0.0,...,0,0,0,0,0,NaN,127.733912,NaN,8.209872,NaN
1,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,recuperacion,NaN,00:15:52,00:15:52,0.0,...,0,0,0,0,0,NaN,128.498912,NaN,38.505594,NaN
2,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,perdida,NaN,00:16:03,00:16:03,0.0,...,0,0,0,0,0,NaN,177.661607,NaN,63.848860,NaN
3,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,recuperacion,NaN,00:16:22,00:16:22,0.0,...,0,0,0,0,0,NaN,21.283588,NaN,162.000000,NaN
4,2022/06/18,Sarmiento,SARMIENTO_ACCIONESFINAL,17:25:55,19:40:45,perdida,NaN,00:16:25,00:16:25,0.0,...,0,0,0,0,0,NaN,7.960795,NaN,155.977511,NaN

In [146]:
# data22 = pd.concat([data221, data222])
data23 = data231

In [147]:
data23['Equipo'] = 'Estudiantes'
data23['Minuto.video'] = 10
data23 = data23[cols_usar]

## Fecha 4 - Independiente

In [148]:
data241 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha4_independiente-tabla_filtros.csv')
data241.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,pelota parada,NaN,00:15:41,00:15:41,0.0,...,0,0,0,0,0,9.0,4.763467,63.889392,155.938367,147.631671
1,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,perdida,NaN,00:15:41,00:15:41,0.0,...,0,0,0,0,0,9.0,39.713705,74.248164,162.000000,154.162803
2,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,recuperacion,NaN,00:16:07,00:16:07,0.0,...,0,0,0,0,0,NaN,50.230007,NaN,142.661235,NaN
3,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,perdida,NaN,00:16:10,00:16:10,0.0,...,0,0,0,0,0,NaN,60.341614,NaN,140.716605,NaN
4,2022/06/24,Independiente,INDEPTE_FECHA4_ACCIONES,09:44:36,11:56:36,recuperacion,NaN,00:19:35,00:19:35,0.0,...,0,0,0,0,0,NaN,85.955701,NaN,36.345088,NaN

In [149]:
# data22 = pd.concat([data221, data222])
data24 = data241

In [150]:
data24['Equipo'] = 'Estudiantes'
data24['Minuto.video'] = 10
data24 = data24[cols_usar]

## Fecha 5 - Newells

In [151]:
data251 = pd.read_csv('../Datos generados para la app/reserva02-22-fecha5_newells-tabla_filtros.csv')
data251.head()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2022/06/29,Newells,NEWELLS_FECHA5ACCIONES,11:22:28,13:37:18,perdida,NaN,00:18:43,00:18:43,0.0,...,0,0,0,0,0,NaN,199.647221,NaN,130.355271,NaN
1,2022/06/29,Newells,NEWELLS_FECHA5ACCIONES,11:22:28,13:37:18,pelota parada,NaN,00:19:03,00:19:03,0.0,...,0,0,0,0,0,18.0,142.371393,208.057107,150.320478,151.795980
2,2022/06/29,Newells,NEWELLS_FECHA5ACCIONES,11:22:28,13:37:18,perdida,NaN,00:19:19,00:19:19,0.0,...,0,0,0,0,0,17.0,151.161197,193.862641,13.092023,83.183299
3,2022/06/29,Newells,NEWELLS_FECHA5ACCIONES,11:22:28,13:37:18,recuperacion,NaN,00:19:20,00:19:20,0.0,...,0,0,0,0,0,NaN,156.418644,NaN,88.216687,NaN
4,2022/06/29,Newells,NEWELLS_FECHA5ACCIONES,11:22:28,13:37:18,perdida,NaN,00:19:39,00:19:39,0.0,...,0,0,0,0,0,NaN,79.384975,NaN,25.961749,NaN

In [152]:
# data22 = pd.concat([data221, data222])
data25 = data251

In [153]:
data25['Equipo'] = 'Estudiantes'
data25['Minuto.video'] = 10
data25 = data25[cols_usar]

In [154]:
# df = pd.concat([data1, data2])
# df = pd.concat([df,data5])
# df = pd.concat([df,data6])
# df = pd.concat([df,data7])
# df = pd.concat([df,data8])
# df = pd.concat([df,data9])
# df = pd.concat([df,data10])
# df = pd.concat([df,data11])
# df = pd.concat([df,data12])
# df = pd.concat([df,data13])
#df.sample(15)
#df = data13
df2 = pd.concat([data21, data22,data23,data24,data25])
#df2 = data24

In [155]:
df2['Temporada'] = "Temp 02-2022"

In [156]:
df2.partido.value_counts()

Gimnasia         540
Newells          341
Independiente    272
Sarmiento        256
Aldosivi         235
Name: partido, dtype: int64

## Unir las dos temporadas

In [157]:
#dftotal = pd.concat([df,df2]).reset_index(drop=True)
dftotal = df2

In [158]:
dftotal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1644 entries, 0 to 340
Data columns (total 70 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Equipo                              1644 non-null   object
 1   tiempo                              1644 non-null   object
 2   Minuto.video                        1644 non-null   int64
 3   Evento                              1644 non-null   object
 4   Subevento                           1644 non-null   object
 5   Jugador.1                           1643 non-null   float64
 6   Jugador.2                           599 non-null    object
 7   coord.inicial                       1644 non-null   object
 8   coord.final                         598 non-null    object
 9   partido                             1644 non-null   object
 10  segundos                            1644 non-null   float64
 11  remate-Gol                          1644 non-null   int64
 12  remate-Fuera                        1644 non-null   int64
 13  remate-Al-arco                      1644 non-null   int64
 14  remate-Interceptado                 1644 non-null   int64
 15  remate-Cabeza                       1644 non-null   int64
 16  pase-Asistencia                     1644 non-null   int64
 17  pase-Completado                     1644 non-null   int64
 18  pase-Incompleto                     1644 non-null   int64
 19  pase-Inteligente                    1644 non-null   int64
 20  centro-Asistencia                   1644 non-null   int64
 21  centro-Completado                   1644 non-null   int64
 22  centro-Interceptado                 1644 non-null   int64
 23  centro-Bloqueado                    1644 non-null   int64
 24  centro-Fuera                        1644 non-null   int64
 25  duelo-Aereo-Perdido                 1644 non-null   int64
 26  duelo-Aereo-Ganado                  1644 non-null   int64
 27  duelo-Disputa-suelo-Perdida         1644 non-null   int64
 28  duelo-Disputa-suelo-Ganada          1644 non-null   int64
 29  duelo-Gambeta-contra-Ganada         1644 non-null   int64
 30  duelo-Gambeta-contra-Perdida        1644 non-null   int64
 31  duelo-Gambeta-favor-Perdida         1644 non-null   int64
 32  duelo-Gambeta-favor-Ganada          1644 non-null   int64
 33  duelo-Pivote-Perdido                1644 non-null   int64
 34  duelo-Pivote-Ganado                 1644 non-null   int64
 35  falta-Cometida                      1644 non-null   int64
 36  falta-Recibida                      1644 non-null   int64
 37  falta-Penal-cometido                1644 non-null   int64
 38  falta-Penal-recibido                1644 non-null   int64
 39  falta-Offside                       1644 non-null   int64
 40  falta-Tarjeta-amarilla              1644 non-null   int64
 41  falta-Tarjeta-roja                  1644 non-null   int64
 42  recuperacion-Robo                   1644 non-null   int64
 43  recuperacion-Encontrada             1644 non-null   int64
 44  recuperacion-Intercepcion-suelo     1644 non-null   int64
 45  recuperacion-Intercepcion-aereo     1644 non-null   int64
 46  recuperacion-Intercepcion-anticipo  1644 non-null   int64
 47  recuperacion-Disputa-suelo          1644 non-null   int64
 48  parado-Lateral-interceptado         1644 non-null   int64
 49  parado-Lateral-completado           1644 non-null   int64
 50  parado-Corner-interceptado          1644 non-null   int64
 51  parado-Corner-completado            1644 non-null   int64
 52  parado-Tiro-libre-incompleto        1644 non-null   int64
 53  parado-Tiro-libre-completado        1644 non-null   int64
 54  perdida-Gambeta                     1644 non-null   int64
 55  perdida-Robo                        1644 non-null   int64
 56  perdida-Intercepcion                1644 non-null   int64
 57  perdida-Error-tecnico               1644 non-null   int64
 58  perdida-Balon-fuera                 1644 non-null   int64
 59  perdida-Error-tactico               1644 non-null   int64
 60  perdida-Atajada                     1644 non-null   int64
 61  arquero-Gol-rival                   1644 non-null   int64
 62  arquero-Atajada                     1644 non-null   int64
 63  arquero-Intercepcion-aerea          1644 non-null   int64
 64  arquero-Intercepcion                1644 non-null   int64
 65  arquero-Anticipo                    1644 non-null   int64
 66  arquero-Saque-mano                  1644 non-null   int64
 67  arquero-Saque-pie                   1644 non-null   int64
 68  arquero-Saque-meta                  1644 non-null   int64
 69  Temporada                           1644 non-null   object
dtypes: float64(2), int64(59), object(9)
memory usage: 911.9+ KB

## Meter los apellidos

In [159]:
formaciones = pd.read_excel('../Datos generados para la app/Formaciones Reserva 2022.xlsx')
formaciones.head()

         Partido  Numero_jugador   Apellido   Estado     Temporada
0  Independiente             1.0     Zozaya  Titular  Temp 01-2022
1  Independiente             3.0  Fernandez  Titular  Temp 01-2022
2  Independiente             6.0   S. NuÃ±ez  Titular  Temp 01-2022
3  Independiente             2.0     Flores  Titular  Temp 01-2022
4  Independiente             4.0    Rosales  Titular  Temp 01-2022

In [160]:
dftotal2 = dftotal.merge(formaciones,how='left',left_on=(['Temporada','partido','Jugador.1']), right_on=(['Temporada','Partido','Numero_jugador']))
dftotal2.sample(15)

,Equipo,tiempo,Minuto.video,Evento,Subevento,Jugador.1,Jugador.2,coord.inicial,coord.final,partido,...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,Temporada,Partido,Numero_jugador,Apellido,Estado
751,Estudiantes,ALDOSIVI_FECHA2_ACCIONES,10,recuperacion,robo,7.0,NaN,"203,123",NaN,Aldosivi,...,0,0,0,0,0,Temp 02-2022,Aldosivi,7.0,Arango,Titular
11,Estudiantes,GELP_FECHA1T,10,recuperacion,intercepcion anticipo,10.0,NaN,"81,99",NaN,Gimnasia,...,0,0,0,0,0,Temp 02-2022,Gimnasia,10.0,Rojas,Titular
1415,Estudiantes,NEWELLS_FECHA5ACCIONES,10,perdida,interceptado,3.0,7.0,"71,13","104,84",Newells,...,0,0,0,0,0,Temp 02-2022,Newells,3.0,T. NuÃ±ez,Titular
313,Estudiantes,Temp2Fecha1,10,pase,inteligente,10.0,11,"162,11","270,39",Gimnasia,...,0,0,0,0,0,Temp 02-2022,Gimnasia,10.0,Rojas,Titular
127,Estudiantes,GELP_FECHA1T,10,duelo,disputa suelo,10.0,NaN,"112,69",NaN,Gimnasia,...,0,0,0,0,0,Temp 02-2022,Gimnasia,10.0,Rojas,Titular
1177,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,perdida,duelo,5.0,NaN,"239,100",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,5.0,PiÃ±eiro,Titular
1490,Estudiantes,NEWELLS_FECHA5ACCIONES,10,recuperacion,intercepcion anticipo,4.0,NaN,"118,87",NaN,Newells,...,0,0,0,0,0,Temp 02-2022,Newells,4.0,Caccace,Titular
454,Estudiantes,Temp2Fecha1,10,pase,medio,3.0,18,"76,38","173,7",Gimnasia,...,0,0,0,0,0,Temp 02-2022,Gimnasia,3.0,T. NuÃ±ez,Titular
618,Estudiantes,ALDOSIVI_FECHA2_ACCIONES,10,perdida,error tecnico,11.0,NaN,"194,151",NaN,Aldosivi,...,0,0,0,0,0,Temp 02-2022,Aldosivi,11.0,A. Palavecino,Titular
1574,Estudiantes,NEWELLS_FECHA5ACCIONES,10,recuperacion,duelo,3.0,NaN,"159,2",NaN,Newells,...,0,0,0,0,0,Temp 02-2022,Newells,3.0,T. NuÃ±ez,Titular
599,Estudiantes,ALDOSIVI_FECHA2_ACCIONES,10,perdida,duelo,7.0,NaN,"170,14",NaN,Aldosivi,...,0,0,0,0,0,Temp 02-2022,Aldosivi,7.0,Arango,Titular
1192,Estudiantes,INDEPTE_FECHA4_ACCIONES,10,recuperacion,encontrada,2.0,NaN,"49,140",NaN,Independiente,...,0,0,0,0,0,Temp 02-2022,Independiente,2.0,Flores,Titular
1638,Estudiantes,NEWELLS_FECHA5ACCIONES,10,duelo,aereo,6.0,NaN,"177,65",NaN,Newells,...,0,0,0,0,0,Temp 02-2022,Newells,6.0,S. NuÃ±ez,Titular
980,Estudiantes,SARMIENTO_ACCIONESFINAL,10,perdida,intercepcion aereo,3.0,9,"83,79","167,34",Sarmiento,...,0,0,0,0,0,Temp 02-2022,Sarmiento,3.0,T. NuÃ±ez,Titular
280,Estudiantes,Temp2Fecha1,10,pase,medio,10.0,8,"270,10","250,66",Gimnasia,...,0,0,0,0,0,Temp 02-2022,Gimnasia,10.0,Rojas,Titular

In [161]:
dftotal2.to_csv("../Datos generados para la app/reserva22-completo.csv",index=False)