In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import glob
import os
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [2]:
# merging the files
files_joined = os.path.join('..\\..\\datos etiquetas\\Tem2-2022\\Fecha 4 - Independiente', "*.csv")

# Return a list of all joined files
list_files = glob.glob(files_joined)

#print("** Merging multiple csv files into a single pandas dataframe **")
# Merge files by joining all files
data = pd.concat(map(pd.read_csv, list_files), ignore_index=True)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   249 non-null    object
 1   Event                249 non-null    object
 2   Session Name         249 non-null    object
 3   Session Start        249 non-null    object
 4   Session End          249 non-null    object
 5   Tag Description      249 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            249 non-null    object
 8   Tag End              249 non-null    object
 9   Tag Duration (secs)  249 non-null    float64
 10  Zonas_final          249 non-null    object
 11  Jugador2             196 non-null    object
 12  Jugador              245 non-null    float64
 13  Calificacion         4 non-null      object
 14  Zonas                246 non-null    float64
 15  Categoria            246 non-null    object
 16  Optional Column      0 non-null      float64
dtypes: float64(5), object(12)
memory usage: 33.2+ KB

In [4]:
# data.columns = ['Session Start Date','partido','tiempo','Session Start',
#        'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
#        'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Optional Column']

data.columns = ['Session Start Date','tiempo','partido','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','coord final','Jugador 2','Jugador 1','Calificacion','coord inicial','Subevento','Optional Column']

In [5]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [6]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   249 non-null    object
 1   tiempo               249 non-null    object
 2   partido              249 non-null    object
 3   Session Start        249 non-null    object
 4   Session End          249 non-null    object
 5   Evento               249 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            249 non-null    object
 8   Tag End              249 non-null    object
 9   Tag Duration (secs)  249 non-null    float64
 10  coord final          249 non-null    object
 11  Jugador 2            196 non-null    object
 12  Jugador 1            245 non-null    float64
 13  Calificacion         4 non-null      object
 14  coord inicial        246 non-null    float64
 15  Subevento            246 non-null    object
 16  Optional Column      0 non-null      float64
 17  segundos             249 non-null    float64
dtypes: float64(6), object(12)
memory usage: 35.3+ KB

In [8]:
data

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos
0,2022/07/06,independiente,pases,17:20:45,19:32:44,Pase,NaN,00:16:35,00:16:35,0.0,2,6,1.0,NaN,3.0,S arquero pie,NaN,995.0
1,2022/07/06,independiente,pases,17:20:45,19:32:44,Pase,NaN,00:16:42,00:16:42,0.0,9,2,6.0,NaN,7.0,medio,NaN,1002.0
2,2022/07/06,independiente,pases,17:20:45,19:32:44,Pase,NaN,00:16:47,00:16:47,0.0,4,1,2.0,NaN,9.0,corto,NaN,1007.0
3,2022/07/06,independiente,pases,17:20:45,19:32:44,Pase,NaN,00:16:50,00:16:50,0.0,7,6,1.0,NaN,4.0,corto,NaN,1010.0
4,2022/07/06,independiente,pases,17:20:45,19:32:44,Pase,NaN,00:16:55,00:16:55,0.0,8,1,6.0,NaN,7.0,corto,NaN,1015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2022/07/06,independiente,pases,17:20:45,19:32:44,Pase,NaN,02:03:16,02:03:16,0.0,12,4,2.0,NaN,5.0,corto,NaN,7396.0
246,2022/07/06,independiente,pases,17:20:45,19:32:44,Pase,NaN,02:03:21,02:03:21,0.0,24,21,4.0,NaN,12.0,medio,NaN,7401.0
247,2022/07/06,independiente,pases,17:20:45,19:32:44,Remate pie,NaN,02:03:37,02:03:37,0.0,22,Rival,21.0,NaN,17.0,Corta distancia,NaN,7417.0
248,2022/07/06,independiente,pases,17:20:45,19:32:44,Arquero,NaN,02:04:23,02:04:23,0.0,Volver,NaN,1.0,Bueno,5.0,Salvada/Atajada,NaN,7463.0
249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [10]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [11]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       rebote/despeje               1
              remate atajable              5
              salida suelo                 1
              salvada/atajada              3
falta         hecha                        5
              recibida                    20
gol           directa                      1
gol rival     indirecta                    1
pase          centro aereo                 3
              corto                      138
              largo                        2
              medio                       30
              s arquero mano               3
              s arquero pie                5
perdida       balon afuera fondo           2
              balon afuera lateral         1
              interceptado                 9
              robo                         2
remate cabeza dificil                      2
              remate bloqueado             1
remate pie    corta distancia              4
              larga distancia              1
              media distancia              2
              remate bloqueado             2
tarjeta       amarilla                     2

In [12]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                      cantidad
Jugador 1 Evento     Subevento
1.0       arquero    rebote/despeje          1
                     remate atajable         5
                     salida suelo            1
                     salvada/atajada         3
          pase       corto                  11
...                                        ...
16.0      pase       corto                   1
          perdida    interceptado            1
17.0      pase       corto                   1
21.0      pase       corto                   1
          remate pie corta distancia         1

[73 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [13]:
data_eventos = data.copy()
data_eventos.shape

(250, 18)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [14]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
data_eventos.loc[data_eventos['remate-Gol'] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol
155,2022/07/06,independiente,pases,17:20:45,19:32:44,remate pie,NaN,01:23:33,01:23:33,0.0,22,Rival,11.0,NaN,22.0,corta distancia,NaN,5013.0,1

In [15]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera
36,2022/07/06,independiente,pases,17:20:45,19:32:44,remate pie,NaN,00:25:50,00:25:50,0.0,22,Rival,8.0,NaN,17.0,media distancia,NaN,1550.0,0,1

In [16]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco]
Index: []

[0 rows x 21 columns]

In [17]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado
17,2022/07/06,independiente,pases,17:20:45,19:32:44,remate pie,NaN,00:20:18,00:20:18,0.0,...,7.0,NaN,24.0,remate bloqueado,NaN,1218.0,0,0,0,1
19,2022/07/06,independiente,pases,17:20:45,19:32:44,remate cabeza,NaN,00:21:41,00:21:41,0.0,...,6.0,NaN,21.0,remate bloqueado,NaN,1301.0,0,0,0,1
56,2022/07/06,independiente,pases,17:20:45,19:32:44,remate pie,NaN,00:30:44,00:30:44,0.0,...,11.0,NaN,19.0,remate bloqueado,NaN,1844.0,0,0,0,1

In [18]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
19,2022/07/06,independiente,pases,17:20:45,19:32:44,remate cabeza,NaN,00:21:41,00:21:41,0.0,...,NaN,21.0,remate bloqueado,NaN,1301.0,0,0,0,1,1
187,2022/07/06,independiente,pases,17:20:45,19:32:44,remate cabeza,NaN,01:35:23,01:35:23,0.0,...,NaN,21.0,dificil,NaN,5723.0,0,0,0,0,1
229,2022/07/06,independiente,pases,17:20:45,19:32:44,remate cabeza,NaN,01:51:50,01:51:50,0.0,...,NaN,21.0,dificil,NaN,6710.0,0,0,0,0,1

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [19]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                       cantidad
Evento Subevento
pase   centro aereo           3
       corto                138
       largo                  2
       medio                 30
       s arquero mano         3
       s arquero pie          5

In [20]:
data[(data.Evento=='pase')]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos
0,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:35,00:16:35,0.0,2,6,1.0,NaN,3.0,s arquero pie,NaN,995.0
1,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:42,00:16:42,0.0,9,2,6.0,NaN,7.0,medio,NaN,1002.0
2,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:47,00:16:47,0.0,4,1,2.0,NaN,9.0,corto,NaN,1007.0
3,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:50,00:16:50,0.0,7,6,1.0,NaN,4.0,corto,NaN,1010.0
4,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:55,00:16:55,0.0,8,1,6.0,NaN,7.0,corto,NaN,1015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:53:28,01:53:28,0.0,13,6,17.0,NaN,13.0,corto,NaN,6808.0
237,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:53:30,01:53:30,0.0,17,8,6.0,NaN,13.0,corto,NaN,6810.0
243,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:02:42,02:02:42,0.0,16,17,16.0,NaN,16.0,corto,NaN,7362.0
245,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:03:16,02:03:16,0.0,12,4,2.0,NaN,5.0,corto,NaN,7396.0
246,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:03:21,02:03:21,0.0,24,21,4.0,NaN,12.0,medio,NaN,7401.0

In [21]:
data_eventos.head()

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
0,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:35,00:16:35,0.0,...,NaN,3.0,s arquero pie,NaN,995.0,0,0,0,0,0
1,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:42,00:16:42,0.0,...,NaN,7.0,medio,NaN,1002.0,0,0,0,0,0
2,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:47,00:16:47,0.0,...,NaN,9.0,corto,NaN,1007.0,0,0,0,0,0
3,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:50,00:16:50,0.0,...,NaN,4.0,corto,NaN,1010.0,0,0,0,0,0
4,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:55,00:16:55,0.0,...,NaN,7.0,corto,NaN,1015.0,0,0,0,0,0

In [22]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''
colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia
154,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:23:30,01:23:30,0.0,...,21.0,corto,NaN,5010.0,0,0,0,0,0,1

In [23]:
##completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') & (data_eventos.loc[i,'Jugador 2'] != 'Rival')):
        if ((data_eventos.loc[i+1,'Evento'] != 'perdida') ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado
1,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:42,00:16:42,0.0,...,medio,NaN,1002.0,0,0,0,0,0,0,1
2,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:47,00:16:47,0.0,...,corto,NaN,1007.0,0,0,0,0,0,0,1
3,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:50,00:16:50,0.0,...,corto,NaN,1010.0,0,0,0,0,0,0,1
4,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:55,00:16:55,0.0,...,corto,NaN,1015.0,0,0,0,0,0,0,1
5,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:57,00:16:57,0.0,...,corto,NaN,1017.0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:53:21,01:53:21,0.0,...,corto,NaN,6801.0,0,0,0,0,0,0,1
235,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:53:26,01:53:26,0.0,...,corto,NaN,6806.0,0,0,0,0,0,0,1
236,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:53:28,01:53:28,0.0,...,corto,NaN,6808.0,0,0,0,0,0,0,1
245,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:03:16,02:03:16,0.0,...,corto,NaN,7396.0,0,0,0,0,0,0,1
246,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:03:21,02:03:21,0.0,...,medio,NaN,7401.0,0,0,0,0,0,0,1

In [24]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

corto           132
medio            27
largo             1
centro aereo      1
Name: Subevento, dtype: int64

In [25]:
#Incompleto
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Incompleto'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') ):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') ):
            #if ((data_eventos.loc[i,'pase-Completado'] != 1)):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto
12,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:19:07,00:19:07,0.0,...,NaN,1147.0,0,0,0,0,0,0,0,1
23,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:22:35,00:22:35,0.0,...,NaN,1355.0,0,0,0,0,0,0,0,1
44,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:28:33,00:28:33,0.0,...,NaN,1713.0,0,0,0,0,0,0,0,1
51,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:29:42,00:29:42,0.0,...,NaN,1782.0,0,0,0,0,0,0,0,1
60,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:31:06,00:31:06,0.0,...,NaN,1866.0,0,0,0,0,0,0,0,1
74,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:36:18,00:36:18,0.0,...,NaN,2178.0,0,0,0,0,0,0,0,1
88,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:42:14,00:42:14,0.0,...,NaN,2534.0,0,0,0,0,0,0,0,1
146,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:17:41,01:17:41,0.0,...,NaN,4661.0,0,0,0,0,0,0,0,1
197,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:36:57,01:36:57,0.0,...,NaN,5817.0,0,0,0,0,0,0,0,1
224,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:45:56,01:45:56,0.0,...,NaN,6356.0,0,0,0,0,0,0,0,1
237,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:53:30,01:53:30,0.0,...,NaN,6810.0,0,0,0,0,0,0,0,1
243,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:02:42,02:02:42,0.0,...,NaN,7362.0,0,0,0,0,0,0,0,1

In [26]:
# #fuera
# '''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

# colname = 'pase-Fuera'
# data_eventos[colname] = 0
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
#         if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
#             if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
#                 data_eventos.loc[i,colname] = 1
            
# data_eventos.loc[data_eventos[colname] == 1]

In [27]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente]
Index: []

[0 rows x 27 columns]

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [28]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       rebote/despeje               1
              remate atajable              5
              salida suelo                 1
              salvada/atajada              3
falta         hecha                        5
              recibida                    20
gol           directa                      1
gol rival     indirecta                    1
pase          centro aereo                 3
              corto                      138
              largo                        2
              medio                       30
              s arquero mano               3
              s arquero pie                5
perdida       balon afuera fondo           2
              balon afuera lateral         1
              interceptado                 9
              robo                         2
remate cabeza dificil                      2
              remate bloqueado             1
remate pie    corta distancia              4
              larga distancia              1
              media distancia              2
              remate bloqueado             2
tarjeta       amarilla                     2

In [29]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 28 columns]

In [30]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado
18,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:21:39,00:21:39,0.0,...,0,0,0,0,0,1,0,0,0,1

In [31]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado
23,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:22:35,00:22:35,0.0,...,0,0,0,0,0,1,0,0,0,1
74,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:36:18,00:36:18,0.0,...,0,0,0,0,0,1,0,0,0,1

In [32]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 31 columns]

In [33]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 32 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [34]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       rebote/despeje               1
              remate atajable              5
              salida suelo                 1
              salvada/atajada              3
falta         hecha                        5
              recibida                    20
gol           directa                      1
gol rival     indirecta                    1
pase          centro aereo                 3
              corto                      138
              largo                        2
              medio                       30
              s arquero mano               3
              s arquero pie                5
perdida       balon afuera fondo           2
              balon afuera lateral         1
              interceptado                 9
              robo                         2
remate cabeza dificil                      2
              remate bloqueado             1
remate pie    corta distancia              4
              larga distancia              1
              media distancia              2
              remate bloqueado             2
tarjeta       amarilla                     2

In [35]:
# dejar_index= []
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='duelo'):
#         dejar_index.append(i-1)
#         dejar_index.append(i)
#         dejar_index.append(i+1)
# data_eventos.loc[dejar_index].head(10)

In [36]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1


data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado]
Index: []

[0 rows x 34 columns]

In [37]:
data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado]
Index: []

[0 rows x 34 columns]

In [38]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada]
Index: []

[0 rows x 36 columns]

In [39]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada]
Index: []

[0 rows x 36 columns]

In [40]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [41]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [42]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada]
Index: []

[0 rows x 40 columns]

In [43]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada]
Index: []

[0 rows x 40 columns]

In [44]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 42 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [45]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       rebote/despeje               1
              remate atajable              5
              salida suelo                 1
              salvada/atajada              3
falta         hecha                        5
              recibida                    20
gol           directa                      1
gol rival     indirecta                    1
pase          centro aereo                 3
              corto                      138
              largo                        2
              medio                       30
              s arquero mano               3
              s arquero pie                5
perdida       balon afuera fondo           2
              balon afuera lateral         1
              interceptado                 9
              robo                         2
remate cabeza dificil                      2
              remate bloqueado             1
remate pie    corta distancia              4
              larga distancia              1
              media distancia              2
              remate bloqueado             2
tarjeta       amarilla                     2

In [46]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida
120,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:52:48,00:52:48,0.0,...,0,0,0,0,0,0,0,0,0,1
123,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:55:26,00:55:26,0.0,...,0,0,0,0,0,0,0,0,0,1
157,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:24:46,01:24:46,0.0,...,0,0,0,0,0,0,0,0,0,1
165,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:29:22,01:29:22,0.0,...,0,0,0,0,0,0,0,0,0,1
226,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:46:17,01:46:17,0.0,...,0,0,0,0,0,0,0,0,0,1

In [47]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida
38,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:27:28,00:27:28,0.0,...,0,0,0,0,0,0,0,0,0,1
40,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:27:54,00:27:54,0.0,...,0,0,0,0,0,0,0,0,0,1
62,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:31:26,00:31:26,0.0,...,0,0,0,0,0,0,0,0,0,1
63,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:33:29,00:33:29,0.0,...,0,0,0,0,0,0,0,0,0,1
76,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:38:48,00:38:48,0.0,...,0,0,0,0,0,0,0,0,0,1
91,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:43:55,00:43:55,0.0,...,0,0,0,0,0,0,0,0,0,1
122,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:54:15,00:54:15,0.0,...,0,0,0,0,0,0,0,0,0,1
129,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:56:39,00:56:39,0.0,...,0,0,0,0,0,0,0,0,0,1
138,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:59:12,00:59:12,0.0,...,0,0,0,0,0,0,0,0,0,1
150,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:19:44,01:19:44,0.0,...,0,0,0,0,0,0,0,0,0,1
151,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:20:54,01:20:54,0.0,...,0,0,0,0,0,0,0,0,0,1
153,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:22:40,01:22:40,0.0,...,0,0,0,0,0,0,0,0,0,1
166,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:30:07,01:30:07,0.0,...,0,0,0,0,0,0,0,0,0,1
193,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:36:10,01:36:10,0.0,...,0,0,0,0,0,0,0,0,0,1
212,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:41:39,01:41:39,0.0,...,0,0,0,0,0,0,0,0,0,1
228,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:50:12,01:50:12,0.0,...,0,0,0,0,0,0,0,0,0,1
231,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:52:26,01:52:26,0.0,...,0,0,0,0,0,0,0,0,0,1
239,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:55:50,01:55:50,0.0,...,0,0,0,0,0,0,0,0,0,1
241,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:59:03,01:59:03,0.0,...,0,0,0,0,0,0,0,0,0,1
242,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,02:00:07,02:00:07,0.0,...,0,0,0,0,0,0,0,0,0,1

In [48]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 45 columns]

In [49]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 46 columns]

In [50]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside]
Index: []

[0 rows x 47 columns]

In [51]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla
120,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,00:52:48,00:52:48,0.0,...,0,0,0,0,1,0,0,0,0,1
157,2022/07/06,independiente,pases,17:20:45,19:32:44,falta,NaN,01:24:46,01:24:46,0.0,...,0,0,0,0,1,0,0,0,0,1

In [52]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja]
Index: []

[0 rows x 49 columns]

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [53]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       rebote/despeje               1
              remate atajable              5
              salida suelo                 1
              salvada/atajada              3
falta         hecha                        5
              recibida                    20
gol           directa                      1
gol rival     indirecta                    1
pase          centro aereo                 3
              corto                      138
              largo                        2
              medio                       30
              s arquero mano               3
              s arquero pie                5
perdida       balon afuera fondo           2
              balon afuera lateral         1
              interceptado                 9
              robo                         2
remate cabeza dificil                      2
              remate bloqueado             1
remate pie    corta distancia              4
              larga distancia              1
              media distancia              2
              remate bloqueado             2
tarjeta       amarilla                     2

In [54]:
colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo]
Index: []

[0 rows x 50 columns]

In [55]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada]
Index: []

[0 rows x 51 columns]

In [56]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo]
Index: []

[0 rows x 52 columns]

In [57]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo]
Index: []

[0 rows x 53 columns]

In [58]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo]
Index: []

[0 rows x 54 columns]

In [59]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if (data_eventos.loc[i,'Evento'] == 'recuperacion') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo]
Index: []

[0 rows x 55 columns]

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [60]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       rebote/despeje               1
              remate atajable              5
              salida suelo                 1
              salvada/atajada              3
falta         hecha                        5
              recibida                    20
gol           directa                      1
gol rival     indirecta                    1
pase          centro aereo                 3
              corto                      138
              largo                        2
              medio                       30
              s arquero mano               3
              s arquero pie                5
perdida       balon afuera fondo           2
              balon afuera lateral         1
              interceptado                 9
              robo                         2
remate cabeza dificil                      2
              remate bloqueado             1
remate pie    corta distancia              4
              larga distancia              1
              media distancia              2
              remate bloqueado             2
tarjeta       amarilla                     2

In [61]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado]
Index: []

[0 rows x 57 columns]

In [62]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado]
Index: []

[0 rows x 57 columns]

In [63]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 59 columns]

In [64]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 59 columns]

In [65]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado]
Index: []

[0 rows x 61 columns]

In [66]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado]
Index: []

[0 rows x 61 columns]

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [67]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       rebote/despeje               1
              remate atajable              5
              salida suelo                 1
              salvada/atajada              3
falta         hecha                        5
              recibida                    20
gol           directa                      1
gol rival     indirecta                    1
pase          centro aereo                 3
              corto                      138
              largo                        2
              medio                       30
              s arquero mano               3
              s arquero pie                5
perdida       balon afuera fondo           2
              balon afuera lateral         1
              interceptado                 9
              robo                         2
remate cabeza dificil                      2
              remate bloqueado             1
remate pie    corta distancia              4
              larga distancia              1
              media distancia              2
              remate bloqueado             2
tarjeta       amarilla                     2

In [68]:
# data_eventos = data_eventos[~data_eventos.Subevento.isna()].reset_index(drop=True)

In [69]:
data_eventos[data_eventos.Evento == 'perdida']

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
13,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:19:10,00:19:10,0.0,...,0,0,0,0,0,0,0,0,0,0
24,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:22:35,00:22:35,0.0,...,0,0,0,0,0,0,0,0,0,0
37,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:25:50,00:25:50,0.0,...,0,0,0,0,0,0,0,0,0,0
45,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:28:33,00:28:33,0.0,...,0,0,0,0,0,0,0,0,0,0
52,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:29:44,00:29:44,0.0,...,0,0,0,0,0,0,0,0,0,0
61,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:31:07,00:31:07,0.0,...,0,0,0,0,0,0,0,0,0,0
75,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:36:19,00:36:19,0.0,...,0,0,0,0,0,0,0,0,0,0
89,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,00:42:14,00:42:14,0.0,...,0,0,0,0,0,0,0,0,0,0
147,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,01:17:43,01:17:43,0.0,...,0,0,0,0,0,0,0,0,0,0
198,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,01:36:57,01:36:57,0.0,...,0,0,0,0,0,0,0,0,0,0
214,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,01:43:29,01:43:29,0.0,...,0,0,0,0,0,0,0,0,0,0
225,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,01:45:57,01:45:57,0.0,...,0,0,0,0,0,0,0,0,0,0
238,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,01:53:31,01:53:31,0.0,...,0,0,0,0,0,0,0,0,0,0
244,2022/07/06,independiente,pases,17:20:45,19:32:44,perdida,NaN,02:02:44,02:02:44,0.0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
#gambeta a favor

colname = 'perdida-Gambeta'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     #if (data_eventos.loc[i-1,'Evento']=='duelo') & (data_eventos.loc[i-1,'Subevento']=='gambeta a favor'):
#         if (data_eventos.loc[i,'Evento'] == 'perdida') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
#             data_eventos.loc[i,colname] = 1
# 
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta]
Index: []

[0 rows x 62 columns]

In [71]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida') & ((data_eventos.loc[i,'Subevento']=='robo')):
#             data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo]
Index: []

[0 rows x 63 columns]

In [72]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion]
Index: []

[0 rows x 64 columns]

In [73]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
#             data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico]
Index: []

[0 rows x 65 columns]

In [74]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida'):
#         if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
#             data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera]
Index: []

[0 rows x 66 columns]

In [75]:
#situacion rival

colname = 'perdida-Error-tactico'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida'):
#         if (data_eventos.loc[i,'Subevento']=='error tactico'):
#             data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico]
Index: []

[0 rows x 67 columns]

In [76]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida'):
#         if (data_eventos.loc[i,'Subevento']=='atajada'):
#             data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada]
Index: []

[0 rows x 68 columns]

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [77]:
data[data['Jugador 1'] == 1].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                            cantidad
Evento  Subevento
arquero rebote/despeje             1
        remate atajable            5
        salida suelo               1
        salvada/atajada            3
pase    corto                     11
        medio                      7
        s arquero mano             3
        s arquero pie              5
perdida balon afuera fondo         1

In [78]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Tiro-libre-completado,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable
110,2022/07/06,independiente,pases,17:20:45,19:32:44,gol rival,NaN,00:47:29,00:47:29,0.0,...,0,0,0,0,0,0,0,0,1,0

In [79]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in data_eventos.loc[i,'Subevento']) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            # if ('remate' in data_eventos.loc[i-1,'Evento']):
            #     data_eventos.loc[i-1,colname] = 1
            # elif ('remate' in data_eventos.loc[i-2,'Evento']):
            #     data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada
8,2022/07/06,independiente,pases,17:20:45,19:32:44,arquero,NaN,00:18:45,00:18:45,0.0,...,0,0,0,0,0,0,0,0,0,1
159,2022/07/06,independiente,pases,17:20:45,19:32:44,arquero,NaN,01:25:50,01:25:50,0.0,...,0,0,0,0,0,0,0,0,0,1
248,2022/07/06,independiente,pases,17:20:45,19:32:44,arquero,NaN,02:04:23,02:04:23,0.0,...,0,0,0,0,0,0,0,0,0,1

In [80]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [81]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 72 columns]

In [82]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 73 columns]

In [83]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 74 columns]

In [84]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano
9,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:18:55,00:18:55,0.0,...,0,0,0,0,0,0,0,0,0,1
54,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:30:34,00:30:34,0.0,...,0,0,0,0,0,0,0,0,0,1
175,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:33:20,01:33:20,0.0,...,0,0,0,0,0,0,0,0,0,1

In [85]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie
0,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:35,00:16:35,0.0,...,0,0,0,0,0,0,0,0,0,1
77,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:40:25,00:40:25,0.0,...,0,0,0,0,0,0,0,0,0,1
149,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:19:31,01:19:31,0.0,...,0,0,0,0,0,0,0,0,0,1
206,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:40:02,01:40:02,0.0,...,0,0,0,0,0,0,0,0,0,1
213,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,01:43:28,01:43:28,0.0,...,0,0,0,0,0,0,0,0,0,1

In [86]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 77 columns]

In [87]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [88]:
data_eventos.iloc[:,:20]

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),coord.final,Jugador.2,Jugador.1,Calificacion,coord.inicial,Subevento,Optional.Column,segundos,remate-Gol,remate-Fuera
0,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:35,00:16:35,0.0,2,6,1.0,NaN,3.0,s arquero pie,NaN,995.0,0,0
1,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:42,00:16:42,0.0,9,2,6.0,NaN,7.0,medio,NaN,1002.0,0,0
2,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:47,00:16:47,0.0,4,1,2.0,NaN,9.0,corto,NaN,1007.0,0,0
3,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:50,00:16:50,0.0,7,6,1.0,NaN,4.0,corto,NaN,1010.0,0,0
4,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,00:16:55,00:16:55,0.0,8,1,6.0,NaN,7.0,corto,NaN,1015.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:03:16,02:03:16,0.0,12,4,2.0,NaN,5.0,corto,NaN,7396.0,0,0
246,2022/07/06,independiente,pases,17:20:45,19:32:44,pase,NaN,02:03:21,02:03:21,0.0,24,21,4.0,NaN,12.0,medio,NaN,7401.0,0,0
247,2022/07/06,independiente,pases,17:20:45,19:32:44,remate pie,NaN,02:03:37,02:03:37,0.0,22,Rival,21.0,NaN,17.0,corta distancia,NaN,7417.0,0,0
248,2022/07/06,independiente,pases,17:20:45,19:32:44,arquero,NaN,02:04:23,02:04:23,0.0,Volver,NaN,1.0,Bueno,5.0,salvada/atajada,NaN,7463.0,0,0
249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [89]:
data_eventos['coord.inicial'].value_counts()

7.0     34
12.0    27
9.0     18
17.0    17
15.0    14
13.0    14
18.0    14
3.0     13
8.0     13
10.0    10
4.0     10
11.0    10
19.0     8
14.0     8
21.0     7
24.0     7
16.0     7
2.0      4
5.0      4
6.0      2
22.0     2
20.0     2
1.0      1
Name: coord.inicial, dtype: int64

In [90]:
data_eventos['coord.final'].value_counts()

Volver    56
7         16
15        16
10        16
12        15
22        14
18        13
9         13
14        12
11        10
8          9
13         8
2          7
4          7
17         7
16         7
21         5
24         5
19         4
5          3
6          2
23         2
20         1
3          1
Name: coord.final, dtype: int64

In [91]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [92]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [93]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [94]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2.0,12.0,21.0,82.0,43.0
1,9.0,68.0,65.0,22.0,141.0
2,4.0,65.0,33.0,141.0,83.0
3,7.0,33.0,68.0,83.0,22.0
4,8.0,68.0,66.0,22.0,81.0
...,...,...,...,...,...
245,12.0,21.0,105.0,117.0,138.0
246,24.0,105.0,250.0,138.0,147.0
247,22.0,203.0,260.0,80.0,81.0
248,NaN,21.0,NaN,117.0,NaN
249,NaN,NaN,NaN,NaN,NaN

In [95]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    246.000000
mean     122.069106
std       72.225097
min       12.000000
25%       66.000000
50%      105.000000
75%      203.000000
max      260.000000
Name: coord.inicial.x, dtype: float64

In [96]:
# añadirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    246.000000
mean     122.793500
std       74.122048
min       -4.485217
25%       63.690751
50%      110.029033
75%      187.218207
max      278.947321
Name: coord.inicial.x, dtype: float64

In [97]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [98]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    246.000000
mean      82.841463
std       48.144121
min       18.000000
25%       22.000000
50%       81.000000
75%      138.000000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [99]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    246.000000
mean      82.781988
std       49.241802
min        1.113103
25%       33.443520
50%       85.739326
75%      130.945883
max      165.160023
Name: coord.inicial.y, dtype: float64

In [100]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [101]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [102]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [103]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,2.0,6.118970,30.440638,74.778914,56.481372
1,9.0,79.339418,66.166123,34.965286,132.749944
2,4.0,76.313099,42.497743,136.840942,66.151231
3,7.0,19.200292,68.293527,82.221678,2.930160
4,8.0,67.553323,58.107109,23.868604,77.252642
...,...,...,...,...,...
245,12.0,19.932958,109.054707,133.996291,147.608530
246,24.0,105.542165,264.206188,155.288833,140.489047
247,22.0,202.741074,246.534351,99.563841,91.528214
248,NaN,10.976261,NaN,122.731724,NaN
249,NaN,NaN,NaN,NaN,NaN

In [104]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0         6.0,75.0
1        79.0,35.0
2       76.0,137.0
3        19.0,82.0
4        68.0,24.0
          ...
245     20.0,134.0
246    106.0,155.0
247    203.0,100.0
248     11.0,123.0
249        nan,nan
Length: 250, dtype: object

In [105]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [106]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [107]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0            6,75       30,56
1           79,35      66,133
2          76,137       42,66
3           19,82        68,3
4           68,24       58,77
..            ...         ...
245        20,134     109,148
246       106,155     264,140
247       203,100      247,92
248        11,123        None
249          None        None

[250 rows x 2 columns]

# Escribir tabla filtros

In [108]:
data_eventos = data_eventos[~data_eventos['partido'].isna()].reset_index(drop=True)

In [109]:
data_eventos['partido'] = 'Independiente'

In [110]:
data_eventos.tail()

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
244,2022/07/06,independiente,Independiente,17:20:45,19:32:44,perdida,NaN,02:02:44,02:02:44,0.0,...,0,0,0,0,0,NaN,207.734260,NaN,23.616497,NaN
245,2022/07/06,independiente,Independiente,17:20:45,19:32:44,pase,NaN,02:03:16,02:03:16,0.0,...,0,0,0,0,0,12.0,19.932958,109.054707,133.996291,147.608530
246,2022/07/06,independiente,Independiente,17:20:45,19:32:44,pase,NaN,02:03:21,02:03:21,0.0,...,0,0,0,0,0,24.0,105.542165,264.206188,155.288833,140.489047
247,2022/07/06,independiente,Independiente,17:20:45,19:32:44,remate pie,NaN,02:03:37,02:03:37,0.0,...,0,0,0,0,0,22.0,202.741074,246.534351,99.563841,91.528214
248,2022/07/06,independiente,Independiente,17:20:45,19:32:44,arquero,NaN,02:04:23,02:04:23,0.0,...,0,0,0,0,0,NaN,10.976261,NaN,122.731724,NaN

In [111]:
data_eventos.partido.value_counts()

Independiente    249
Name: partido, dtype: int64

In [112]:
data_eventos.to_csv("../Datos generados para la app/reserva02-22-fecha4_independiente-tabla_filtros2.csv",index=False)