In [332]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [333]:
data = pd.read_csv('../../datos etiquetas/Fecha 2 - Huracan/Huracan_primer tiempo.csv')
data

,Session Start Date,Event,Session Name,Session Start,Session End,Tag Description,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Dificultad,Zonas_final,Jugador2,Jugador,Zonas,Categoria,Optional Column
0,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,corto,NaN
1,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,medio,NaN
2,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,corto,NaN
3,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,medio,NaN
4,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,5.0,11.0,corto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1390,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,01:03:06,01:03:13,7.649,NaN,9,4,8.0,8.0,corto,NaN
1391,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,01:03:06,01:03:13,7.649,NaN,9,4,8.0,8.0,corto,NaN
1392,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,01:03:12,01:03:18,6.000,NaN,23,11,4.0,12.0,inteligente,NaN
1393,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,01:03:16,01:03:22,6.000,NaN,22,9,11.0,23.0,inteligente,NaN
1394,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Remate pie,NaN,01:03:20,01:03:26,6.000,NaN,20,Rival,7.0,22.0,Corta distancia,NaN

In [334]:
data.columns

Index(['Session Start Date', 'Event', 'Session Name', 'Session Start',
       'Session End', 'Tag Description', 'Tag Notes', 'Tag Start', 'Tag End',
       'Tag Duration (secs)', 'Dificultad', 'Zonas_final', 'Jugador2',
       'Jugador', 'Zonas', 'Categoria', 'Optional Column'],
      dtype='object')

In [335]:
data.columns = ['Session Start Date','partido','tiempo','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','Calificaciondelevento','coord final', 'Jugador 2', 'Jugador 1',
       'coord inicial', 'Subevento', 'Optional Column']

In [336]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1395 entries, 0 to 1394
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Session Start Date     1395 non-null   object
 1   partido                1395 non-null   object
 2   tiempo                 1395 non-null   object
 3   Session Start          1395 non-null   object
 4   Session End            1395 non-null   object
 5   Evento                 1395 non-null   object
 6   Tag Notes              0 non-null      float64
 7   Tag Start              1395 non-null   object
 8   Tag End                1395 non-null   object
 9   Tag Duration (secs)    1395 non-null   float64
 10  Calificaciondelevento  1 non-null      object
 11  coord final            1393 non-null   object
 12  Jugador 2              1319 non-null   object
 13  Jugador 1              1393 non-null   float64
 14  coord inicial          1393 non-null   float64
 15  Subevento              1393 non-null   object
 16  Optional Column        0 non-null      float64
dtypes: float64(5), object(12)
memory usage: 185.4+ KB

In [337]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [338]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [339]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 843 entries, 0 to 842
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Session Start Date     842 non-null    object
 1   partido                842 non-null    object
 2   tiempo                 842 non-null    object
 3   Session Start          842 non-null    object
 4   Session End            842 non-null    object
 5   Evento                 842 non-null    object
 6   Tag Notes              0 non-null      float64
 7   Tag Start              842 non-null    object
 8   Tag End                842 non-null    object
 9   Tag Duration (secs)    842 non-null    float64
 10  Calificaciondelevento  1 non-null      object
 11  coord final            840 non-null    object
 12  Jugador 2              766 non-null    object
 13  Jugador 1              840 non-null    float64
 14  coord inicial          840 non-null    float64
 15  Subevento              840 non-null    object
 16  Optional Column        0 non-null      float64
 17  segundos               842 non-null    float64
dtypes: float64(6), object(12)
memory usage: 118.7+ KB

In [340]:
data

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Calificaciondelevento,coord final,Jugador 2,Jugador 1,coord inicial,Subevento,Optional Column,segundos
0,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,corto,NaN,1045.0
1,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,medio,NaN,1045.0
2,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,corto,NaN,1045.0
3,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,medio,NaN,1045.0
4,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,5.0,11.0,corto,NaN,1045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,01:03:06,01:03:13,7.649,NaN,9,4,8.0,8.0,corto,NaN,3786.0
839,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,01:03:12,01:03:18,6.000,NaN,23,11,4.0,12.0,inteligente,NaN,3792.0
840,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Pase,NaN,01:03:16,01:03:22,6.000,NaN,22,9,11.0,23.0,inteligente,NaN,3796.0
841,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,Remate pie,NaN,01:03:20,01:03:26,6.000,NaN,20,Rival,7.0,22.0,Corta distancia,NaN,3800.0
842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [341]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [342]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [343]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [344]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                      cantidad
Jugador 1 Evento     Subevento
1.0       arquero    no salida aerea         1
                     remate atajable         2
                     salvada/atajada         1
          pase       corto                  75
                     largo                  25
...                                        ...
11.0      pase       inteligente             1
                     largo                  18
          perdida    duelo                   1
                     interceptado            1
          remate pie media distancia         1

[120 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [345]:
data_eventos = data.copy()
data_eventos.shape

(843, 18)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [346]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
data_eventos.loc[data_eventos['remate-Gol'] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol]
Index: []

In [347]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera]
Index: []

In [348]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco]
Index: []

[0 rows x 21 columns]

In [349]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 2,Jugador 1,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado
650,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,remate pie,NaN,00:48:22,00:48:28,6.0,...,Rival,9.0,21.0,remate bloqueado,NaN,2902.0,0,0,0,1
663,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,remate pie,NaN,00:52:19,00:52:25,6.0,...,NaN,9.0,17.0,remate bloqueado,NaN,3139.0,0,0,0,1

In [350]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza]
Index: []

[0 rows x 23 columns]

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [351]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                         cantidad
Evento Subevento
pase   bloqueado               16
       centro aereo             3
       centro bloqueado         1
       corto                  323
       inteligente             22
       largo                  110
       medio                  124
       s arquero mano          81
       s arquero pie           58

In [352]:
data[(data.Evento=='pase')]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Calificaciondelevento,coord final,Jugador 2,Jugador 1,coord inicial,Subevento,Optional Column,segundos
0,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,corto,NaN,1045.0
1,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,medio,NaN,1045.0
2,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,corto,NaN,1045.0
3,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,medio,NaN,1045.0
4,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,5.0,11.0,corto,NaN,1045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:06,01:03:13,7.649,NaN,9,8,8.0,8.0,corto,NaN,3786.0
837,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:06,01:03:13,7.649,NaN,9,4,2.0,8.0,corto,NaN,3786.0
838,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:06,01:03:13,7.649,NaN,9,4,8.0,8.0,corto,NaN,3786.0
839,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:12,01:03:18,6.000,NaN,23,11,4.0,12.0,inteligente,NaN,3792.0
840,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:16,01:03:22,6.000,NaN,22,9,11.0,23.0,inteligente,NaN,3796.0

In [353]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''

colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia]
Index: []

[0 rows x 24 columns]

In [354]:
data_eventos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 843 entries, 0 to 842
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Session Start Date     842 non-null    object
 1   partido                842 non-null    object
 2   tiempo                 842 non-null    object
 3   Session Start          842 non-null    object
 4   Session End            842 non-null    object
 5   Evento                 842 non-null    object
 6   Tag Notes              0 non-null      float64
 7   Tag Start              842 non-null    object
 8   Tag End                842 non-null    object
 9   Tag Duration (secs)    842 non-null    float64
 10  Calificaciondelevento  1 non-null      object
 11  coord final            840 non-null    object
 12  Jugador 2              766 non-null    object
 13  Jugador 1              840 non-null    float64
 14  coord inicial          840 non-null    float64
 15  Subevento              840 non-null    object
 16  Optional Column        0 non-null      float64
 17  segundos               842 non-null    float64
 18  remate-Gol             843 non-null    int64
 19  remate-Fuera           843 non-null    int64
 20  remate-Al-arco         843 non-null    int64
 21  remate-Interceptado    843 non-null    int64
 22  remate-Cabeza          843 non-null    int64
 23  pase-Asistencia        843 non-null    int64
dtypes: float64(6), int64(6), object(12)
memory usage: 158.2+ KB

In [355]:
#completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='centro aereo') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='bloqueado'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) | (data_eventos.loc[i+1,'Subevento'] == 'offside' ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado
0,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,...,corto,NaN,1045.0,0,0,0,0,0,0,1
1,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,...,medio,NaN,1045.0,0,0,0,0,0,0,1
2,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,...,corto,NaN,1045.0,0,0,0,0,0,0,1
3,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,...,medio,NaN,1045.0,0,0,0,0,0,0,1
4,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,...,corto,NaN,1045.0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:06,01:03:13,7.649,...,corto,NaN,3786.0,0,0,0,0,0,0,1
837,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:06,01:03:13,7.649,...,corto,NaN,3786.0,0,0,0,0,0,0,1
838,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:06,01:03:13,7.649,...,corto,NaN,3786.0,0,0,0,0,0,0,1
839,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:12,01:03:18,6.000,...,inteligente,NaN,3792.0,0,0,0,0,0,0,1
840,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:16,01:03:22,6.000,...,inteligente,NaN,3796.0,0,0,0,0,0,0,1

In [356]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

corto               323
medio               123
largo               110
s arquero pie        58
inteligente          22
centro bloqueado      1
Name: Subevento, dtype: int64

In [357]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado
89,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:22:36,00:22:42,6.0,...,NaN,1356.0,0,0,0,0,0,0,1,1
92,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:22:52,00:22:58,6.0,...,NaN,1372.0,0,0,0,0,0,0,1,1
228,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:32:21,00:32:27,6.0,...,NaN,1941.0,0,0,0,0,0,0,1,1
652,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:48:50,00:48:56,6.0,...,NaN,2930.0,0,0,0,0,0,0,1,1
802,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:00:32,01:00:38,6.0,...,NaN,3632.0,0,0,0,0,0,0,0,1
812,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:02:49,01:02:55,6.0,...,NaN,3769.0,0,0,0,0,0,0,1,1

In [358]:
#fuera
'''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

colname = 'pase-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera]
Index: []

[0 rows x 27 columns]

In [359]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente
86,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:21:58,00:22:04,6.000,...,0,0,0,0,0,0,1,0,0,1
97,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:23:30,00:23:36,6.000,...,0,0,0,0,0,0,1,0,0,1
192,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
194,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
196,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
198,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
200,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
202,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
204,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
206,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
208,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
210,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
212,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
214,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
216,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
218,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
220,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
222,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:31:09,00:31:17,7.916,...,0,0,0,0,0,0,1,0,0,1
662,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:52:15,00:52:21,6.000,...,0,0,0,0,0,0,1,0,0,1
786,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:56:00,00:56:06,6.000,...,0,0,0,0,0,0,1,0,0,1
839,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:12,01:03:18,6.000,...,0,0,0,0,0,0,1,0,0,1
840,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:16,01:03:22,6.000,...,0,0,0,0,0,0,1,0,0,1

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [360]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [361]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 29 columns]

In [362]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado
649,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:48:21,00:48:27,6.0,...,0,0,0,0,0,0,0,0,0,1
780,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:55:27,00:55:33,6.0,...,0,0,0,0,0,0,0,0,0,1

In [363]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado
84,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:21:26,00:21:32,6.0,...,0,0,0,0,0,0,0,0,0,1

In [364]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 32 columns]

In [365]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 33 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [366]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [367]:
dejar_index= []
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo'):
        dejar_index.append(i-1)
        dejar_index.append(i)
        dejar_index.append(i+1)
data_eventos.loc[dejar_index].head(100)

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera
73,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:19:27,00:19:33,6.0,...,0,0,0,0,0,0,0,0,0,0
74,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:20:02,00:20:08,6.0,...,0,0,0,0,0,0,0,0,0,0
75,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:20:20,00:20:26,6.0,...,0,0,0,0,0,0,0,0,0,0
106,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:27:35,00:27:41,6.0,...,0,0,0,0,0,0,0,0,0,0
107,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:28:01,00:28:07,6.0,...,0,0,0,0,0,0,0,0,0,0
108,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:28:02,00:28:08,6.0,...,0,0,0,0,0,0,0,0,0,0
108,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:28:02,00:28:08,6.0,...,0,0,0,0,0,0,0,0,0,0
109,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:28:52,00:28:58,6.0,...,0,0,0,0,0,0,0,0,0,0
110,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:29:43,00:29:49,6.0,...,0,0,0,0,0,0,0,0,0,0
112,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:29:51,00:29:57,6.0,...,0,1,0,0,0,0,0,0,0,0
113,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:29:55,00:30:01,6.0,...,0,0,0,0,0,0,0,0,0,0
114,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:30:00,00:30:06,6.0,...,0,0,0,0,0,0,0,0,0,0
489,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:37:03,00:37:09,6.0,...,0,0,0,0,0,0,0,0,0,0
490,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:37:53,00:37:59,6.0,...,0,0,0,0,0,0,0,0,0,0
491,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:38:30,00:38:36,6.0,...,0,0,0,0,0,0,0,0,0,0
656,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,despeje,NaN,00:50:49,00:50:55,6.0,...,0,0,0,0,0,0,0,0,0,0
657,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:50:51,00:50:57,6.0,...,0,0,0,0,0,0,0,0,0,0
658,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:50:56,00:51:02,6.0,...,0,1,0,0,0,0,0,0,0,0

In [368]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
74,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:20:02,00:20:08,6.0,...,0,0,0,0,0,0,0,0,0,1
109,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:28:52,00:28:58,6.0,...,0,0,0,0,0,0,0,0,0,1
490,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:37:53,00:37:59,6.0,...,0,0,0,0,0,0,0,0,0,1

In [369]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
107,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:28:01,00:28:07,6.0,...,0,0,0,0,0,0,0,0,0,1
657,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:50:51,00:50:57,6.0,...,0,0,0,0,0,0,0,0,0,1

In [370]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 39 columns]

In [371]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada]
Index: []

[0 rows x 41 columns]

In [372]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 43 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [373]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [374]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida
106,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:27:35,00:27:41,6.0,...,0,0,0,0,0,0,0,0,0,1
489,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:37:03,00:37:09,6.0,...,0,0,0,0,0,0,0,0,0,1
635,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:45:38,00:45:44,6.0,...,0,0,0,0,0,0,0,0,0,1
636,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:46:01,00:46:07,6.0,...,0,0,0,0,0,0,0,0,0,1
791,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:58:10,00:58:16,6.0,...,0,0,0,0,0,0,0,0,0,1

In [375]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida
33,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:17:35,00:17:41,6.0,...,0,0,0,0,0,0,0,0,0,1
51,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:18:00,00:18:06,6.0,...,0,0,0,0,0,0,0,0,0,1
94,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:22:56,00:23:02,6.0,...,0,0,0,0,0,0,0,0,0,1
100,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:24:35,00:24:41,6.0,...,0,0,0,0,0,0,0,0,0,1
236,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:33:57,00:34:03,6.0,...,0,0,0,0,0,0,0,0,0,1
241,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:34:52,00:34:58,6.0,...,0,0,0,0,0,0,0,0,0,1
491,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:38:30,00:38:36,6.0,...,0,0,0,0,0,0,0,0,0,1
493,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:38:54,00:39:00,6.0,...,0,0,0,0,0,0,0,0,0,1
495,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:39:55,00:40:01,6.0,...,0,0,0,0,0,0,0,0,0,1
669,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:54:46,00:54:52,6.0,...,0,0,0,0,0,0,0,0,0,1

In [376]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 46 columns]

In [377]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 47 columns]

In [378]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside
73,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:19:27,00:19:33,6.0,...,0,0,0,0,0,0,0,0,0,1
500,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:42:16,00:42:22,6.0,...,0,0,0,0,0,0,0,0,0,1
634,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:45:18,00:45:24,6.0,...,0,0,0,0,0,0,0,0,0,1
787,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:56:03,00:56:09,6.0,...,0,0,0,0,0,0,0,0,0,1

In [379]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla
636,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,falta,NaN,00:46:01,00:46:07,6.0,...,0,0,0,0,1,0,0,0,0,1

In [380]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja]
Index: []

[0 rows x 50 columns]

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [381]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [382]:
#robo/gambeta en contra recuperada

colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo
224,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:31:30,00:31:36,6.0,...,0,0,0,0,0,0,0,0,0,1
501,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:43:41,00:43:47,6.0,...,0,0,0,0,0,0,0,0,0,1
660,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:52:11,00:52:17,6.0,...,0,0,0,0,0,0,0,0,0,1
796,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:59:44,00:59:50,6.0,...,0,0,0,0,0,0,0,0,0,1

In [383]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada
110,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:29:43,00:29:49,6.0,...,0,0,0,0,0,0,0,0,0,1
230,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:32:59,00:33:05,6.0,...,0,0,0,0,0,0,0,0,0,1
666,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:53:33,00:53:39,6.0,...,0,0,0,0,0,0,0,0,0,1
811,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,01:02:47,01:02:53,6.0,...,0,0,0,0,0,0,0,0,0,1

In [384]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo
53,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:19:11,00:19:17,6.0,...,0,0,0,0,0,0,0,0,0,1
75,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:20:20,00:20:26,6.0,...,0,0,0,0,0,0,0,0,0,1
78,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:21:06,00:21:12,6.0,...,0,0,0,0,0,0,0,0,0,1
613,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:44:33,00:44:39,6.0,...,0,0,0,0,0,0,0,0,0,1
781,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:55:36,00:55:42,6.0,...,0,0,0,0,0,0,0,0,0,1
814,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,01:02:56,01:03:02,6.0,...,0,0,0,0,0,0,0,0,0,1

In [385]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo
91,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:22:51,00:22:57,6.0,...,0,0,0,0,0,0,0,0,0,1
799,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,01:00:12,01:00:18,6.0,...,0,0,0,0,0,0,0,0,0,1

In [386]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in str(data_eventos.loc[i,'Subevento'])):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo
783,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:55:47,00:55:53,6.0,...,0,0,0,0,0,0,0,0,0,1

In [387]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if (data_eventos.loc[i+1,'Evento'] == 'recuperacion') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo]
Index: []

[0 rows x 56 columns]

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [388]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [389]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
498,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:42:11,00:42:17,6.0,...,0,0,0,0,0,0,0,0,0,1
615,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:45:05,00:45:11,6.0,...,0,0,0,0,0,0,0,0,0,1
639,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:48:07,00:48:13,6.0,...,0,0,0,0,0,0,0,0,0,1

In [390]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 60 columns]

In [391]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
52,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:18:41,00:18:47,6.0,...,0,0,0,0,0,0,0,0,0,1
95,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:23:23,00:23:29,6.0,...,0,0,0,0,0,0,0,0,0,1
237,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:34:32,00:34:38,6.0,...,0,0,0,0,0,0,0,0,0,1
242,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:35:50,00:35:56,6.0,...,0,0,0,0,0,0,0,0,0,1
494,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:39:51,00:39:57,6.0,...,0,0,0,0,0,0,0,0,0,1
670,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pelota parada,NaN,00:55:11,00:55:17,6.0,...,0,0,0,0,0,0,0,0,0,1

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [392]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [393]:
#gambeta a favor

colname = 'perdida-Gambeta-favor'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor
113,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:29:55,00:30:01,6.0,...,0,0,0,0,0,0,0,0,0,1

In [394]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='robo'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo
105,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:27:23,00:27:29,6.0,...,0,0,0,0,0,0,0,0,0,1

In [395]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion
85,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:21:26,00:21:32,6.0,...,0,0,0,0,0,0,0,0,0,1
90,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:22:37,00:22:43,6.0,...,0,0,0,0,0,0,0,0,0,1
93,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:22:53,00:22:59,6.0,...,0,0,0,0,0,0,0,0,0,1
102,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:25:44,00:25:50,6.0,...,0,0,0,0,0,0,0,0,0,1
229,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:32:23,00:32:29,6.0,...,0,0,0,0,0,0,0,0,0,1
653,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:48:53,00:48:59,6.0,...,0,0,0,0,0,0,0,0,0,1
655,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:50:43,00:50:49,6.0,...,0,0,0,0,0,0,0,0,0,1
665,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:52:53,00:52:59,6.0,...,0,0,0,0,0,0,0,0,0,1
803,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,01:00:32,01:00:38,6.0,...,0,0,0,0,0,0,0,0,0,1
813,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,01:02:50,01:02:56,6.0,...,0,0,0,0,0,0,0,0,0,1

In [396]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico
488,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,perdida,NaN,00:36:54,00:37:00,6.0,...,0,0,0,0,0,0,0,0,0,1

In [397]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
            data_eventos.loc[i-1,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera
75,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:20:20,00:20:26,6.0,...,0,0,0,0,0,0,0,0,0,1
107,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,duelo,NaN,00:28:01,00:28:07,6.0,...,0,0,0,0,0,0,0,0,0,1
613,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:44:33,00:44:39,6.0,...,0,0,0,0,0,0,0,0,0,1
781,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,recuperacion,NaN,00:55:36,00:55:42,6.0,...,0,0,0,0,0,0,0,0,0,1

In [398]:
#situacion rival

colname = 'perdida-Situacion-rival'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='situacion rival'):
        if (data_eventos.loc[i,'Subevento']=='directa'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Situacion-rival
103,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,situacion rival,NaN,00:26:42,00:26:48,6.0,...,0,0,0,0,0,0,0,0,0,1

In [399]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='atajada'):
            data_eventos.loc[i-1,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada]
Index: []

[0 rows x 69 columns]

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [400]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                       cantidad
Evento          Subevento
arquero         no salida aerea               1
                remate atajable               2
                salvada/atajada               1
despeje         despeje                       3
                despeje bloqueado             2
duelo           aereo                         3
                disputa suelo                 2
                gambeta a favor               1
falta           hecha                         5
                offside                       4
                recibida                     10
pase            bloqueado                    16
                centro aereo                  3
                centro bloqueado              1
                corto                       323
                inteligente                  22
                largo                       110
                medio                       124
                s arquero mano               81
                s arquero pie                58
pelota parada   lateral corto                 1
                lateral largo                 2
                penal                         1
                saque de meta                 3
                tiro libre                    7
perdida         balon afuera fondo            1
                balon afuera lateral          3
                duelo                         9
                error tecnico                 1
                intercepcion aereo            1
                interceptado                  9
                robo                          1
recuperacion    duelo                         5
                encontrada                    4
                intercepcion                  6
                intercepcion aereo            2
                intercepcion anticipo         1
                robo                          4
remate pie      corta distancia               2
                media distancia               1
                remate bloqueado              2
situacion rival directa                       1
tarjeta         amarilla                      1

In [401]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable]
Index: []

[0 rows x 71 columns]

In [402]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in str(data_eventos.loc[i,'Subevento'])) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            if ('remate' in str(data_eventos.loc[i-1,'Evento'])):
                data_eventos.loc[i-1,colname] = 1
            elif ('remate' in str(data_eventos.loc[i-2,'Evento'])):
                data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Situacion-rival,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada
243,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,remate pie,NaN,00:35:51,00:35:57,6.0,...,0,0,0,0,0,0,0,0,0,1
244,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,arquero,NaN,00:36:13,00:36:19,6.0,...,0,0,0,0,0,0,0,0,0,1

In [403]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [404]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 73 columns]

In [405]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 74 columns]

In [406]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 75 columns]

In [407]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano]
Index: []

[0 rows x 76 columns]

In [408]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie]
Index: []

[0 rows x 77 columns]

In [409]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Calificaciondelevento, coord final, Jugador 2, Jugador 1, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 78 columns]

In [410]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [411]:
data_eventos.iloc[:,:20]

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),Calificaciondelevento,coord.final,Jugador.2,Jugador.1,coord.inicial,Subevento,Optional.Column,segundos,remate-Gol,remate-Fuera
0,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,corto,NaN,1045.0,0,0
1,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,11.0,medio,NaN,1045.0,0,0
2,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,corto,NaN,1045.0,0,0
3,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,9.0,8.0,medio,NaN,1045.0,0,0
4,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,00:17:25,00:17:33,8.000,NaN,8,5,5.0,11.0,corto,NaN,1045.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:06,01:03:13,7.649,NaN,9,4,8.0,8.0,corto,NaN,3786.0,0,0
839,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:12,01:03:18,6.000,NaN,23,11,4.0,12.0,inteligente,NaN,3792.0,0,0
840,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,pase,NaN,01:03:16,01:03:22,6.000,NaN,22,9,11.0,23.0,inteligente,NaN,3796.0,0,0
841,2022/03/05,Huracan,primer tiempo,14:32:28,16:49:21,remate pie,NaN,01:03:20,01:03:26,6.000,NaN,20,Rival,7.0,22.0,corta distancia,NaN,3800.0,0,0
842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [412]:
data_eventos['coord.inicial'].value_counts()

5.0     155
3.0     140
9.0      91
8.0      90
11.0     68
14.0     64
17.0     42
6.0      38
15.0     30
7.0      18
13.0     17
24.0     17
10.0     15
2.0      13
4.0       9
18.0      7
12.0      7
1.0       6
16.0      5
21.0      4
23.0      1
20.0      1
19.0      1
22.0      1
Name: coord.inicial, dtype: int64

In [413]:
data_eventos['coord.final'].value_counts()

5         128
6         118
14         82
12         82
Volver     74
17         68
11         55
13         50
3          45
9          32
8          24
22         18
24         17
10         14
16          9
21          5
20          4
2           4
15          3
18          3
23          2
7           2
19          1
Name: coord.final, dtype: int64

In [414]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [415]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [416]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [417]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,8.0,108.0,66.0,82.0,81.0
1,8.0,108.0,66.0,82.0,81.0
2,8.0,66.0,66.0,81.0,81.0
3,8.0,66.0,66.0,81.0,81.0
4,8.0,108.0,66.0,82.0,81.0
...,...,...,...,...,...
838,9.0,66.0,65.0,81.0,141.0
839,23.0,105.0,250.0,138.0,119.0
840,22.0,250.0,260.0,119.0,81.0
841,20.0,260.0,250.0,81.0,45.0
842,NaN,NaN,NaN,NaN,NaN

In [418]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    840.000000
mean      76.467857
std       66.995963
min       12.000000
25%       21.000000
50%       65.000000
75%      108.000000
max      260.000000
Name: coord.inicial.x, dtype: float64

In [419]:
# aÃ±adirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    840.000000
mean      76.572908
std       67.325860
min       -7.525649
25%       22.332333
50%       55.365849
75%      118.990386
max      269.870102
Name: coord.inicial.x, dtype: float64

In [420]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [421]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    840.000000
mean      96.846429
std       33.807475
min       18.000000
25%       81.000000
50%       82.000000
75%      117.000000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [422]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    840.000000
mean      96.643899
std       35.480696
min        2.004786
25%       74.324610
50%       94.825447
75%      124.227254
max      166.843578
Name: coord.inicial.y, dtype: float64

In [423]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [424]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [425]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [426]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,8.0,100.472415,53.660912,68.042128,72.170061
1,8.0,103.753228,67.882328,75.127161,93.873726
2,8.0,51.559598,76.988068,78.439998,82.288766
3,8.0,49.855822,80.659045,66.149659,100.546433
4,8.0,115.378423,46.738479,91.083660,76.987687
...,...,...,...,...,...
838,9.0,72.470365,47.704182,84.998517,124.700768
839,23.0,94.795753,253.274769,134.937330,121.151037
840,22.0,263.764470,266.776300,133.168344,71.145243
841,20.0,241.854263,242.465540,94.954030,31.626499
842,NaN,NaN,NaN,NaN,NaN

In [427]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0       100.0,68.0
1       104.0,75.0
2        52.0,78.0
3        50.0,66.0
4       115.0,91.0
          ...
838      72.0,85.0
839     95.0,135.0
840    264.0,133.0
841     242.0,95.0
842        nan,nan
Length: 843, dtype: object

In [428]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [429]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [430]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0          100,68       54,72
1          104,75       68,94
2           52,78       77,82
3           50,66      81,101
4          115,91       47,77
..            ...         ...
838         72,85      48,125
839        95,135     253,121
840       264,133      267,71
841        242,95      242,32
842          None        None

[843 rows x 2 columns]

# Escribir tabla filtros

In [431]:
data_eventos = data_eventos[~data_eventos['partido'].isna()].reset_index(drop=True)

In [432]:
data_eventos.to_csv("../Datos generados para la app/reserva22-fecha2-huracan-tabla_filtros.csv",index=False)

In [ ]:
data_eventos[[col for col in data_eventos.columns if 'perdida' in col]].sum()

In [ ]:
data_eventos[data_eventos['Jugador.1']==3][['Jugador.1','coord.inicial','coord.final','Subevento']+[col for col in data_eventos.columns if 'perdida' in col]]

# Agregar

ARQUERO
- que siempre que hay una atajada haya un remate antes para saber desde donde proviene
- que el remate antes de gol o atajada tenga coord inicio y final
- agregar rebote
- ver como poner los mano a mano
- INTERCEPCIONES (poner antes de donde proviene del rival)

In [ ]:
data_eventos.info()

In [ ]:
data_eventos.iloc[:,12:].apply(lambda x: x.sum(), axis='rows')