In [328]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import glob
import os
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [329]:
# merging the files
files_joined = os.path.join('..\\..\\datos etiquetas\\Tem2-2022\\Fecha 2 - Aldosivi', "*.csv")

# Return a list of all joined files
list_files = glob.glob(files_joined)

#print("** Merging multiple csv files into a single pandas dataframe **")
# Merge files by joining all files
data = pd.concat(map(pd.read_csv, list_files), ignore_index=True)

In [330]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   235 non-null    object
 1   Event                235 non-null    object
 2   Session Name         235 non-null    object
 3   Session Start        235 non-null    object
 4   Session End          235 non-null    object
 5   Tag Description      235 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            235 non-null    object
 8   Tag End              235 non-null    object
 9   Tag Duration (secs)  235 non-null    float64
 10  Zonas                235 non-null    int64
 11  Categoria            235 non-null    object
 12  Jugador2             65 non-null     object
 13  Jugador              235 non-null    int64
 14  Zonas_final          235 non-null    object
 15  Optional Column      0 non-null      float64
dtypes: float64(3), int64(2), object(11)
memory usage: 29.5+ KB

In [331]:
data.columns = ['Session Start Date','partido','tiempo','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Optional Column']

# data.columns = ['Session Start Date','tiempo','partido','Session Start',
#        'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
#        'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Dificultad','Calificacion','Optional Column']

In [332]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [333]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [334]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   235 non-null    object
 1   partido              235 non-null    object
 2   tiempo               235 non-null    object
 3   Session Start        235 non-null    object
 4   Session End          235 non-null    object
 5   Evento               235 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            235 non-null    object
 8   Tag End              235 non-null    object
 9   Tag Duration (secs)  235 non-null    float64
 10  coord inicial        235 non-null    float64
 11  Subevento            235 non-null    object
 12  Jugador 2            65 non-null     object
 13  Jugador 1            235 non-null    float64
 14  coord final          235 non-null    object
 15  Optional Column      0 non-null      float64
 16  segundos             235 non-null    float64
dtypes: float64(6), object(11)
memory usage: 31.5+ KB

In [335]:
data

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Optional Column,segundos
0,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Perdida,NaN,00:12:40,00:12:40,0.0,9.0,Balon afuera lateral,3,6.0,10,NaN,760.0
1,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Recuperacion,NaN,00:13:02,00:13:02,0.0,10.0,intercepcion anticipo,NaN,3.0,Volver,NaN,782.0
2,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Perdida,NaN,00:13:17,00:13:17,0.0,9.0,Interceptado,4,6.0,9,NaN,797.0
3,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Duelo,NaN,00:13:20,00:13:20,0.0,6.0,Disputa suelo,NaN,6.0,Volver,NaN,800.0
4,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Recuperacion,NaN,00:13:21,00:13:21,0.0,6.0,Duelo,NaN,6.0,Volver,NaN,801.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Pelota parada,NaN,02:03:39,02:03:39,0.0,16.0,Tiro libre,Rival,3.0,17,NaN,7419.0
232,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Perdida,NaN,02:03:40,02:03:40,0.0,16.0,Interceptado,Rival,3.0,17,NaN,7420.0
233,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Pelota parada,NaN,02:04:29,02:04:29,0.0,14.0,Tiro libre,Rival,1.0,21,NaN,7469.0
234,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,Perdida,NaN,02:04:31,02:04:31,0.0,14.0,Interceptado,Rival,1.0,21,NaN,7471.0
235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [336]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [337]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [338]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        19
              disputa suelo                11
              gambeta a favor              10
pelota parada lateral corto                13
              lateral largo                10
              tiro de esquina               6
              tiro libre                   16
perdida       atajada                       7
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        13
              error tecnico                23
              intercepcion aereo            7
              interceptado                 18
              robo                          4
recuperacion  duelo                         9
              encontrada                   11
              intercepcion                  8
              intercepcion aereo            8
              intercepcion anticipo         7
              robo                         23

In [339]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                            cantidad
Jugador 1 Evento        Subevento
1.0       pelota parada tiro libre                 2
          perdida       intercepcion aereo         1
                        interceptado               1
2.0       duelo         aereo                      2
          pelota parada tiro libre                 3
...                                              ...
22.0      duelo         aereo                      1
          perdida       atajada                    2
                        duelo                      2
          recuperacion  intercepcion               1
                        robo                       1

[123 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [340]:
data_eventos = data.copy()
data_eventos.shape

(236, 17)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [341]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
data_eventos.loc[data_eventos['remate-Gol'] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol]
Index: []

In [342]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera]
Index: []

In [343]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco]
Index: []

In [344]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado]
Index: []

[0 rows x 21 columns]

In [345]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza]
Index: []

[0 rows x 22 columns]

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [346]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

Empty DataFrame
Columns: [cantidad]
Index: []

In [347]:
data[(data.Evento=='pase')]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos]
Index: []

In [348]:
data_eventos.head()

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 2,Jugador 1,coord final,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
0,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:12:40,00:12:40,0.0,...,3,6.0,10,NaN,760.0,0,0,0,0,0
1,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:02,00:13:02,0.0,...,NaN,3.0,Volver,NaN,782.0,0,0,0,0,0
2,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:13:17,00:13:17,0.0,...,4,6.0,9,NaN,797.0,0,0,0,0,0
3,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:13:20,00:13:20,0.0,...,NaN,6.0,Volver,NaN,800.0,0,0,0,0,0
4,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:21,00:13:21,0.0,...,NaN,6.0,Volver,NaN,801.0,0,0,0,0,0

In [349]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''
colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia]
Index: []

[0 rows x 23 columns]

In [350]:
##completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') & (data_eventos.loc[i,'Jugador 2'] != 'Rival')):
        if ((data_eventos.loc[i+1,'Evento'] != 'perdida') ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado]
Index: []

[0 rows x 24 columns]

In [351]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

Series([], Name: Subevento, dtype: int64)

In [352]:
#Incompleto
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Incompleto'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') ):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') ):
            #if ((data_eventos.loc[i,'pase-Completado'] != 1)):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto]
Index: []

[0 rows x 25 columns]

In [353]:
# #fuera
# '''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

# colname = 'pase-Fuera'
# data_eventos[colname] = 0
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
#         if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
#             if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
#                 data_eventos.loc[i,colname] = 1
            
# data_eventos.loc[data_eventos[colname] == 1]

In [354]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente]
Index: []

[0 rows x 26 columns]

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [355]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        19
              disputa suelo                11
              gambeta a favor              10
pelota parada lateral corto                13
              lateral largo                10
              tiro de esquina               6
              tiro libre                   16
perdida       atajada                       7
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        13
              error tecnico                23
              intercepcion aereo            7
              interceptado                 18
              robo                          4
recuperacion  duelo                         9
              encontrada                   11
              intercepcion                  8
              intercepcion aereo            8
              intercepcion anticipo         7
              robo                         23

In [356]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 27 columns]

In [357]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado]
Index: []

[0 rows x 28 columns]

In [358]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado]
Index: []

[0 rows x 29 columns]

In [359]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 30 columns]

In [360]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 31 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [361]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        19
              disputa suelo                11
              gambeta a favor              10
pelota parada lateral corto                13
              lateral largo                10
              tiro de esquina               6
              tiro libre                   16
perdida       atajada                       7
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        13
              error tecnico                23
              intercepcion aereo            7
              interceptado                 18
              robo                          4
recuperacion  duelo                         9
              encontrada                   11
              intercepcion                  8
              intercepcion aereo            8
              intercepcion anticipo         7
              robo                         23

In [362]:
# dejar_index= []
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='duelo'):
#         dejar_index.append(i-1)
#         dejar_index.append(i)
#         dejar_index.append(i+1)
# data_eventos.loc[dejar_index].head(10)

In [363]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1


data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
7,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:14:50,00:14:50,0.0,...,0,0,0,0,0,0,0,0,0,1
8,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:14:52,00:14:52,0.0,...,0,0,0,0,0,0,0,0,0,1
48,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:29:34,00:29:34,0.0,...,0,0,0,0,0,0,0,0,0,1
74,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:38:53,00:38:53,0.0,...,0,0,0,0,0,0,0,0,0,1
75,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:38:56,00:38:56,0.0,...,0,0,0,0,0,0,0,0,0,1
88,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:42:09,00:42:09,0.0,...,0,0,0,0,0,0,0,0,0,1
89,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:42:11,00:42:11,0.0,...,0,0,0,0,0,0,0,0,0,1
91,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:43:01,00:43:01,0.0,...,0,0,0,0,0,0,0,0,0,1
98,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:45:35,00:45:35,0.0,...,0,0,0,0,0,0,0,0,0,1
122,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:16:53,01:16:53,0.0,...,0,0,0,0,0,0,0,0,0,1
127,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:18:43,01:18:43,0.0,...,0,0,0,0,0,0,0,0,0,1
140,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:23:03,01:23:03,0.0,...,0,0,0,0,0,0,0,0,0,1
169,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:37:32,01:37:32,0.0,...,0,0,0,0,0,0,0,0,0,1
173,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:38:50,01:38:50,0.0,...,0,0,0,0,0,0,0,0,0,1
188,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:45:33,01:45:33,0.0,...,0,0,0,0,0,0,0,0,0,1
216,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:57:43,01:57:43,0.0,...,0,0,0,0,0,0,0,0,0,1

In [364]:
data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
103,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:48:37,00:48:37,0.0,...,0,0,0,0,0,0,0,0,1,0
138,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:23:01,01:23:01,0.0,...,0,0,0,0,0,0,0,0,1,0
176,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:39:07,01:39:07,0.0,...,0,0,0,0,0,0,0,0,1,0

In [365]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
9,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:14:57,00:14:57,0.0,...,0,0,0,0,0,0,0,0,1,0
132,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:20:42,01:20:42,0.0,...,0,0,0,0,0,0,0,0,1,0

In [366]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
3,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:13:20,00:13:20,0.0,...,0,0,0,0,0,0,0,0,0,1
17,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:17:44,00:17:44,0.0,...,0,0,0,0,0,0,0,0,0,1
23,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:18:46,00:18:46,0.0,...,0,0,0,0,0,0,0,0,0,1
35,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:24:12,00:24:12,0.0,...,0,0,0,0,0,0,0,0,0,1
38,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:25:07,00:25:07,0.0,...,0,0,0,0,0,0,0,0,0,1
62,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:34:47,00:34:47,0.0,...,0,0,0,0,0,0,0,0,0,1
85,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:40:38,00:40:38,0.0,...,0,0,0,0,0,0,0,0,0,1
119,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:16:25,01:16:25,0.0,...,0,0,0,0,0,0,0,0,0,1
160,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:35:11,01:35:11,0.0,...,0,0,0,0,0,0,0,0,0,1

In [367]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 37 columns]

In [368]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 37 columns]

In [369]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada
81,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:39:44,00:39:44,0.0,...,0,0,0,0,0,0,0,0,1,0

In [370]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada
31,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:22:41,00:22:41,0.0,...,0,0,0,0,0,0,0,0,0,1
44,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:28:25,00:28:25,0.0,...,0,0,0,0,0,0,0,0,0,1
50,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:30:38,00:30:38,0.0,...,0,0,0,0,0,0,0,0,0,1
55,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:31:22,00:31:22,0.0,...,0,0,0,0,0,0,0,0,0,1
93,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:43:10,00:43:10,0.0,...,0,0,0,0,0,0,0,0,0,1
152,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:32:36,01:32:36,0.0,...,0,0,0,0,0,0,0,0,0,1
171,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:37:41,01:37:41,0.0,...,0,0,0,0,0,0,0,0,0,1
187,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:44:34,01:44:34,0.0,...,0,0,0,0,0,0,0,0,0,1
202,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,01:50:02,01:50:02,0.0,...,0,0,0,0,0,0,0,0,0,1

In [371]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 41 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [372]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        19
              disputa suelo                11
              gambeta a favor              10
pelota parada lateral corto                13
              lateral largo                10
              tiro de esquina               6
              tiro libre                   16
perdida       atajada                       7
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        13
              error tecnico                23
              intercepcion aereo            7
              interceptado                 18
              robo                          4
recuperacion  duelo                         9
              encontrada                   11
              intercepcion                  8
              intercepcion aereo            8
              intercepcion anticipo         7
              robo                         23

In [373]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida]
Index: []

[0 rows x 42 columns]

In [374]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida]
Index: []

[0 rows x 43 columns]

In [375]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 44 columns]

In [376]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 45 columns]

In [377]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside]
Index: []

[0 rows x 46 columns]

In [378]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla]
Index: []

[0 rows x 47 columns]

In [379]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja]
Index: []

[0 rows x 48 columns]

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [380]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        19
              disputa suelo                11
              gambeta a favor              10
pelota parada lateral corto                13
              lateral largo                10
              tiro de esquina               6
              tiro libre                   16
perdida       atajada                       7
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        13
              error tecnico                23
              intercepcion aereo            7
              interceptado                 18
              robo                          4
recuperacion  duelo                         9
              encontrada                   11
              intercepcion                  8
              intercepcion aereo            8
              intercepcion anticipo         7
              robo                         23

In [381]:
colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo
11,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:15:12,00:15:12,0.0,...,0,0,0,0,0,0,0,0,0,1
18,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:17:45,00:17:45,0.0,...,0,0,0,0,0,0,0,0,0,1
24,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:18:47,00:18:47,0.0,...,0,0,0,0,0,0,0,0,0,1
36,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:24:13,00:24:13,0.0,...,0,0,0,0,0,0,0,0,0,1
39,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:25:08,00:25:08,0.0,...,0,0,0,0,0,0,0,0,0,1
46,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:28:40,00:28:40,0.0,...,0,0,0,0,0,0,0,0,0,1
49,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:30:19,00:30:19,0.0,...,0,0,0,0,0,0,0,0,0,1
52,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:30:50,00:30:50,0.0,...,0,0,0,0,0,0,0,0,0,1
57,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:32:16,00:32:16,0.0,...,0,0,0,0,0,0,0,0,0,1
63,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:34:48,00:34:48,0.0,...,0,0,0,0,0,0,0,0,0,1
86,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:40:39,00:40:39,0.0,...,0,0,0,0,0,0,0,0,0,1
108,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:52:23,00:52:23,0.0,...,0,0,0,0,0,0,0,0,0,1
120,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:16:28,01:16:28,0.0,...,0,0,0,0,0,0,0,0,0,1
161,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:35:12,01:35:12,0.0,...,0,0,0,0,0,0,0,0,0,1
164,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:36:05,01:36:05,0.0,...,0,0,0,0,0,0,0,0,0,1
178,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:39:17,01:39:17,0.0,...,0,0,0,0,0,0,0,0,0,1
180,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:42:06,01:42:06,0.0,...,0,0,0,0,0,0,0,0,0,1
184,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:43:35,01:43:35,0.0,...,0,0,0,0,0,0,0,0,0,1
193,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:47:50,01:47:50,0.0,...,0,0,0,0,0,0,0,0,0,1
204,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:50:22,01:50:22,0.0,...,0,0,0,0,0,0,0,0,0,1
208,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:51:44,01:51:44,0.0,...,0,0,0,0,0,0,0,0,0,1
211,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:52:20,01:52:20,0.0,...,0,0,0,0,0,0,0,0,0,1
224,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,02:00:53,02:00:53,0.0,...,0,0,0,0,0,0,0,0,0,1

In [382]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada
27,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:21:22,00:21:22,0.0,...,0,0,0,0,0,0,0,0,0,1
54,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:31:16,00:31:16,0.0,...,0,0,0,0,0,0,0,0,0,1
65,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:35:26,00:35:26,0.0,...,0,0,0,0,0,0,0,0,0,1
95,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:43:40,00:43:40,0.0,...,0,0,0,0,0,0,0,0,0,1
105,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:50:57,00:50:57,0.0,...,0,0,0,0,0,0,0,0,0,1
157,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:34:17,01:34:17,0.0,...,0,0,0,0,0,0,0,0,0,1
163,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:35:34,01:35:34,0.0,...,0,0,0,0,0,0,0,0,0,1
167,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:37:02,01:37:02,0.0,...,0,0,0,0,0,0,0,0,0,1
175,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:38:55,01:38:55,0.0,...,0,0,0,0,0,0,0,0,0,1
191,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:47:31,01:47:31,0.0,...,0,0,0,0,0,0,0,0,0,1
222,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:59:57,01:59:57,0.0,...,0,0,0,0,0,0,0,0,0,1

In [383]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo
92,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:43:07,00:43:07,0.0,...,0,0,0,0,0,0,0,0,0,1
116,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:57:32,00:57:32,0.0,...,0,0,0,0,0,0,0,0,0,1
134,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:20:47,01:20:47,0.0,...,0,0,0,0,0,0,0,0,0,1
144,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:23:47,01:23:47,0.0,...,0,0,0,0,0,0,0,0,0,1
186,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:44:25,01:44:25,0.0,...,0,0,0,0,0,0,0,0,0,1
201,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:49:58,01:49:58,0.0,...,0,0,0,0,0,0,0,0,0,1
206,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:51:21,01:51:21,0.0,...,0,0,0,0,0,0,0,0,0,1
227,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,02:02:21,02:02:21,0.0,...,0,0,0,0,0,0,0,0,0,1

In [384]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo
15,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:17:09,00:17:09,0.0,...,0,0,0,0,0,0,0,0,0,1
67,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:35:51,00:35:51,0.0,...,0,0,0,0,0,0,0,0,0,1
79,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:39:21,00:39:21,0.0,...,0,0,0,0,0,0,0,0,0,1
123,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:16:54,01:16:54,0.0,...,0,0,0,0,0,0,0,0,0,1
128,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:18:43,01:18:43,0.0,...,0,0,0,0,0,0,0,0,0,1
141,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:23:03,01:23:03,0.0,...,0,0,0,0,0,0,0,0,0,1
170,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:37:33,01:37:33,0.0,...,0,0,0,0,0,0,0,0,0,1
220,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:59:35,01:59:35,0.0,...,0,0,0,0,0,0,0,0,0,1

In [385]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo
1,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:02,00:13:02,0.0,...,0,0,0,0,0,0,0,0,0,1
25,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:20:59,00:20:59,0.0,...,0,0,0,0,0,0,0,0,0,1
33,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:23:07,00:23:07,0.0,...,0,0,0,0,0,0,0,0,0,1
71,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:38:07,00:38:07,0.0,...,0,0,0,0,0,0,0,0,0,1
100,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:47:13,00:47:13,0.0,...,0,0,0,0,0,0,0,0,0,1
113,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:56:52,00:56:52,0.0,...,0,0,0,0,0,0,0,0,0,1
165,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:36:48,01:36:48,0.0,...,0,0,0,0,0,0,0,0,0,1

In [386]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
    if (data_eventos.loc[i,'Evento'] == 'recuperacion') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo
4,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:21,00:13:21,0.0,...,0,0,0,0,0,0,0,0,0,1
20,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:18:03,00:18:03,0.0,...,0,0,0,0,0,0,0,0,0,1
41,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:25:31,00:25:31,0.0,...,0,0,0,0,0,0,0,0,0,1
76,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:38:56,00:38:56,0.0,...,0,0,0,0,0,0,0,0,0,1
136,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:22:33,01:22:33,0.0,...,0,0,0,0,0,0,0,0,0,1
149,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:31:06,01:31:06,0.0,...,0,0,0,0,0,0,0,0,0,1
195,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:48:31,01:48:31,0.0,...,0,0,0,0,0,0,0,0,0,1
218,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,01:58:18,01:58:18,0.0,...,0,0,0,0,0,0,0,0,0,1
230,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,02:03:06,02:03:06,0.0,...,0,0,0,0,0,0,0,0,0,1

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [387]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        19
              disputa suelo                11
              gambeta a favor              10
pelota parada lateral corto                13
              lateral largo                10
              tiro de esquina               6
              tiro libre                   16
perdida       atajada                       7
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        13
              error tecnico                23
              intercepcion aereo            7
              interceptado                 18
              robo                          4
recuperacion  duelo                         9
              encontrada                   11
              intercepcion                  8
              intercepcion aereo            8
              intercepcion anticipo         7
              robo                         23

In [388]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
131,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:20:35,01:20:35,0.0,...,0,0,0,0,0,0,0,0,1,0
137,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:22:51,01:22:51,0.0,...,0,0,0,0,0,0,0,0,1,0

In [389]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
12,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:15:37,00:15:37,0.0,...,0,0,0,0,0,0,0,0,0,1
29,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:22:21,00:22:21,0.0,...,0,0,0,0,0,0,0,0,0,1
30,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:22:34,00:22:34,0.0,...,0,0,0,0,0,0,0,0,0,1
42,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:25:53,00:25:53,0.0,...,0,0,0,0,0,0,0,0,0,1
60,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:33:57,00:33:57,0.0,...,0,0,0,0,0,0,0,0,0,1
77,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:39:15,00:39:15,0.0,...,0,0,0,0,0,0,0,0,0,1
80,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:39:36,00:39:36,0.0,...,0,0,0,0,0,0,0,0,0,1
83,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:40:30,00:40:30,0.0,...,0,0,0,0,0,0,0,0,0,1
106,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:51:17,00:51:17,0.0,...,0,0,0,0,0,0,0,0,0,1
111,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:56:15,00:56:15,0.0,...,0,0,0,0,0,0,0,0,0,1
114,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:57:20,00:57:20,0.0,...,0,0,0,0,0,0,0,0,0,1
125,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:18:23,01:18:23,0.0,...,0,0,0,0,0,0,0,0,0,1
150,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:31:30,01:31:30,0.0,...,0,0,0,0,0,0,0,0,0,1
154,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:33:09,01:33:09,0.0,...,0,0,0,0,0,0,0,0,0,1
182,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:43:03,01:43:03,0.0,...,0,0,0,0,0,0,0,0,0,1
196,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:48:38,01:48:38,0.0,...,0,0,0,0,0,0,0,0,0,1
197,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:48:48,01:48:48,0.0,...,0,0,0,0,0,0,0,0,0,1
199,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:49:43,01:49:43,0.0,...,0,0,0,0,0,0,0,0,0,1
209,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:52:01,01:52:01,0.0,...,0,0,0,0,0,0,0,0,0,1
214,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:56:14,01:56:14,0.0,...,0,0,0,0,0,0,0,0,0,1
229,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:03:00,02:03:00,0.0,...,0,0,0,0,0,0,0,0,0,1

In [390]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado
109,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:55:54,00:55:54,0.0,...,0,0,0,0,0,0,0,0,1,0
189,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:46:08,01:46:08,0.0,...,0,0,0,0,0,0,0,0,1,0

In [391]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado
5,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:14:16,00:14:16,0.0,...,0,0,0,0,0,0,0,0,0,1
13,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:16:33,00:16:33,0.0,...,0,0,0,0,0,0,0,0,0,1
172,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:38:49,01:38:49,0.0,...,0,0,0,0,0,0,0,0,0,1
225,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:01:47,02:01:47,0.0,...,0,0,0,0,0,0,0,0,0,1

In [392]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
21,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:18:10,00:18:10,0.0,...,0,0,0,0,0,0,0,0,1,0
58,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:32:28,00:32:28,0.0,...,0,0,0,0,0,0,0,0,1,0
69,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:36:52,00:36:52,0.0,...,0,0,0,0,0,0,0,0,1,0
72,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:38:25,00:38:25,0.0,...,0,0,0,0,0,0,0,0,1,0
96,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:45:02,00:45:02,0.0,...,0,0,0,0,0,0,0,0,1,0
101,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:47:22,00:47:22,0.0,...,0,0,0,0,0,0,0,0,1,0
117,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:16:13,01:16:13,0.0,...,0,0,0,0,0,0,0,0,1,0
129,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:20:08,01:20:08,0.0,...,0,0,0,0,0,0,0,0,1,0
142,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:23:36,01:23:36,0.0,...,0,0,0,0,0,0,0,0,1,0
145,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:24:37,01:24:37,0.0,...,0,0,0,0,0,0,0,0,1,0
147,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:28:07,01:28:07,0.0,...,0,0,0,0,0,0,0,0,1,0
155,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:33:32,01:33:32,0.0,...,0,0,0,0,0,0,0,0,1,0
231,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:03:39,02:03:39,0.0,...,0,0,0,0,0,0,0,0,1,0
233,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:04:29,02:04:29,0.0,...,0,0,0,0,0,0,0,0,1,0

In [393]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
68,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,00:36:16,00:36:16,0.0,...,0,0,0,0,0,0,0,0,0,1
215,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,01:57:40,01:57:40,0.0,...,0,0,0,0,0,0,0,0,0,1

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [394]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        19
              disputa suelo                11
              gambeta a favor              10
pelota parada lateral corto                13
              lateral largo                10
              tiro de esquina               6
              tiro libre                   16
perdida       atajada                       7
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        13
              error tecnico                23
              intercepcion aereo            7
              interceptado                 18
              robo                          4
recuperacion  duelo                         9
              encontrada                   11
              intercepcion                  8
              intercepcion aereo            8
              intercepcion anticipo         7
              robo                         23

In [395]:
data_eventos = data_eventos[~data_eventos.Subevento.isna()].reset_index(drop=True)

In [396]:
data_eventos[data_eventos.Evento == 'perdida']

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
0,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:12:40,00:12:40,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:13:17,00:13:17,0.0,...,0,0,0,0,0,0,0,0,0,0
6,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:14:21,00:14:21,0.0,...,0,0,0,0,0,0,0,0,0,0
10,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:14:59,00:14:59,0.0,...,0,0,0,0,0,0,0,0,0,0
14,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:16:34,00:16:34,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:00:00,02:00:00,0.0,...,0,0,0,0,0,0,0,0,0,0
226,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:01:50,02:01:50,0.0,...,0,0,0,0,0,0,0,0,0,0
228,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:02:32,02:02:32,0.0,...,0,0,0,0,0,0,0,0,0,0
232,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:03:40,02:03:40,0.0,...,0,0,0,0,0,0,0,0,0,0
234,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:04:31,02:04:31,0.0,...,0,0,0,0,0,0,0,0,0,0

In [397]:
#gambeta a favor

colname = 'perdida-Gambeta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    #if (data_eventos.loc[i-1,'Evento']=='duelo') & (data_eventos.loc[i-1,'Subevento']=='gambeta a favor'):
        if (data_eventos.loc[i,'Evento'] == 'perdida') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta
10,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:14:59,00:14:59,0.0,...,0,0,0,0,0,0,0,0,0,1
16,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:17:18,00:17:18,0.0,...,0,0,0,0,0,0,0,0,0,1
59,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:33:11,00:33:11,0.0,...,0,0,0,0,0,0,0,0,0,1
82,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:39:45,00:39:45,0.0,...,0,0,0,0,0,0,0,0,0,1
104,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:48:39,00:48:39,0.0,...,0,0,0,0,0,0,0,0,0,1
115,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:57:27,00:57:27,0.0,...,0,0,0,0,0,0,0,0,0,1
133,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:20:43,01:20:43,0.0,...,0,0,0,0,0,0,0,0,0,1
139,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:23:01,01:23:01,0.0,...,0,0,0,0,0,0,0,0,0,1
177,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:39:08,01:39:08,0.0,...,0,0,0,0,0,0,0,0,0,1
181,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:42:12,01:42:12,0.0,...,0,0,0,0,0,0,0,0,0,1
192,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:47:40,01:47:40,0.0,...,0,0,0,0,0,0,0,0,0,1
219,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:58:20,01:58:20,0.0,...,0,0,0,0,0,0,0,0,0,1
221,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:59:40,01:59:40,0.0,...,0,0,0,0,0,0,0,0,0,1

In [398]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ((data_eventos.loc[i,'Subevento']=='robo')):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta,perdida-Robo
45,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:28:26,00:28:26,0.0,...,0,0,0,0,0,0,0,0,0,1
84,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:40:37,00:40:37,0.0,...,0,0,0,0,0,0,0,0,0,1
166,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:36:54,01:36:54,0.0,...,0,0,0,0,0,0,0,0,0,1
207,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:51:33,01:51:33,0.0,...,0,0,0,0,0,0,0,0,0,1

In [399]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta,perdida-Robo,perdida-Intercepcion
2,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:13:17,00:13:17,0.0,...,0,0,0,0,0,0,0,0,0,1
19,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:17:57,00:17:57,0.0,...,0,0,0,0,0,0,0,0,0,1
26,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:21:15,00:21:15,0.0,...,0,0,0,0,0,0,0,0,0,1
51,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:30:42,00:30:42,0.0,...,0,0,0,0,0,0,0,0,0,1
53,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:31:12,00:31:12,0.0,...,0,0,0,0,0,0,0,0,0,1
61,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:34:31,00:34:31,0.0,...,0,0,0,0,0,0,0,0,0,1
64,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:34:52,00:34:52,0.0,...,0,0,0,0,0,0,0,0,0,1
73,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:38:50,00:38:50,0.0,...,0,0,0,0,0,0,0,0,0,1
90,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:42:12,00:42:12,0.0,...,0,0,0,0,0,0,0,0,0,1
107,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:51:22,00:51:22,0.0,...,0,0,0,0,0,0,0,0,0,1
110,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:55:56,00:55:56,0.0,...,0,0,0,0,0,0,0,0,0,1
118,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:16:13,01:16:13,0.0,...,0,0,0,0,0,0,0,0,0,1
151,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:31:50,01:31:50,0.0,...,0,0,0,0,0,0,0,0,0,1
162,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:35:16,01:35:16,0.0,...,0,0,0,0,0,0,0,0,0,1
168,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:37:25,01:37:25,0.0,...,0,0,0,0,0,0,0,0,0,1
174,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:38:51,01:38:51,0.0,...,0,0,0,0,0,0,0,0,0,1
190,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:46:12,01:46:12,0.0,...,0,0,0,0,0,0,0,0,0,1
194,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:48:17,01:48:17,0.0,...,0,0,0,0,0,0,0,0,0,1
198,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:49:11,01:49:11,0.0,...,0,0,0,0,0,0,0,0,0,1
200,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:49:46,01:49:46,0.0,...,0,0,0,0,0,0,0,0,0,1
210,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:52:14,01:52:14,0.0,...,0,0,0,0,0,0,0,0,0,1
212,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:52:21,01:52:21,0.0,...,0,0,0,0,0,0,0,0,0,1
223,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:00:00,02:00:00,0.0,...,0,0,0,0,0,0,0,0,0,1
232,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:03:40,02:03:40,0.0,...,0,0,0,0,0,0,0,0,0,1
234,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:04:31,02:04:31,0.0,...,0,0,0,0,0,0,0,0,0,1

In [400]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico
22,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:18:33,00:18:33,0.0,...,0,0,0,0,0,0,0,0,0,1
34,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:23:11,00:23:11,0.0,...,0,0,0,0,0,0,0,0,0,1
37,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:24:31,00:24:31,0.0,...,0,0,0,0,0,0,0,0,0,1
40,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:25:15,00:25:15,0.0,...,0,0,0,0,0,0,0,0,0,1
66,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:35:29,00:35:29,0.0,...,0,0,0,0,0,0,0,0,0,1
78,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:39:19,00:39:19,0.0,...,0,0,0,0,0,0,0,0,0,1
87,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:40:58,00:40:58,0.0,...,0,0,0,0,0,0,0,0,0,1
94,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:43:12,00:43:12,0.0,...,0,0,0,0,0,0,0,0,0,1
102,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:47:34,00:47:34,0.0,...,0,0,0,0,0,0,0,0,0,1
112,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:56:45,00:56:45,0.0,...,0,0,0,0,0,0,0,0,0,1
121,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:16:30,01:16:30,0.0,...,0,0,0,0,0,0,0,0,0,1
124,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:17:59,01:17:59,0.0,...,0,0,0,0,0,0,0,0,0,1
135,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:20:53,01:20:53,0.0,...,0,0,0,0,0,0,0,0,0,1
148,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:28:17,01:28:17,0.0,...,0,0,0,0,0,0,0,0,0,1
153,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:32:42,01:32:42,0.0,...,0,0,0,0,0,0,0,0,0,1
156,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:33:33,01:33:33,0.0,...,0,0,0,0,0,0,0,0,0,1
158,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:34:18,01:34:18,0.0,...,0,0,0,0,0,0,0,0,0,1
159,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:35:08,01:35:08,0.0,...,0,0,0,0,0,0,0,0,0,1
179,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:39:28,01:39:28,0.0,...,0,0,0,0,0,0,0,0,0,1
183,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:43:13,01:43:13,0.0,...,0,0,0,0,0,0,0,0,0,1
185,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:43:47,01:43:47,0.0,...,0,0,0,0,0,0,0,0,0,1
203,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:50:21,01:50:21,0.0,...,0,0,0,0,0,0,0,0,0,1
213,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:52:52,01:52:52,0.0,...,0,0,0,0,0,0,0,0,0,1

In [401]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera
0,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:12:40,00:12:40,0.0,...,0,0,0,0,0,0,0,0,0,1
6,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:14:21,00:14:21,0.0,...,0,0,0,0,0,0,0,0,0,1
28,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:21:43,00:21:43,0.0,...,0,0,0,0,0,0,0,0,0,1
43,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:26:02,00:26:02,0.0,...,0,0,0,0,0,0,0,0,0,1
47,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:29:02,00:29:02,0.0,...,0,0,0,0,0,0,0,0,0,1
97,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:45:04,00:45:04,0.0,...,0,0,0,0,0,0,0,0,0,1
99,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:45:38,00:45:38,0.0,...,0,0,0,0,0,0,0,0,0,1
126,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:18:29,01:18:29,0.0,...,0,0,0,0,0,0,0,0,0,1
130,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:20:09,01:20:09,0.0,...,0,0,0,0,0,0,0,0,0,1
146,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:26:57,01:26:57,0.0,...,0,0,0,0,0,0,0,0,0,1
205,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:50:35,01:50:35,0.0,...,0,0,0,0,0,0,0,0,0,1
228,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:02:32,02:02:32,0.0,...,0,0,0,0,0,0,0,0,0,1

In [402]:
#situacion rival

colname = 'perdida-Error-tactico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='error tactico'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico]
Index: []

[0 rows x 66 columns]

In [403]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='atajada'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada
14,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:16:34,00:16:34,0.0,...,0,0,0,0,0,0,0,0,0,1
32,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:22:42,00:22:42,0.0,...,0,0,0,0,0,0,0,0,0,1
56,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:31:53,00:31:53,0.0,...,0,0,0,0,0,0,0,0,0,1
70,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:36:57,00:36:57,0.0,...,0,0,0,0,0,0,0,0,0,1
143,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:23:37,01:23:37,0.0,...,0,0,0,0,0,0,0,0,0,1
217,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,01:57:55,01:57:55,0.0,...,0,0,0,0,0,0,0,0,0,1
226,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:01:50,02:01:50,0.0,...,0,0,0,0,0,0,0,0,0,1

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [404]:
data[data['Jugador 1'] == 1].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
pelota parada tiro libre                 2
perdida       intercepcion aereo         1
              interceptado               1

In [405]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable]
Index: []

[0 rows x 69 columns]

In [406]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in data_eventos.loc[i,'Subevento']) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            if ('remate' in data_eventos.loc[i-1,'Evento']):
                data_eventos.loc[i-1,colname] = 1
            elif ('remate' in data_eventos.loc[i-2,'Evento']):
                data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada]
Index: []

[0 rows x 70 columns]

In [407]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [408]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 71 columns]

In [409]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 72 columns]

In [410]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 73 columns]

In [411]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano]
Index: []

[0 rows x 74 columns]

In [412]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie]
Index: []

[0 rows x 75 columns]

In [413]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 76 columns]

In [414]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [415]:
data_eventos.iloc[:,:20]

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),coord.inicial,Subevento,Jugador.2,Jugador.1,coord.final,Optional.Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco
0,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:12:40,00:12:40,0.0,9.0,balon afuera lateral,3,6.0,10,NaN,760.0,0,0,0
1,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:02,00:13:02,0.0,10.0,intercepcion anticipo,NaN,3.0,Volver,NaN,782.0,0,0,0
2,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,00:13:17,00:13:17,0.0,9.0,interceptado,4,6.0,9,NaN,797.0,0,0,0
3,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,duelo,NaN,00:13:20,00:13:20,0.0,6.0,disputa suelo,NaN,6.0,Volver,NaN,800.0,0,0,0
4,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,00:13:21,00:13:21,0.0,6.0,duelo,NaN,6.0,Volver,NaN,801.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,02:03:06,02:03:06,0.0,16.0,duelo,NaN,7.0,Volver,NaN,7386.0,0,0,0
231,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:03:39,02:03:39,0.0,16.0,tiro libre,Rival,3.0,17,NaN,7419.0,0,0,0
232,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:03:40,02:03:40,0.0,16.0,interceptado,Rival,3.0,17,NaN,7420.0,0,0,0
233,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:04:29,02:04:29,0.0,14.0,tiro libre,Rival,1.0,21,NaN,7469.0,0,0,0
234,2022/06/13,ALDOSIVI_FECHA2,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:04:31,02:04:31,0.0,14.0,interceptado,Rival,1.0,21,NaN,7471.0,0,0,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [416]:
data_eventos['coord.inicial'].value_counts()

16.0    25
9.0     21
13.0    21
10.0    20
18.0    20
15.0    19
11.0    18
14.0    14
12.0    13
24.0    11
21.0    10
17.0    10
8.0      9
7.0      8
19.0     5
6.0      5
1.0      2
20.0     1
4.0      1
5.0      1
23.0     1
Name: coord.inicial, dtype: int64

In [417]:
data_eventos['coord.final'].value_counts()

Volver    170
21         13
18          7
17          6
12          5
10          4
16          4
15          4
14          3
13          3
23          2
8           2
7           2
5           2
9           2
22          2
11          1
19          1
6           1
20          1
Name: coord.final, dtype: int64

In [418]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [419]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [420]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [421]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,10.0,65,109.0,141,22.0
1,NaN,109,NaN,22,NaN
2,9.0,65,65.0,141,141.0
3,NaN,20,NaN,147,NaN
4,NaN,20,NaN,147,NaN
...,...,...,...,...,...
230,NaN,205,NaN,23,NaN
231,17.0,205,203.0,23,80.0
232,17.0,205,203.0,23,80.0
233,21.0,161,238.0,81,80.0
234,21.0,161,238.0,81,80.0

In [422]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    235.000000
mean     148.876596
std       63.143353
min       20.000000
25%      105.000000
50%      161.000000
75%      203.000000
max      251.000000
Name: coord.inicial.x, dtype: float64

In [423]:
# añadirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    235.000000
mean     147.968142
std       64.614491
min        3.012619
25%       98.048791
50%      152.289606
75%      201.428819
max      269.516972
Name: coord.inicial.x, dtype: float64

In [424]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [425]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    235.000000
mean      83.812766
std       51.314422
min       18.000000
25%       23.000000
50%       81.000000
75%      141.000000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [426]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    235.000000
mean      85.267230
std       53.574890
min        0.142693
25%       32.454372
50%       84.932689
75%      141.242260
max      165.851403
Name: coord.inicial.y, dtype: float64

In [427]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [428]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [429]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [430]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,10.0,55.580669,120.032733,148.846974,35.158805
1,NaN,125.892854,NaN,30.326662,NaN
2,9.0,82.870794,70.996555,139.192474,136.522403
3,NaN,5.818923,NaN,162.000000,NaN
4,NaN,35.862442,NaN,160.344938,NaN
...,...,...,...,...,...
230,NaN,202.010516,NaN,38.689628,NaN
231,17.0,195.894716,204.618579,10.928297,85.999339
232,17.0,198.091761,208.818958,41.736802,65.678937
233,21.0,164.833483,235.385848,92.061488,95.839737
234,21.0,177.554008,257.006936,74.728636,97.439551

In [431]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0      56.0,149.0
1      126.0,30.0
2      83.0,139.0
3       6.0,162.0
4      36.0,160.0
          ...
230    202.0,39.0
231    196.0,11.0
232    198.0,42.0
233    165.0,92.0
234    178.0,75.0
Length: 235, dtype: object

In [432]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [433]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [434]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0          56,149      120,35
1          126,30        None
2          83,139      71,137
3           6,162        None
4          36,160        None
..            ...         ...
230        202,39        None
231        196,11      205,86
232        198,42      209,66
233        165,92      235,96
234        178,75      257,97

[235 rows x 2 columns]

# Escribir tabla filtros

In [435]:
data_eventos = data_eventos[~data_eventos['partido'].isna()].reset_index(drop=True)

In [436]:
data_eventos['partido'] = 'Aldosivi'

In [437]:
data_eventos.tail()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
230,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,recuperacion,NaN,02:03:06,02:03:06,0.0,...,0,0,0,0,0,NaN,202.010516,NaN,38.689628,NaN
231,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:03:39,02:03:39,0.0,...,0,0,0,0,0,17.0,195.894716,204.618579,10.928297,85.999339
232,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:03:40,02:03:40,0.0,...,0,0,0,0,0,17.0,198.091761,208.818958,41.736802,65.678937
233,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,pelota parada,NaN,02:04:29,02:04:29,0.0,...,0,0,0,0,0,21.0,164.833483,235.385848,92.061488,95.839737
234,2022/06/13,Aldosivi,ALDOSIVI_FECHA2_ACCIONES,11:04:15,13:13:33,perdida,NaN,02:04:31,02:04:31,0.0,...,0,0,0,0,0,21.0,177.554008,257.006936,74.728636,97.439551

In [438]:
data_eventos.to_csv("../Datos generados para la app/reserva02-22-fecha2_aldosivi-tabla_filtros.csv",index=False)