In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import glob
import os
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [37]:
# merging the files
files_joined = os.path.join('..\\..\\datos etiquetas\\Tem2-2022\\Fecha 7 - Central Cordoba', "*.csv")

# Return a list of all joined files
list_files = glob.glob(files_joined)

#print("** Merging multiple csv files into a single pandas dataframe **")
# Merge files by joining all files
data = pd.concat(map(pd.read_csv, list_files), ignore_index=True)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   312 non-null    object
 1   Event                312 non-null    object
 2   Session Name         312 non-null    object
 3   Session Start        312 non-null    object
 4   Session End          312 non-null    object
 5   Tag Description      312 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            312 non-null    object
 8   Tag End              312 non-null    object
 9   Tag Duration (secs)  312 non-null    float64
 10  Zonas                309 non-null    float64
 11  Categoria            309 non-null    object
 12  Jugador2             226 non-null    object
 13  Jugador              307 non-null    float64
 14  Zonas_final          309 non-null    object
 15  Dificultad           1 non-null      object
 16  Optional Column      0 non-null      float64
dtypes: float64(5), object(12)
memory usage: 41.6+ KB

In [39]:
# data.columns = ['Session Start Date','partido','tiempo','Session Start',
#        'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
#        'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Optional Column']

data.columns = ['Session Start Date','tiempo','partido','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Dificultad','Optional Column']

In [40]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [41]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 313 entries, 0 to 312
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   312 non-null    object
 1   tiempo               312 non-null    object
 2   partido              312 non-null    object
 3   Session Start        312 non-null    object
 4   Session End          312 non-null    object
 5   Evento               312 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            312 non-null    object
 8   Tag End              312 non-null    object
 9   Tag Duration (secs)  312 non-null    float64
 10  coord inicial        309 non-null    float64
 11  Subevento            309 non-null    object
 12  Jugador 2            226 non-null    object
 13  Jugador 1            307 non-null    float64
 14  coord final          309 non-null    object
 15  Dificultad           1 non-null      object
 16  Optional Column      0 non-null      float64
 17  segundos             312 non-null    float64
dtypes: float64(6), object(12)
memory usage: 44.1+ KB

In [43]:
data

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Dificultad,Optional Column,segundos
0,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Pase,NaN,00:09:51,00:09:51,0.0,24.0,corto,5,3.0,15,NaN,NaN,591.0
1,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Remate pie,NaN,00:09:56,00:09:56,0.0,15.0,Media distancia,Rival,5.0,22,NaN,NaN,596.0
2,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Perdida,NaN,00:09:56,00:09:56,0.0,15.0,Balon afuera fondo,NaN,5.0,Volver,NaN,NaN,596.0
3,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Remate pie,NaN,00:10:26,00:10:26,0.0,23.0,Corta distancia,Rival,4.0,22,NaN,NaN,626.0
4,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Perdida,NaN,00:10:26,00:10:26,0.0,23.0,Atajada,NaN,4.0,Volver,NaN,NaN,626.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Pase,NaN,02:00:24,02:00:24,0.0,17.0,corto,8,5.0,18,NaN,NaN,7224.0
309,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Pase,NaN,02:00:27,02:00:27,0.0,18.0,corto,16,8.0,24,NaN,NaN,7227.0
310,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Remate pie,NaN,00:47:12,00:47:12,0.0,22.0,Corta distancia,Rival,2.0,22,NaN,NaN,2832.0
311,2022/07/14,central cordoba,pases,11:05:27,13:15:32,Gol,NaN,00:47:12,00:47:12,0.0,22.0,Directa,NaN,2.0,Volver,NaN,NaN,2832.0
312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [45]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [46]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       remate atajable              4
              salvada/atajada              1
falta         hecha                       13
              offside                      1
              recibida                    10
gol           directa                      1
gol rival     indirecta                    2
pase          centro aereo                 8
              corto                      137
              inteligente                  3
              largo                       15
              medio                       31
              s arquero mano               4
              s arquero pie               13
perdida       atajada                      8
              balon afuera fondo           7
              balon afuera lateral         8
              error tecnico                1
              interceptado                25
              robo                         1
remate cabeza dificil                      1
remate pie    corta distancia              7
              larga distancia              1
              media distancia              5
tarjeta       amarilla                     2

In [47]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                   cantidad
Jugador 1 Evento  Subevento
1.0       arquero remate atajable         4
                  salvada/atajada         1
          pase    corto                   3
                  largo                   2
                  s arquero mano          4
...                                     ...
18.0      falta   hecha                   2
                  offside                 1
          pase    corto                   7
                  medio                   2
          perdida interceptado            1

[102 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [48]:
data_eventos = data.copy()
data_eventos.shape

(313, 18)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [49]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
            
data_eventos.loc[data_eventos['remate-Gol'] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Dificultad,Optional Column,segundos,remate-Gol
310,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:47:12,00:47:12,0.0,22.0,corta distancia,Rival,2.0,22,NaN,NaN,2832.0,1

In [50]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera
1,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:09:56,00:09:56,0.0,15.0,media distancia,Rival,5.0,22,NaN,NaN,596.0,0,1
8,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:11:49,00:11:49,0.0,16.0,corta distancia,Rival,5.0,22,NaN,NaN,709.0,0,1
60,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:34:03,00:34:03,0.0,24.0,corta distancia,Rival,11.0,22,NaN,NaN,2043.0,0,1
137,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,01:21:33,01:21:33,0.0,21.0,media distancia,Rival,9.0,22,NaN,NaN,4893.0,0,1
193,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,01:36:13,01:36:13,0.0,21.0,corta distancia,Rival,16.0,20,NaN,NaN,5773.0,0,1
259,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,01:49:53,01:49:53,0.0,17.0,media distancia,Rival,14.0,22,NaN,NaN,6593.0,0,1
268,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,01:51:54,01:51:54,0.0,17.0,media distancia,Rival,17.0,20,NaN,NaN,6714.0,0,1

In [51]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Subevento,Jugador 2,Jugador 1,coord final,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco
3,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:10:26,00:10:26,0.0,...,corta distancia,Rival,4.0,22,NaN,NaN,626.0,0,0,1
5,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:11:05,00:11:05,0.0,...,corta distancia,Rival,4.0,22,NaN,NaN,665.0,0,0,1
32,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate cabeza,NaN,00:21:27,00:21:27,0.0,...,dificil,Rival,9.0,22,NaN,NaN,1287.0,0,0,1
47,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:27:17,00:27:17,0.0,...,media distancia,Rival,5.0,22,NaN,NaN,1637.0,0,0,1
165,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,01:26:17,01:26:17,0.0,...,larga distancia,Rival,10.0,22,NaN,NaN,5177.0,0,0,1
228,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,01:44:18,01:44:18,0.0,...,corta distancia,Rival,14.0,22,NaN,NaN,6258.0,0,0,1

In [52]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado]
Index: []

[0 rows x 22 columns]

In [53]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 1,coord final,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
32,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate cabeza,NaN,00:21:27,00:21:27,0.0,...,9.0,22,NaN,NaN,1287.0,0,0,1,0,1

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [54]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                       cantidad
Evento Subevento
pase   centro aereo           8
       corto                137
       inteligente            3
       largo                 15
       medio                 31
       s arquero mano         4
       s arquero pie         13

In [55]:
data[(data.Evento=='pase') ]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Dificultad,Optional Column,segundos
0,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:09:51,00:09:51,0.0,24.0,corto,5,3.0,15,NaN,NaN,591.0
7,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:11:44,00:11:44,0.0,13.0,corto,5,10.0,13,NaN,NaN,704.0
10,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:13:15,00:13:15,0.0,9.0,corto,4,2.0,12,NaN,NaN,795.0
11,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:13:18,00:13:18,0.0,9.0,corto,5,4.0,9,NaN,NaN,798.0
12,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:13:19,00:13:19,0.0,9.0,corto,2,5.0,9,NaN,NaN,799.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:17,02:00:17,0.0,18.0,largo,3,8.0,19,NaN,NaN,7217.0
306,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:21,02:00:21,0.0,19.0,centro aereo,14,3.0,17,NaN,NaN,7221.0
307,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:22,02:00:22,0.0,17.0,corto,5,14.0,17,NaN,NaN,7222.0
308,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:24,02:00:24,0.0,17.0,corto,8,5.0,18,NaN,NaN,7224.0
309,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:27,02:00:27,0.0,18.0,corto,16,8.0,24,NaN,NaN,7227.0

In [56]:
data_eventos.head()

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 1,coord final,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
0,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:09:51,00:09:51,0.0,...,3.0,15,NaN,NaN,591.0,0,0,0,0,0
1,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:09:56,00:09:56,0.0,...,5.0,22,NaN,NaN,596.0,0,1,0,0,0
2,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:09:56,00:09:56,0.0,...,5.0,Volver,NaN,NaN,596.0,0,0,0,0,0
3,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:10:26,00:10:26,0.0,...,4.0,22,NaN,NaN,626.0,0,0,1,0,0
4,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:10:26,00:10:26,0.0,...,4.0,Volver,NaN,NaN,626.0,0,0,0,0,0

In [58]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''
colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia]
Index: []

[0 rows x 24 columns]

In [59]:
##completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') & (data_eventos.loc[i,'Jugador 2'] != 'Rival')):
        if ((data_eventos.loc[i+1,'Evento'] != 'perdida') ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado
0,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:09:51,00:09:51,0.0,...,NaN,NaN,591.0,0,0,0,0,0,0,1
7,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:11:44,00:11:44,0.0,...,NaN,NaN,704.0,0,0,0,0,0,0,1
10,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:13:15,00:13:15,0.0,...,NaN,NaN,795.0,0,0,0,0,0,0,1
11,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:13:18,00:13:18,0.0,...,NaN,NaN,798.0,0,0,0,0,0,0,1
12,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:13:19,00:13:19,0.0,...,NaN,NaN,799.0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:17,02:00:17,0.0,...,NaN,NaN,7217.0,0,0,0,0,0,0,1
306,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:21,02:00:21,0.0,...,NaN,NaN,7221.0,0,0,0,0,0,0,1
307,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:22,02:00:22,0.0,...,NaN,NaN,7222.0,0,0,0,0,0,0,1
308,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:24,02:00:24,0.0,...,NaN,NaN,7224.0,0,0,0,0,0,0,1
309,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:27,02:00:27,0.0,...,NaN,NaN,7227.0,0,0,0,0,0,0,1

In [60]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

corto           128
medio            18
largo             7
centro aereo      5
inteligente       3
Name: Subevento, dtype: int64

In [61]:
#Incompleto
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Incompleto'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') ):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') ):
            #if ((data_eventos.loc[i,'pase-Completado'] != 1)):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto
19,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:14:58,00:14:58,0.0,...,NaN,898.0,0,0,0,0,0,0,0,1
29,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:19:57,00:19:57,0.0,...,NaN,1197.0,0,0,0,0,0,0,0,1
39,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:22:47,00:22:47,0.0,...,NaN,1367.0,0,0,0,0,0,0,0,1
45,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:25:30,00:25:30,0.0,...,NaN,1530.0,0,0,0,0,0,0,0,1
57,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:31:06,00:31:06,0.0,...,NaN,1866.0,0,0,0,0,0,0,0,1
74,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:41:02,00:41:02,0.0,...,NaN,2462.0,0,0,0,0,0,0,0,1
82,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:49:18,00:49:18,0.0,...,NaN,2958.0,0,0,0,0,0,0,0,1
86,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:53:50,00:53:50,0.0,...,NaN,3230.0,0,0,0,0,0,0,0,1
97,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:13:25,01:13:25,0.0,...,NaN,4405.0,0,0,0,0,0,0,0,1
102,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:16:14,01:16:14,0.0,...,NaN,4574.0,0,0,0,0,0,0,0,1
112,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:18:06,01:18:06,0.0,...,NaN,4686.0,0,0,0,0,0,0,0,1
116,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:18:40,01:18:40,0.0,...,NaN,4720.0,0,0,0,0,0,0,0,1
124,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:19:41,01:19:41,0.0,...,NaN,4781.0,0,0,0,0,0,0,0,1
130,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:21:11,01:21:11,0.0,...,NaN,4871.0,0,0,0,0,0,0,0,1
144,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:22:46,01:22:46,0.0,...,NaN,4966.0,0,0,0,0,0,0,0,1
150,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:23:57,01:23:57,0.0,...,NaN,5037.0,0,0,0,0,0,0,0,1
158,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:25:29,01:25:29,0.0,...,NaN,5129.0,0,0,0,0,0,0,0,1
169,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:26:45,01:26:45,0.0,...,NaN,5205.0,0,0,0,0,0,0,0,1
174,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:30:51,01:30:51,0.0,...,NaN,5451.0,0,0,0,0,0,0,0,1
178,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:32:37,01:32:37,0.0,...,NaN,5557.0,0,0,0,0,0,0,0,1
187,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:34:57,01:34:57,0.0,...,NaN,5697.0,0,0,0,0,0,0,0,1
197,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:38:23,01:38:23,0.0,...,NaN,5903.0,0,0,0,0,0,0,0,1
204,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:39:58,01:39:58,0.0,...,NaN,5998.0,0,0,0,0,0,0,0,1
212,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:40:56,01:40:56,0.0,...,NaN,6056.0,0,0,0,0,0,0,0,1
219,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:43:01,01:43:01,0.0,...,NaN,6181.0,0,0,0,0,0,0,0,1
242,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:46:35,01:46:35,0.0,...,NaN,6395.0,0,0,0,0,0,0,0,1
251,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:48:53,01:48:53,0.0,...,NaN,6533.0,0,0,0,0,0,0,0,1
254,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:49:06,01:49:06,0.0,...,NaN,6546.0,0,0,0,0,0,0,0,1
283,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:55:55,01:55:55,0.0,...,NaN,6955.0,0,0,0,0,0,0,0,1
289,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:58:02,01:58:02,0.0,...,NaN,7082.0,0,0,0,0,0,0,0,1
292,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:58:47,01:58:47,0.0,...,NaN,7127.0,0,0,0,0,0,0,0,1
298,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:59:39,01:59:39,0.0,...,NaN,7179.0,0,0,0,0,0,0,0,1
302,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:59:59,01:59:59,0.0,...,NaN,7199.0,0,0,0,0,0,0,0,1

In [ ]:
# #fuera
# '''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

# colname = 'pase-Fuera'
# data_eventos[colname] = 0
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
#         if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
#             if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
#                 data_eventos.loc[i,colname] = 1
            
# data_eventos.loc[data_eventos[colname] == 1]

In [62]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto,pase-Inteligente
135,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:21:30,01:21:30,0.0,...,4890.0,0,0,0,0,0,0,1,0,1
149,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:23:53,01:23:53,0.0,...,5033.0,0,0,0,0,0,0,1,0,1
294,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:59:04,01:59:04,0.0,...,7144.0,0,0,0,0,0,0,1,0,1

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [63]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       remate atajable              4
              salvada/atajada              1
falta         hecha                       13
              offside                      1
              recibida                    10
gol           directa                      1
gol rival     indirecta                    2
pase          centro aereo                 8
              corto                      137
              inteligente                  3
              largo                       15
              medio                       31
              s arquero mano               4
              s arquero pie               13
perdida       atajada                      8
              balon afuera fondo           7
              balon afuera lateral         8
              error tecnico                1
              interceptado                25
              robo                         1
remate cabeza dificil                      1
remate pie    corta distancia              7
              larga distancia              1
              media distancia              5
tarjeta       amarilla                     2

In [64]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 28 columns]

In [65]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado
227,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:44:14,01:44:14,0.0,...,0,0,0,0,0,1,0,0,0,1
267,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:51:45,01:51:45,0.0,...,0,0,0,0,0,1,0,0,0,1
275,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:54:18,01:54:18,0.0,...,0,0,0,0,0,1,0,0,0,1
295,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:59:24,01:59:24,0.0,...,0,0,0,0,0,1,0,0,0,1
306,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:21,02:00:21,0.0,...,0,0,0,0,0,1,0,0,0,1

In [66]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado
112,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:18:06,01:18:06,0.0,...,0,0,0,0,0,1,0,0,0,1
158,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:25:29,01:25:29,0.0,...,0,0,0,0,0,1,0,0,0,1
174,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:30:51,01:30:51,0.0,...,0,0,0,0,0,1,0,0,0,1

In [67]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 31 columns]

In [68]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 32 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [69]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       remate atajable              4
              salvada/atajada              1
falta         hecha                       13
              offside                      1
              recibida                    10
gol           directa                      1
gol rival     indirecta                    2
pase          centro aereo                 8
              corto                      137
              inteligente                  3
              largo                       15
              medio                       31
              s arquero mano               4
              s arquero pie               13
perdida       atajada                      8
              balon afuera fondo           7
              balon afuera lateral         8
              error tecnico                1
              interceptado                25
              robo                         1
remate cabeza dificil                      1
remate pie    corta distancia              7
              larga distancia              1
              media distancia              5
tarjeta       amarilla                     2

In [ ]:
# dejar_index= []
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='duelo'):
#         dejar_index.append(i-1)
#         dejar_index.append(i)
#         dejar_index.append(i+1)
# data_eventos.loc[dejar_index].head(10)

In [70]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1


data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado]
Index: []

[0 rows x 34 columns]

In [71]:
data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado]
Index: []

[0 rows x 34 columns]

In [72]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada]
Index: []

[0 rows x 36 columns]

In [73]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada]
Index: []

[0 rows x 36 columns]

In [74]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [75]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [76]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada]
Index: []

[0 rows x 40 columns]

In [77]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada]
Index: []

[0 rows x 40 columns]

In [78]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 42 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [79]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       remate atajable              4
              salvada/atajada              1
falta         hecha                       13
              offside                      1
              recibida                    10
gol           directa                      1
gol rival     indirecta                    2
pase          centro aereo                 8
              corto                      137
              inteligente                  3
              largo                       15
              medio                       31
              s arquero mano               4
              s arquero pie               13
perdida       atajada                      8
              balon afuera fondo           7
              balon afuera lateral         8
              error tecnico                1
              interceptado                25
              robo                         1
remate cabeza dificil                      1
remate pie    corta distancia              7
              larga distancia              1
              media distancia              5
tarjeta       amarilla                     2

In [80]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida
24,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:16:44,00:16:44,0.0,...,0,0,0,0,0,0,0,0,0,1
25,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:18:01,00:18:01,0.0,...,0,0,0,0,0,0,0,0,0,1
41,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:23:49,00:23:49,0.0,...,0,0,0,0,0,0,0,0,0,1
51,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:28:15,00:28:15,0.0,...,0,0,0,0,0,0,0,0,0,1
88,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:54:16,00:54:16,0.0,...,0,0,0,0,0,0,0,0,0,1
91,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:56:07,00:56:07,0.0,...,0,0,0,0,0,0,0,0,0,1
171,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:28:01,01:28:01,0.0,...,0,0,0,0,0,0,0,0,0,1
181,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:33:51,01:33:51,0.0,...,0,0,0,0,0,0,0,0,0,1
182,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:34:22,01:34:22,0.0,...,0,0,0,0,0,0,0,0,0,1
217,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:42:25,01:42:25,0.0,...,0,0,0,0,0,0,0,0,0,1
240,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:45:57,01:45:57,0.0,...,0,0,0,0,0,0,0,0,0,1
285,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:56:15,01:56:15,0.0,...,0,0,0,0,0,0,0,0,0,1
291,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:58:13,01:58:13,0.0,...,0,0,0,0,0,0,0,0,0,1

In [81]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida
16,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:13:29,00:13:29,0.0,...,0,0,0,0,0,0,0,0,0,1
42,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:25:08,00:25:08,0.0,...,0,0,0,0,0,0,0,0,0,1
76,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:42:21,00:42:21,0.0,...,0,0,0,0,0,0,0,0,0,1
80,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:45:33,00:45:33,0.0,...,0,0,0,0,0,0,0,0,0,1
84,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,00:50:22,00:50:22,0.0,...,0,0,0,0,0,0,0,0,0,1
111,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:17:14,01:17:14,0.0,...,0,0,0,0,0,0,0,0,0,1
173,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:29:57,01:29:57,0.0,...,0,0,0,0,0,0,0,0,0,1
195,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:37:47,01:37:47,0.0,...,0,0,0,0,0,0,0,0,0,1
234,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:45:34,01:45:34,0.0,...,0,0,0,0,0,0,0,0,0,1
270,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:52:31,01:52:31,0.0,...,0,0,0,0,0,0,0,0,0,1

In [82]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 45 columns]

In [83]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 46 columns]

In [84]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside
232,2022/07/14,central cordoba,pases,11:05:27,13:15:32,falta,NaN,01:44:47,01:44:47,0.0,...,0,0,0,0,0,0,0,0,0,1

In [86]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    # if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i,'Evento']=='tarjeta') & (data_eventos.loc[i,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla
221,2022/07/14,central cordoba,pases,11:05:27,13:15:32,tarjeta,NaN,01:43:25,01:43:25,0.0,...,0,0,0,0,0,0,0,0,0,1
286,2022/07/14,central cordoba,pases,11:05:27,13:15:32,tarjeta,NaN,01:56:15,01:56:15,0.0,...,0,0,0,0,0,0,0,0,0,1

In [87]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    # if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i,'Evento']=='tarjeta') & (data_eventos.loc[i,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja]
Index: []

[0 rows x 49 columns]

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [88]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       remate atajable              4
              salvada/atajada              1
falta         hecha                       13
              offside                      1
              recibida                    10
gol           directa                      1
gol rival     indirecta                    2
pase          centro aereo                 8
              corto                      137
              inteligente                  3
              largo                       15
              medio                       31
              s arquero mano               4
              s arquero pie               13
perdida       atajada                      8
              balon afuera fondo           7
              balon afuera lateral         8
              error tecnico                1
              interceptado                25
              robo                         1
remate cabeza dificil                      1
remate pie    corta distancia              7
              larga distancia              1
              media distancia              5
tarjeta       amarilla                     2

In [89]:
colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo]
Index: []

[0 rows x 50 columns]

In [90]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada]
Index: []

[0 rows x 51 columns]

In [91]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo]
Index: []

[0 rows x 52 columns]

In [92]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo]
Index: []

[0 rows x 53 columns]

In [93]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo]
Index: []

[0 rows x 54 columns]

In [94]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
    if (data_eventos.loc[i,'Evento'] == 'recuperacion') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo]
Index: []

[0 rows x 55 columns]

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [95]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       remate atajable              4
              salvada/atajada              1
falta         hecha                       13
              offside                      1
              recibida                    10
gol           directa                      1
gol rival     indirecta                    2
pase          centro aereo                 8
              corto                      137
              inteligente                  3
              largo                       15
              medio                       31
              s arquero mano               4
              s arquero pie               13
perdida       atajada                      8
              balon afuera fondo           7
              balon afuera lateral         8
              error tecnico                1
              interceptado                25
              robo                         1
remate cabeza dificil                      1
remate pie    corta distancia              7
              larga distancia              1
              media distancia              5
tarjeta       amarilla                     2

In [96]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado]
Index: []

[0 rows x 57 columns]

In [97]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado]
Index: []

[0 rows x 57 columns]

In [98]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 59 columns]

In [99]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 59 columns]

In [100]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado]
Index: []

[0 rows x 61 columns]

In [101]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado]
Index: []

[0 rows x 61 columns]

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [102]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                    cantidad
Evento        Subevento
arquero       remate atajable              4
              salvada/atajada              1
falta         hecha                       13
              offside                      1
              recibida                    10
gol           directa                      1
gol rival     indirecta                    2
pase          centro aereo                 8
              corto                      137
              inteligente                  3
              largo                       15
              medio                       31
              s arquero mano               4
              s arquero pie               13
perdida       atajada                      8
              balon afuera fondo           7
              balon afuera lateral         8
              error tecnico                1
              interceptado                25
              robo                         1
remate cabeza dificil                      1
remate pie    corta distancia              7
              larga distancia              1
              media distancia              5
tarjeta       amarilla                     2

In [103]:
# data_eventos = data_eventos[~data_eventos.Subevento.isna()].reset_index(drop=True)

In [104]:
data_eventos[data_eventos.Evento == 'perdida']

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
2,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:09:56,00:09:56,0.0,...,0,0,0,0,0,0,0,0,0,0
4,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:10:26,00:10:26,0.0,...,0,0,0,0,0,0,0,0,0,0
6,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:11:07,00:11:07,0.0,...,0,0,0,0,0,0,0,0,0,0
9,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:11:50,00:11:50,0.0,...,0,0,0,0,0,0,0,0,0,0
20,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:15:01,00:15:01,0.0,...,0,0,0,0,0,0,0,0,0,0
30,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:19:57,00:19:57,0.0,...,0,0,0,0,0,0,0,0,0,0
33,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:21:28,00:21:28,0.0,...,0,0,0,0,0,0,0,0,0,0
40,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:22:48,00:22:48,0.0,...,0,0,0,0,0,0,0,0,0,0
46,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:25:31,00:25:31,0.0,...,0,0,0,0,0,0,0,0,0,0
48,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:27:18,00:27:18,0.0,...,0,0,0,0,0,0,0,0,0,0
50,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:27:57,00:27:57,0.0,...,0,0,0,0,0,0,0,0,0,0
58,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:31:08,00:31:08,0.0,...,0,0,0,0,0,0,0,0,0,0
61,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:34:04,00:34:04,0.0,...,0,0,0,0,0,0,0,0,0,0
64,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:36:04,00:36:04,0.0,...,0,0,0,0,0,0,0,0,0,0
75,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:41:03,00:41:03,0.0,...,0,0,0,0,0,0,0,0,0,0
83,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:49:21,00:49:21,0.0,...,0,0,0,0,0,0,0,0,0,0
87,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:53:51,00:53:51,0.0,...,0,0,0,0,0,0,0,0,0,0
98,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:13:25,01:13:25,0.0,...,0,0,0,0,0,0,0,0,0,0
100,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:15:00,01:15:00,0.0,...,0,0,0,0,0,0,0,0,0,0
103,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:16:15,01:16:15,0.0,...,0,0,0,0,0,0,0,0,0,0
113,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:18:06,01:18:06,0.0,...,0,0,0,0,0,0,0,0,0,0
117,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:18:40,01:18:40,0.0,...,0,0,0,0,0,0,0,0,0,0
125,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:19:41,01:19:41,0.0,...,0,0,0,0,0,0,0,0,0,0
127,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:20:46,01:20:46,0.0,...,0,0,0,0,0,0,0,0,0,0
131,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:21:11,01:21:11,0.0,...,0,0,0,0,0,0,0,0,0,0
138,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:21:33,01:21:33,0.0,...,0,0,0,0,0,0,0,0,0,0
145,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:22:46,01:22:46,0.0,...,0,0,0,0,0,0,0,0,0,0
151,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:23:58,01:23:58,0.0,...,0,0,0,0,0,0,0,0,0,0
159,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:25:30,01:25:30,0.0,...,0,0,0,0,0,0,0,0,0,0
166,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:26:18,01:26:18,0.0,...,0,0,0,0,0,0,0,0,0,0
170,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:26:45,01:26:45,0.0,...,0,0,0,0,0,0,0,0,0,0
175,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:30:51,01:30:51,0.0,...,0,0,0,0,0,0,0,0,0,0
179,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:32:37,01:32:37,0.0,...,0,0,0,0,0,0,0,0,0,0
188,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:34:58,01:34:58,0.0,...,0,0,0,0,0,0,0,0,0,0
194,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:36:14,01:36:14,0.0,...,0,0,0,0,0,0,0,0,0,0
198,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:38:24,01:38:24,0.0,...,0,0,0,0,0,0,0,0,0,0
205,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:39:59,01:39:59,0.0,...,0,0,0,0,0,0,0,0,0,0
213,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:40:56,01:40:56,0.0,...,0,0,0,0,0,0,0,0,0,0
220,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:43:02,01:43:02,0.0,...,0,0,0,0,0,0,0,0,0,0
229,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:44:19,01:44:19,0.0,...,0,0,0,0,0,0,0,0,0,0
243,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:46:35,01:46:35,0.0,...,0,0,0,0,0,0,0,0,0,0
252,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:48:53,01:48:53,0.0,...,0,0,0,0,0,0,0,0,0,0
255,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:49:07,01:49:07,0.0,...,0,0,0,0,0,0,0,0,0,0
260,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:49:53,01:49:53,0.0,...,0,0,0,0,0,0,0,0,0,0
269,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:51:54,01:51:54,0.0,...,0,0,0,0,0,0,0,0,0,0
284,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:55:55,01:55:55,0.0,...,0,0,0,0,0,0,0,0,0,0
290,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:58:02,01:58:02,0.0,...,0,0,0,0,0,0,0,0,0,0
293,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:58:48,01:58:48,0.0,...,0,0,0,0,0,0,0,0,0,0
299,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:59:40,01:59:40,0.0,...,0,0,0,0,0,0,0,0,0,0
303,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,01:59:59,01:59:59,0.0,...,0,0,0,0,0,0,0,0,0,0

In [105]:
#gambeta a favor

colname = 'perdida-Gambeta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    #if (data_eventos.loc[i-1,'Evento']=='duelo') & (data_eventos.loc[i-1,'Subevento']=='gambeta a favor'):
        if (data_eventos.loc[i,'Evento'] == 'perdida') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta]
Index: []

[0 rows x 62 columns]

In [106]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ((data_eventos.loc[i,'Subevento']=='robo')):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo]
Index: []

[0 rows x 63 columns]

In [107]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion]
Index: []

[0 rows x 64 columns]

In [108]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico]
Index: []

[0 rows x 65 columns]

In [109]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera]
Index: []

[0 rows x 66 columns]

In [110]:
#situacion rival

colname = 'perdida-Error-tactico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='error tactico'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico]
Index: []

[0 rows x 67 columns]

In [111]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='atajada'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada]
Index: []

[0 rows x 68 columns]

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [112]:
data[data['Jugador 1'] == 1].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                              cantidad
Evento  Subevento
arquero remate atajable              4
        salvada/atajada              1
pase    corto                        3
        largo                        2
        s arquero mano               4
        s arquero pie               13
perdida atajada                      1
        balon afuera lateral         1
        interceptado                 4

In [113]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Tiro-libre-completado,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable
34,2022/07/14,central cordoba,pases,11:05:27,13:15:32,gol rival,NaN,00:21:49,00:21:49,0.0,...,0,0,0,0,0,0,0,0,1,0
199,2022/07/14,central cordoba,pases,11:05:27,13:15:32,gol rival,NaN,01:38:55,01:38:55,0.0,...,0,0,0,0,0,0,0,0,1,1

In [114]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in data_eventos.loc[i,'Subevento']) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            if ('remate' in data_eventos.loc[i-1,'Evento']):
                data_eventos.loc[i-1,colname] = 1
            elif ('remate' in data_eventos.loc[i-2,'Evento']):
                data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada
189,2022/07/14,central cordoba,pases,11:05:27,13:15:32,arquero,NaN,01:35:16,01:35:16,0.0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [115]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 72 columns]

In [116]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 73 columns]

In [117]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 74 columns]

In [118]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano
78,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:45:24,00:45:24,0.0,...,0,0,0,0,0,0,0,0,0,1
114,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:18:34,01:18:34,0.0,...,0,0,0,0,0,0,0,0,0,1
184,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:34:47,01:34:47,0.0,...,0,0,0,0,0,0,0,0,0,1
233,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:45:27,01:45:27,0.0,...,0,0,0,0,0,0,0,0,0,1

In [119]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie
26,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:19:42,00:19:42,0.0,...,0,0,0,0,0,0,0,0,0,1
49,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:27:54,00:27:54,0.0,...,0,0,0,0,0,0,0,0,0,1
63,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:36:04,00:36:04,0.0,...,0,0,0,0,0,0,0,0,0,1
85,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:53:47,00:53:47,0.0,...,0,0,0,0,0,0,0,0,0,1
99,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:15:00,01:15:00,0.0,...,0,0,0,0,0,0,0,0,0,1
101,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:16:08,01:16:08,0.0,...,0,0,0,0,0,0,0,0,0,1
118,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:19:02,01:19:02,0.0,...,0,0,0,0,0,0,0,0,0,1
126,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:20:46,01:20:46,0.0,...,0,0,0,0,0,0,0,0,0,1
146,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:23:45,01:23:45,0.0,...,0,0,0,0,0,0,0,0,0,1
177,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:32:30,01:32:30,0.0,...,0,0,0,0,0,0,0,0,0,1
210,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:40:49,01:40:49,0.0,...,0,0,0,0,0,0,0,0,0,1
218,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:42:56,01:42:56,0.0,...,0,0,0,0,0,0,0,0,0,1
287,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,01:57:56,01:57:56,0.0,...,0,0,0,0,0,0,0,0,0,1

In [120]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 77 columns]

In [121]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [122]:
data_eventos.iloc[:,:20]

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),coord.inicial,Subevento,Jugador.2,Jugador.1,coord.final,Dificultad,Optional.Column,segundos,remate-Gol,remate-Fuera
0,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,00:09:51,00:09:51,0.0,24.0,corto,5,3.0,15,NaN,NaN,591.0,0,0
1,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:09:56,00:09:56,0.0,15.0,media distancia,Rival,5.0,22,NaN,NaN,596.0,0,1
2,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:09:56,00:09:56,0.0,15.0,balon afuera fondo,NaN,5.0,Volver,NaN,NaN,596.0,0,0
3,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:10:26,00:10:26,0.0,23.0,corta distancia,Rival,4.0,22,NaN,NaN,626.0,0,0
4,2022/07/14,central cordoba,pases,11:05:27,13:15:32,perdida,NaN,00:10:26,00:10:26,0.0,23.0,atajada,NaN,4.0,Volver,NaN,NaN,626.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:24,02:00:24,0.0,17.0,corto,8,5.0,18,NaN,NaN,7224.0,0,0
309,2022/07/14,central cordoba,pases,11:05:27,13:15:32,pase,NaN,02:00:27,02:00:27,0.0,18.0,corto,16,8.0,24,NaN,NaN,7227.0,0,0
310,2022/07/14,central cordoba,pases,11:05:27,13:15:32,remate pie,NaN,00:47:12,00:47:12,0.0,22.0,corta distancia,Rival,2.0,22,NaN,NaN,2832.0,1,0
311,2022/07/14,central cordoba,pases,11:05:27,13:15:32,gol,NaN,00:47:12,00:47:12,0.0,22.0,directa,NaN,2.0,Volver,NaN,NaN,2832.0,0,0
312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [123]:
data_eventos['coord.inicial'].value_counts()

14.0    24
16.0    24
17.0    23
10.0    23
15.0    22
3.0     21
11.0    21
18.0    19
9.0     18
8.0     18
12.0    15
13.0    12
4.0     11
1.0      9
19.0     9
7.0      8
21.0     8
24.0     6
5.0      4
23.0     4
2.0      4
22.0     3
6.0      2
20.0     1
Name: coord.inicial, dtype: int64

In [124]:
data_eventos['coord.final'].value_counts()

Volver    83
16        23
17        19
18        17
11        16
10        15
22        15
13        14
21        14
15        13
8         13
12        11
14        11
9          9
7          5
20         5
3          5
1          4
24         3
19         3
2          3
5          2
4          2
6          2
23         2
Name: coord.final, dtype: int64

In [125]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [126]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [127]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [128]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,15.0,250.0,160.0,147.0,142.0
1,22.0,160.0,260.0,142.0,81.0
2,NaN,160.0,NaN,142.0,NaN
3,22.0,250.0,260.0,119.0,81.0
4,NaN,250.0,NaN,119.0,NaN
...,...,...,...,...,...
308,18.0,203.0,203.0,80.0,141.0
309,24.0,203.0,250.0,141.0,147.0
310,22.0,260.0,260.0,81.0,81.0
311,NaN,260.0,NaN,81.0,NaN
312,NaN,NaN,NaN,NaN,NaN

In [129]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    309.000000
mean     131.844660
std       73.798571
min       12.000000
25%       66.000000
50%      160.000000
75%      203.000000
max      260.000000
Name: coord.inicial.x, dtype: float64

In [130]:
# añadirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    309.000000
mean     131.708713
std       75.882217
min       -5.191609
25%       67.733822
50%      141.049544
75%      197.593087
max      269.071460
Name: coord.inicial.x, dtype: float64

In [131]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [132]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    309.000000
mean      81.093851
std       44.788401
min       18.000000
25%       23.000000
50%       81.000000
75%      138.000000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [133]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    309.000000
mean      80.083118
std       46.470547
min       -0.347628
25%       33.983828
50%       80.657921
75%      123.810958
max      166.939779
Name: coord.inicial.y, dtype: float64

In [134]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [135]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [136]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [137]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,15.0,269.071460,144.500988,162.000000,135.036338
1,22.0,171.127447,253.068608,153.832610,81.204630
2,NaN,172.394224,NaN,153.774767,NaN
3,22.0,242.462688,263.099597,118.200310,69.746379
4,NaN,260.533489,NaN,110.380550,NaN
...,...,...,...,...,...
308,18.0,215.959985,188.132720,68.114774,136.793814
309,24.0,215.703239,254.858526,130.400173,135.223961
310,22.0,265.522234,262.667859,89.145778,72.008305
311,NaN,269.064919,NaN,70.161497,NaN
312,NaN,NaN,NaN,NaN,NaN

In [138]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0      269.0,162.0
1      171.0,154.0
2      172.0,154.0
3      242.0,118.0
4      261.0,110.0
          ...
308     216.0,68.0
309    216.0,130.0
310     266.0,89.0
311     269.0,70.0
312        nan,nan
Length: 313, dtype: object

In [139]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [140]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [141]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0         269,162     145,135
1         171,154      253,81
2         172,154        None
3         242,118      263,70
4         261,110        None
..            ...         ...
308        216,68     188,137
309       216,130     255,135
310        266,89      263,72
311        269,70        None
312          None        None

[313 rows x 2 columns]

# Escribir tabla filtros

In [142]:
data_eventos = data_eventos[~data_eventos['partido'].isna()].reset_index(drop=True)

In [143]:
data_eventos['partido'] = 'Central Cordoba'

In [144]:
data_eventos.tail()

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
307,2022/07/14,central cordoba,Central Cordoba,11:05:27,13:15:32,pase,NaN,02:00:22,02:00:22,0.0,...,0,0,0,0,0,17.0,195.600776,212.814335,72.686447,73.963984
308,2022/07/14,central cordoba,Central Cordoba,11:05:27,13:15:32,pase,NaN,02:00:24,02:00:24,0.0,...,0,0,0,0,0,18.0,215.959985,188.132720,68.114774,136.793814
309,2022/07/14,central cordoba,Central Cordoba,11:05:27,13:15:32,pase,NaN,02:00:27,02:00:27,0.0,...,0,0,0,0,0,24.0,215.703239,254.858526,130.400173,135.223961
310,2022/07/14,central cordoba,Central Cordoba,11:05:27,13:15:32,remate pie,NaN,00:47:12,00:47:12,0.0,...,0,0,0,0,0,22.0,265.522234,262.667859,89.145778,72.008305
311,2022/07/14,central cordoba,Central Cordoba,11:05:27,13:15:32,gol,NaN,00:47:12,00:47:12,0.0,...,0,0,0,0,0,NaN,269.064919,NaN,70.161497,NaN

In [145]:
data_eventos.to_csv("../Datos generados para la app/reserva02-22-fecha7_cco-tabla_filtros2.csv",index=False)