In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [77]:
data = pd.read_csv('../../datos etiquetas/Fecha 11 - Tigre/TIGREPPDP_TIGREETIQUETADO1.csv')
data

,Session Start Date,Event,Session Name,Session Start,Session End,Tag Description,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Zonas,Categoria,Jugador2,Jugador,Zonas_final,Optional Column
0,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,00:24:05,00:24:05,0.0,7,Balon afuera lateral,NaN,3,Volver,NaN
1,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,00:24:25,00:24:25,0.0,14,Duelo,NaN,11,Volver,NaN
2,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Recuperacion,NaN,00:24:36,00:24:36,0.0,10,Duelo,NaN,8,Volver,NaN
3,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,00:24:50,00:24:50,0.0,16,Interceptado,11.0,9,16,NaN
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Duelo,NaN,00:24:22,00:24:22,0.0,13,Disputa suelo,NaN,11,Volver,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Duelo,NaN,02:14:02,02:14:02,0.0,12,Gambeta a favor,NaN,23,Volver,NaN
220,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,02:14:11,02:14:11,0.0,21,Balon afuera fondo,NaN,23,Volver,NaN
221,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Duelo,NaN,02:14:46,02:14:46,0.0,4,Aereo,NaN,2,Volver,NaN
222,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Recuperacion,NaN,02:14:47,02:14:47,0.0,4,intercepcion anticipo aereo,NaN,2,Volver,NaN
223,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,02:14:52,02:14:52,0.0,1,Interceptado,20.0,3,13,NaN

In [78]:
data.columns = ['Session Start Date','partido','tiempo','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Optional Column']

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   224 non-null    object
 1   partido              224 non-null    object
 2   tiempo               224 non-null    object
 3   Session Start        224 non-null    object
 4   Session End          224 non-null    object
 5   Evento               224 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            224 non-null    object
 8   Tag End              224 non-null    object
 9   Tag Duration (secs)  224 non-null    float64
 10  coord inicial        224 non-null    int64
 11  Subevento            224 non-null    object
 12  Jugador 2            40 non-null     float64
 13  Jugador 1            224 non-null    int64
 14  coord final          224 non-null    object
 15  Optional Column      0 non-null      float64
dtypes: float64(4), int64(2), object(10)
memory usage: 28.1+ KB

In [80]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [81]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   224 non-null    object
 1   partido              224 non-null    object
 2   tiempo               224 non-null    object
 3   Session Start        224 non-null    object
 4   Session End          224 non-null    object
 5   Evento               224 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            224 non-null    object
 8   Tag End              224 non-null    object
 9   Tag Duration (secs)  224 non-null    float64
 10  coord inicial        224 non-null    float64
 11  Subevento            224 non-null    object
 12  Jugador 2            40 non-null     float64
 13  Jugador 1            224 non-null    float64
 14  coord final          224 non-null    object
 15  Optional Column      0 non-null      float64
 16  segundos             224 non-null    float64
dtypes: float64(7), object(10)
memory usage: 30.0+ KB

In [83]:
data

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Optional Column,segundos
0,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,00:24:05,00:24:05,0.0,7.0,Balon afuera lateral,NaN,3.0,Volver,NaN,1445.0
1,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,00:24:25,00:24:25,0.0,14.0,Duelo,NaN,11.0,Volver,NaN,1465.0
2,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Recuperacion,NaN,00:24:36,00:24:36,0.0,10.0,Duelo,NaN,8.0,Volver,NaN,1476.0
3,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,00:24:50,00:24:50,0.0,16.0,Interceptado,11.0,9.0,16,NaN,1490.0
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Duelo,NaN,00:24:22,00:24:22,0.0,13.0,Disputa suelo,NaN,11.0,Volver,NaN,1462.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,02:14:11,02:14:11,0.0,21.0,Balon afuera fondo,NaN,23.0,Volver,NaN,8051.0
221,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Duelo,NaN,02:14:46,02:14:46,0.0,4.0,Aereo,NaN,2.0,Volver,NaN,8086.0
222,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Recuperacion,NaN,02:14:47,02:14:47,0.0,4.0,intercepcion anticipo aereo,NaN,2.0,Volver,NaN,8087.0
223,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,Perdida,NaN,02:14:52,02:14:52,0.0,1.0,Interceptado,20.0,3.0,13,NaN,8092.0
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [85]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [86]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [87]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                                    cantidad
Jugador 1 Evento       Subevento
2.0       duelo        aereo                               2
          perdida      error tecnico                       1
                       intercepcion aereo                  1
                       interceptado                        1
          recuperacion intercepcion anticipo aereo         1
...                                                      ...
23.0      duelo        gambeta a favor                     3
          perdida      atajada                             1
                       balon afuera fondo                  1
                       duelo                               1
          recuperacion intercepcion anticipo               1

[109 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [88]:
data_eventos = data.copy()
data_eventos.shape

(225, 17)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [89]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
data_eventos.loc[data_eventos['remate-Gol'] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol]
Index: []

In [90]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Optional Column,segundos,remate-Gol,remate-Fuera
122,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:34:02,01:34:02,0.0,18.0,lateral corto,7.0,8.0,24,NaN,5642.0,0,1
166,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:53:53,01:53:53,0.0,24.0,tiro de esquina,NaN,8.0,Volver,NaN,6833.0,0,1

In [91]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco]
Index: []

In [92]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado]
Index: []

[0 rows x 21 columns]

In [93]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza]
Index: []

[0 rows x 22 columns]

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [94]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

Empty DataFrame
Columns: [cantidad]
Index: []

In [95]:
data[(data.Evento=='pase')]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos]
Index: []

In [96]:
data_eventos.head()

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 2,Jugador 1,coord final,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
0,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:05,00:24:05,0.0,...,NaN,3.0,Volver,NaN,1445.0,0,0,0,0,0
1,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:25,00:24:25,0.0,...,NaN,11.0,Volver,NaN,1465.0,0,0,0,0,0
2,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:24:36,00:24:36,0.0,...,NaN,8.0,Volver,NaN,1476.0,0,0,0,0,0
3,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:50,00:24:50,0.0,...,11.0,9.0,16,NaN,1490.0,0,0,0,0,0
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:22,00:24:22,0.0,...,NaN,11.0,Volver,NaN,1462.0,0,0,0,0,0

In [97]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''
colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia]
Index: []

[0 rows x 23 columns]

In [98]:
##completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='centro aereo') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='bloqueado'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) | (data_eventos.loc[i+1,'Subevento'] == 'offside' ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado]
Index: []

[0 rows x 24 columns]

In [99]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

Series([], Name: Subevento, dtype: int64)

In [100]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado]
Index: []

[0 rows x 25 columns]

In [101]:
#fuera
'''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

colname = 'pase-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera]
Index: []

[0 rows x 26 columns]

In [102]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente]
Index: []

[0 rows x 27 columns]

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [103]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [104]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 28 columns]

In [105]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado]
Index: []

[0 rows x 29 columns]

In [106]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado]
Index: []

[0 rows x 30 columns]

In [107]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 31 columns]

In [108]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 32 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [109]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [110]:
dejar_index= []
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo'):
        dejar_index.append(i-1)
        dejar_index.append(i)
        dejar_index.append(i+1)
data_eventos.loc[dejar_index].head(100)

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera
3,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:50,00:24:50,0.0,...,0,0,0,0,0,0,0,0,0,0
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:22,00:24:22,0.0,...,0,0,0,0,0,0,0,0,0,0
5,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:35,00:24:35,0.0,...,0,0,0,0,0,0,0,0,0,0
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:22,00:24:22,0.0,...,0,0,0,0,0,0,0,0,0,0
5,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:35,00:24:35,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:56:54,00:56:54,0.0,...,0,0,0,0,0,0,0,0,0,0
80,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:55:22,00:55:22,0.0,...,0,0,0,0,0,0,0,0,0,0
81,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:56:54,00:56:54,0.0,...,0,0,0,0,0,0,0,0,0,0
82,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:56:55,00:56:55,0.0,...,0,0,0,0,0,0,0,0,0,0
83,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:57:27,00:57:27,0.0,...,0,0,0,0,0,0,0,0,0,0

In [111]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1


data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
26,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:31:36,00:31:36,0.0,...,0,0,0,0,0,0,0,0,0,1
49,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:42:12,00:42:12,0.0,...,0,0,0,0,0,0,0,0,0,1
51,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:43:13,00:43:13,0.0,...,0,0,0,0,0,0,0,0,0,1
55,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:46:03,00:46:03,0.0,...,0,0,0,0,0,0,0,0,0,1
60,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:48:08,00:48:08,0.0,...,0,0,0,0,0,0,0,0,0,1
65,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:51:08,00:51:08,0.0,...,0,0,0,0,0,0,0,0,0,1
72,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:51:49,00:51:49,0.0,...,0,0,0,0,0,0,0,0,0,1
81,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:56:54,00:56:54,0.0,...,0,0,0,0,0,0,0,0,0,1
89,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:01:45,01:01:45,0.0,...,0,0,0,0,0,0,0,0,0,1
117,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:33:26,01:33:26,0.0,...,0,0,0,0,0,0,0,0,0,1
124,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:35:21,01:35:21,0.0,...,0,0,0,0,0,0,0,0,0,1
138,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:39:06,01:39:06,0.0,...,0,0,0,0,0,0,0,0,0,1
151,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:43:17,01:43:17,0.0,...,0,0,0,0,0,0,0,0,0,1
155,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:45:11,01:45:11,0.0,...,0,0,0,0,0,0,0,0,0,1
212,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:11:35,02:11:35,0.0,...,0,0,0,0,0,0,0,0,0,1
221,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:14:46,02:14:46,0.0,...,0,0,0,0,0,0,0,0,0,1

In [112]:
data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
28,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:32:31,00:32:31,0.0,...,0,0,0,0,0,0,0,0,1,0
197,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:06:02,02:06:02,0.0,...,0,0,0,0,0,0,0,0,1,0

In [113]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
13,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:27:16,00:27:16,0.0,...,0,0,0,0,0,0,0,0,1,0
15,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:28:12,00:28:12,0.0,...,0,0,0,0,0,0,0,0,1,0
31,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:34:04,00:34:04,0.0,...,0,0,0,0,0,0,0,0,1,0
34,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:35:29,00:35:29,0.0,...,0,0,0,0,0,0,0,0,1,0
38,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:36:54,00:36:54,0.0,...,0,0,0,0,0,0,0,0,1,0
42,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:38:14,00:38:14,0.0,...,0,0,0,0,0,0,0,0,1,0
44,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:39:28,00:39:28,0.0,...,0,0,0,0,0,0,0,0,1,0
47,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:41:40,00:41:40,0.0,...,0,0,0,0,0,0,0,0,1,0
56,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:46:27,00:46:27,0.0,...,0,0,0,0,0,0,0,0,1,0
67,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:51:18,00:51:18,0.0,...,0,0,0,0,0,0,0,0,1,0
91,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:02:02,01:02:02,0.0,...,0,0,0,0,0,0,0,0,1,0
108,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:30:37,01:30:37,0.0,...,0,0,0,0,0,0,0,0,1,0
183,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:02:13,02:02:13,0.0,...,0,0,0,0,0,0,0,0,1,0
188,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:02:41,02:02:41,0.0,...,0,0,0,0,0,0,0,0,1,0
207,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:09:30,02:09:30,0.0,...,0,0,0,0,0,0,0,0,1,0
217,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:13:40,02:13:40,0.0,...,0,0,0,0,0,0,0,0,1,0

In [114]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:22,00:24:22,0.0,...,0,0,0,0,0,0,0,0,0,1
5,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:35,00:24:35,0.0,...,0,0,0,0,0,0,0,0,0,1
6,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:25:06,00:25:06,0.0,...,0,0,0,0,0,0,0,0,0,1
8,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:25:43,00:25:43,0.0,...,0,0,0,0,0,0,0,0,0,1
19,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:29:13,00:29:13,0.0,...,0,0,0,0,0,0,0,0,0,1
22,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:30:01,00:30:01,0.0,...,0,0,0,0,0,0,0,0,0,1
40,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:37:18,00:37:18,0.0,...,0,0,0,0,0,0,0,0,0,1
58,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:47:53,00:47:53,0.0,...,0,0,0,0,0,0,0,0,0,1
69,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:51:27,00:51:27,0.0,...,0,0,0,0,0,0,0,0,0,1
78,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:54:57,00:54:57,0.0,...,0,0,0,0,0,0,0,0,0,1
85,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:59:16,00:59:16,0.0,...,0,0,0,0,0,0,0,0,0,1
94,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:06:49,01:06:49,0.0,...,0,0,0,0,0,0,0,0,0,1
98,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:08:39,01:08:39,0.0,...,0,0,0,0,0,0,0,0,0,1
110,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:31:02,01:31:02,0.0,...,0,0,0,0,0,0,0,0,0,1
113,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:31:25,01:31:25,0.0,...,0,0,0,0,0,0,0,0,0,1
120,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:33:38,01:33:38,0.0,...,0,0,0,0,0,0,0,0,0,1
126,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:35:55,01:35:55,0.0,...,0,0,0,0,0,0,0,0,0,1
132,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:36:55,01:36:55,0.0,...,0,0,0,0,0,0,0,0,0,1
142,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:40:12,01:40:12,0.0,...,0,0,0,0,0,0,0,0,0,1
145,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:40:30,01:40:30,0.0,...,0,0,0,0,0,0,0,0,0,1
157,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:47:09,01:47:09,0.0,...,0,0,0,0,0,0,0,0,0,1
161,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:49:36,01:49:36,0.0,...,0,0,0,0,0,0,0,0,0,1
170,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:56:08,01:56:08,0.0,...,0,0,0,0,0,0,0,0,0,1
173,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:57:25,01:57:25,0.0,...,0,0,0,0,0,0,0,0,0,1
177,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:59:16,01:59:16,0.0,...,0,0,0,0,0,0,0,0,0,1
186,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:02:34,02:02:34,0.0,...,0,0,0,0,0,0,0,0,0,1
190,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:03:03,02:03:03,0.0,...,0,0,0,0,0,0,0,0,0,1
194,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:04:12,02:04:12,0.0,...,0,0,0,0,0,0,0,0,0,1
200,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:07:59,02:07:59,0.0,...,0,0,0,0,0,0,0,0,0,1
203,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:08:47,02:08:47,0.0,...,0,0,0,0,0,0,0,0,0,1

In [115]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [116]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [117]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada
134,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:36:58,01:36:58,0.0,...,0,0,0,0,0,0,0,0,1,0
149,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:42:42,01:42:42,0.0,...,0,0,0,0,0,0,0,0,1,0
205,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:08:52,02:08:52,0.0,...,0,0,0,0,0,0,0,0,1,0
219,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:14:02,02:14:02,0.0,...,0,0,0,0,0,0,0,0,1,0

In [118]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada
17,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:28:56,00:28:56,0.0,...,0,0,0,0,0,0,0,0,0,1
36,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:36:24,00:36:24,0.0,...,0,0,0,0,0,0,0,0,0,1
66,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:51:13,00:51:13,0.0,...,0,0,0,0,0,0,0,0,0,1
80,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:55:22,00:55:22,0.0,...,0,0,0,0,0,0,0,0,0,1
84,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:59:00,00:59:00,0.0,...,0,0,0,0,0,0,0,0,0,1
93,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:02:42,01:02:42,0.0,...,0,0,0,0,0,0,0,0,0,1
106,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:30:07,01:30:07,0.0,...,0,0,0,0,0,0,0,0,0,1
116,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:32:49,01:32:49,0.0,...,0,0,0,0,0,0,0,0,0,1
128,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:35:58,01:35:58,0.0,...,0,0,0,0,0,0,0,0,0,1
140,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:39:16,01:39:16,0.0,...,0,0,0,0,0,0,0,0,0,1
153,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:43:20,01:43:20,0.0,...,0,0,0,0,0,0,0,0,0,1
163,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:49:40,01:49:40,0.0,...,0,0,0,0,0,0,0,0,0,1
165,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:52:03,01:52:03,0.0,...,0,0,0,0,0,0,0,0,0,1
172,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:57:02,01:57:02,0.0,...,0,0,0,0,0,0,0,0,0,1
179,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:59:26,01:59:26,0.0,...,0,0,0,0,0,0,0,0,0,1
180,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:59:36,01:59:36,0.0,...,0,0,0,0,0,0,0,0,0,1

In [119]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 42 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [120]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [121]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida]
Index: []

[0 rows x 43 columns]

In [122]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida]
Index: []

[0 rows x 44 columns]

In [123]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 45 columns]

In [124]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 46 columns]

In [125]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside]
Index: []

[0 rows x 47 columns]

In [126]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla]
Index: []

[0 rows x 48 columns]

In [127]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja]
Index: []

[0 rows x 49 columns]

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [128]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [129]:
colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo
41,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:37:22,00:37:22,0.0,...,0,0,0,0,0,0,0,0,0,1
79,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:54:59,00:54:59,0.0,...,0,0,0,0,0,0,0,0,0,1
86,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:59:17,00:59:17,0.0,...,0,0,0,0,0,0,0,0,0,1
95,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:06:50,01:06:50,0.0,...,0,0,0,0,0,0,0,0,0,1
99,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:08:40,01:08:40,0.0,...,0,0,0,0,0,0,0,0,0,1
111,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:31:03,01:31:03,0.0,...,0,0,0,0,0,0,0,0,0,1
114,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:31:26,01:31:26,0.0,...,0,0,0,0,0,0,0,0,0,1
121,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:33:39,01:33:39,0.0,...,0,0,0,0,0,0,0,0,0,1
127,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:35:56,01:35:56,0.0,...,0,0,0,0,0,0,0,0,0,1
133,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:36:56,01:36:56,0.0,...,0,0,0,0,0,0,0,0,0,1
158,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:47:11,01:47:11,0.0,...,0,0,0,0,0,0,0,0,0,1
162,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:49:37,01:49:37,0.0,...,0,0,0,0,0,0,0,0,0,1
171,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:56:09,01:56:09,0.0,...,0,0,0,0,0,0,0,0,0,1
187,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:02:35,02:02:35,0.0,...,0,0,0,0,0,0,0,0,0,1
191,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:03:04,02:03:04,0.0,...,0,0,0,0,0,0,0,0,0,1
195,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:04:12,02:04:12,0.0,...,0,0,0,0,0,0,0,0,0,1
201,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:08:00,02:08:00,0.0,...,0,0,0,0,0,0,0,0,0,1

In [130]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada]
Index: []

[0 rows x 51 columns]

In [131]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo
178,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:59:17,01:59:17,0.0,...,0,0,0,0,0,0,0,0,0,1

In [132]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo
82,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:56:55,00:56:55,0.0,...,0,0,0,0,0,0,0,0,0,1
118,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:33:26,01:33:26,0.0,...,0,0,0,0,0,0,0,0,0,1
139,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:39:07,01:39:07,0.0,...,0,0,0,0,0,0,0,0,0,1
152,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:43:18,01:43:18,0.0,...,0,0,0,0,0,0,0,0,0,1

In [133]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo
143,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:40:14,01:40:14,0.0,...,0,0,0,0,0,0,0,0,0,1
174,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,01:57:26,01:57:26,0.0,...,0,0,0,0,0,0,0,0,0,1
204,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:08:48,02:08:48,0.0,...,0,0,0,0,0,0,0,0,0,1
222,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:14:47,02:14:47,0.0,...,0,0,0,0,0,0,0,0,0,1

In [134]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if (data_eventos.loc[i+1,'Evento'] == 'recuperacion') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo
6,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:25:06,00:25:06,0.0,...,0,0,0,0,0,0,0,0,0,1
58,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:47:53,00:47:53,0.0,...,0,0,0,0,0,0,0,0,0,1
69,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:51:27,00:51:27,0.0,...,0,0,0,0,0,0,0,0,0,1
145,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,01:40:30,01:40:30,0.0,...,0,0,0,0,0,0,0,0,0,1

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [135]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [136]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
182,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,02:02:01,02:02:01,0.0,...,0,0,0,0,0,0,0,0,1,0
216,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,02:13:36,02:13:36,0.0,...,0,0,0,0,0,0,0,0,1,0

In [137]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
10,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,00:26:22,00:26:22,0.0,...,0,0,0,0,0,0,0,0,0,1
21,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,00:29:33,00:29:33,0.0,...,0,0,0,0,0,0,0,0,0,1
53,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,00:45:06,00:45:06,0.0,...,0,0,0,0,0,0,0,0,0,1
61,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,00:48:58,00:48:58,0.0,...,0,0,0,0,0,0,0,0,0,1
97,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:08:29,01:08:29,0.0,...,0,0,0,0,0,0,0,0,0,1
101,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:09:20,01:09:20,0.0,...,0,0,0,0,0,0,0,0,0,1
103,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:29:25,01:29:25,0.0,...,0,0,0,0,0,0,0,0,0,1
104,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:29:50,01:29:50,0.0,...,0,0,0,0,0,0,0,0,0,1
122,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:34:02,01:34:02,0.0,...,0,0,0,0,0,0,0,0,0,1
130,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:36:41,01:36:41,0.0,...,0,0,0,0,0,0,0,0,0,1
136,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:37:55,01:37:55,0.0,...,0,0,0,0,0,0,0,0,0,1
148,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:42:20,01:42:20,0.0,...,0,0,0,0,0,0,0,0,0,1
159,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:47:40,01:47:40,0.0,...,0,0,0,0,0,0,0,0,0,1
160,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:48:24,01:48:24,0.0,...,0,0,0,0,0,0,0,0,0,1
211,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,02:11:32,02:11:32,0.0,...,0,0,0,0,0,0,0,0,0,1
214,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,02:12:23,02:12:23,0.0,...,0,0,0,0,0,0,0,0,0,1
215,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,02:12:49,02:12:49,0.0,...,0,0,0,0,0,0,0,0,0,1

In [138]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado
62,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,00:50:19,00:50:19,0.0,...,0,0,0,0,0,0,0,0,1,0

In [139]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado
156,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:46:08,01:46:08,0.0,...,0,0,0,0,0,0,0,0,0,1
164,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:50:34,01:50:34,0.0,...,0,0,0,0,0,0,0,0,0,1
166,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:53:53,01:53:53,0.0,...,0,0,0,0,0,0,0,0,0,1
169,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:56:02,01:56:02,0.0,...,0,0,0,0,0,0,0,0,0,1
181,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,02:00:21,02:00:21,0.0,...,0,0,0,0,0,0,0,0,0,1

In [140]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
192,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,02:03:58,02:03:58,0.0,...,0,0,0,0,0,0,0,0,1,0

In [141]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
96,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:08:05,01:08:05,0.0,...,0,0,0,0,0,0,0,0,0,1
115,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:32:39,01:32:39,0.0,...,0,0,0,0,0,0,0,0,0,1
168,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,pelota parada,NaN,01:55:23,01:55:23,0.0,...,0,0,0,0,0,0,0,0,0,1

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [142]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [143]:
#gambeta a favor

colname = 'perdida-Gambeta-favor'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor
205,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:08:52,02:08:52,0.0,...,0,0,0,0,0,0,0,0,0,1

In [144]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='robo'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo
100,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:08:45,01:08:45,0.0,...,0,0,0,0,0,0,0,0,0,1

In [145]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion
3,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:50,00:24:50,0.0,...,0,0,0,0,0,0,0,0,0,1
9,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:25:54,00:25:54,0.0,...,0,0,0,0,0,0,0,0,0,1
11,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:26:26,00:26:26,0.0,...,0,0,0,0,0,0,0,0,0,1
18,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:29:00,00:29:00,0.0,...,0,0,0,0,0,0,0,0,0,1
24,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:30:45,00:30:45,0.0,...,0,0,0,0,0,0,0,0,0,1
25,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:31:36,00:31:36,0.0,...,0,0,0,0,0,0,0,0,0,1
50,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:42:13,00:42:13,0.0,...,0,0,0,0,0,0,0,0,0,1
52,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:43:14,00:43:14,0.0,...,0,0,0,0,0,0,0,0,0,1
63,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:50:37,00:50:37,0.0,...,0,0,0,0,0,0,0,0,0,1
71,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:51:35,00:51:35,0.0,...,0,0,0,0,0,0,0,0,0,1
74,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:51:53,00:51:53,0.0,...,0,0,0,0,0,0,0,0,0,1
87,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:00:01,01:00:01,0.0,...,0,0,0,0,0,0,0,0,0,1
90,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:01:47,01:01:47,0.0,...,0,0,0,0,0,0,0,0,0,1
105,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:29:51,01:29:51,0.0,...,0,0,0,0,0,0,0,0,0,1
112,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:31:12,01:31:12,0.0,...,0,0,0,0,0,0,0,0,0,1
119,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:33:29,01:33:29,0.0,...,0,0,0,0,0,0,0,0,0,1
125,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:35:42,01:35:42,0.0,...,0,0,0,0,0,0,0,0,0,1
131,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:36:50,01:36:50,0.0,...,0,0,0,0,0,0,0,0,0,1
137,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:38:30,01:38:30,0.0,...,0,0,0,0,0,0,0,0,0,1
144,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:40:16,01:40:16,0.0,...,0,0,0,0,0,0,0,0,0,1
193,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:03:59,02:03:59,0.0,...,0,0,0,0,0,0,0,0,0,1
202,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:08:01,02:08:01,0.0,...,0,0,0,0,0,0,0,0,0,1
209,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:10:15,02:10:15,0.0,...,0,0,0,0,0,0,0,0,0,1
210,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:10:15,02:10:15,0.0,...,0,0,0,0,0,0,0,0,0,1
223,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:14:52,02:14:52,0.0,...,0,0,0,0,0,0,0,0,0,1

In [146]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico
30,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:33:06,00:33:06,0.0,...,0,0,0,0,0,0,0,0,0,1
33,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:35:06,00:35:06,0.0,...,0,0,0,0,0,0,0,0,0,1
46,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:40:33,00:40:33,0.0,...,0,0,0,0,0,0,0,0,0,1
54,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:45:32,00:45:32,0.0,...,0,0,0,0,0,0,0,0,0,1
107,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:30:19,01:30:19,0.0,...,0,0,0,0,0,0,0,0,0,1
141,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:39:45,01:39:45,0.0,...,0,0,0,0,0,0,0,0,0,1
154,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:43:33,01:43:33,0.0,...,0,0,0,0,0,0,0,0,0,1
196,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:04:17,02:04:17,0.0,...,0,0,0,0,0,0,0,0,0,1
199,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:07:09,02:07:09,0.0,...,0,0,0,0,0,0,0,0,0,1

In [147]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera
0,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:05,00:24:05,0.0,...,0,0,0,0,0,0,0,0,0,1
20,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:29:14,00:29:14,0.0,...,0,0,0,0,0,0,0,0,0,1
23,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:30:02,00:30:02,0.0,...,0,0,0,0,0,0,0,0,0,1
27,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:31:56,00:31:56,0.0,...,0,0,0,0,0,0,0,0,0,1
64,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:50:46,00:50:46,0.0,...,0,0,0,0,0,0,0,0,0,1
76,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:52:54,00:52:54,0.0,...,0,0,0,0,0,0,0,0,0,1
77,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:54:30,00:54:30,0.0,...,0,0,0,0,0,0,0,0,0,1
83,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:57:27,00:57:27,0.0,...,0,0,0,0,0,0,0,0,0,1
88,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:01:18,01:01:18,0.0,...,0,0,0,0,0,0,0,0,0,1
123,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:34:36,01:34:36,0.0,...,0,0,0,0,0,0,0,0,0,1
135,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:37:08,01:37:08,0.0,...,0,0,0,0,0,0,0,0,0,1
147,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:40:33,01:40:33,0.0,...,0,0,0,0,0,0,0,0,0,1
150,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:42:50,01:42:50,0.0,...,0,0,0,0,0,0,0,0,0,1
167,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:54:00,01:54:00,0.0,...,0,0,0,0,0,0,0,0,0,1
175,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:57:39,01:57:39,0.0,...,0,0,0,0,0,0,0,0,0,1
176,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:59:01,01:59:01,0.0,...,0,0,0,0,0,0,0,0,0,1
213,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:11:36,02:11:36,0.0,...,0,0,0,0,0,0,0,0,0,1
220,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:14:11,02:14:11,0.0,...,0,0,0,0,0,0,0,0,0,1

In [148]:
#situacion rival

colname = 'perdida-Situacion-rival'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='situacion rival'):
        if (data_eventos.loc[i,'Subevento']=='directa'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival]
Index: []

[0 rows x 67 columns]

In [149]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='atajada'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Situacion-rival,perdida-Atajada
12,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:26:45,00:26:45,0.0,...,0,0,0,0,0,0,0,0,0,1
37,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:36:32,00:36:32,0.0,...,0,0,0,0,0,0,0,0,0,1
129,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,01:36:04,01:36:04,0.0,...,0,0,0,0,0,0,0,0,0,1
185,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:02:18,02:02:18,0.0,...,0,0,0,0,0,0,0,0,0,1

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [150]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [151]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable]
Index: []

[0 rows x 70 columns]

In [152]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in data_eventos.loc[i,'Subevento']) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            if ('remate' in data_eventos.loc[i-1,'Evento']):
                data_eventos.loc[i-1,colname] = 1
            elif ('remate' in data_eventos.loc[i-2,'Evento']):
                data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada]
Index: []

[0 rows x 71 columns]

In [153]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [154]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 72 columns]

In [155]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 73 columns]

In [156]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 74 columns]

In [157]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano]
Index: []

[0 rows x 75 columns]

In [158]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie]
Index: []

[0 rows x 76 columns]

In [159]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 77 columns]

In [160]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [161]:
data_eventos.iloc[:,:20]

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),coord.inicial,Subevento,Jugador.2,Jugador.1,coord.final,Optional.Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco
0,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:05,00:24:05,0.0,7.0,balon afuera lateral,NaN,3.0,Volver,NaN,1445.0,0,0,0
1,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:25,00:24:25,0.0,14.0,duelo,NaN,11.0,Volver,NaN,1465.0,0,0,0
2,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,00:24:36,00:24:36,0.0,10.0,duelo,NaN,8.0,Volver,NaN,1476.0,0,0,0
3,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,00:24:50,00:24:50,0.0,16.0,interceptado,11.0,9.0,16,NaN,1490.0,0,0,0
4,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,00:24:22,00:24:22,0.0,13.0,disputa suelo,NaN,11.0,Volver,NaN,1462.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:14:11,02:14:11,0.0,21.0,balon afuera fondo,NaN,23.0,Volver,NaN,8051.0,0,0,0
221,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:14:46,02:14:46,0.0,4.0,aereo,NaN,2.0,Volver,NaN,8086.0,0,0,0
222,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:14:47,02:14:47,0.0,4.0,intercepcion anticipo aereo,NaN,2.0,Volver,NaN,8087.0,0,0,0
223,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:14:52,02:14:52,0.0,1.0,interceptado,20.0,3.0,13,NaN,8092.0,0,0,0
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [162]:
data_eventos['coord.inicial'].value_counts()

14.0    25
10.0    24
18.0    20
8.0     20
24.0    16
11.0    16
17.0    15
13.0    14
19.0    11
15.0     9
9.0      9
1.0      8
7.0      7
21.0     7
16.0     7
12.0     5
23.0     4
2.0      2
6.0      2
4.0      2
20.0     1
Name: coord.inicial, dtype: int64

In [163]:
data_eventos['coord.final'].value_counts()

Volver    184
18          8
21          6
17          6
16          4
13          4
14          3
23          2
15          2
19          1
1           1
24          1
12          1
10          1
Name: coord.final, dtype: int64

In [164]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [165]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [166]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [167]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,NaN,68.0,NaN,22.0,NaN
1,NaN,161.0,NaN,81.0,NaN
2,NaN,109.0,NaN,22.0,NaN
3,16.0,205.0,205.0,23.0,23.0
4,NaN,162.0,NaN,21.0,NaN
...,...,...,...,...,...
220,NaN,238.0,NaN,80.0,NaN
221,NaN,33.0,NaN,83.0,NaN
222,NaN,33.0,NaN,83.0,NaN
223,13.0,22.0,162.0,18.0,21.0
224,NaN,NaN,NaN,NaN,NaN

In [168]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    224.000000
mean     149.660714
std       68.920641
min       20.000000
25%      108.000000
50%      161.000000
75%      203.000000
max      251.000000
Name: coord.inicial.x, dtype: float64

In [169]:
# aÃ±adirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    224.000000
mean     149.544475
std       70.747761
min        2.476111
25%       95.964459
50%      157.100274
75%      209.766261
max      269.866098
Name: coord.inicial.x, dtype: float64

In [170]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [171]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    224.000000
mean      78.991071
std       47.170428
min       18.000000
25%       22.000000
50%       81.000000
75%      138.750000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [172]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    224.000000
mean      78.455438
std       49.072206
min        1.774965
25%       32.124597
50%       80.153242
75%      127.480862
max      164.836659
Name: coord.inicial.y, dtype: float64

In [173]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [174]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [175]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [176]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,NaN,49.295863,NaN,5.407594,NaN
1,NaN,178.951017,NaN,64.437918,NaN
2,NaN,101.810577,NaN,5.066415,NaN
3,16.0,205.841514,214.794418,8.485152,27.478753
4,NaN,161.987191,NaN,38.155945,NaN
...,...,...,...,...,...
220,NaN,249.759303,NaN,82.223169,NaN
221,NaN,17.041811,NaN,72.829759,NaN
222,NaN,26.155316,NaN,79.198215,NaN
223,13.0,23.304864,164.272478,27.514303,11.574564
224,NaN,NaN,NaN,NaN,NaN

In [177]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0        49.0,5.0
1      179.0,64.0
2       102.0,5.0
3       206.0,8.0
4      162.0,38.0
          ...
220    250.0,82.0
221     17.0,73.0
222     26.0,79.0
223     23.0,28.0
224       nan,nan
Length: 225, dtype: object

In [178]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [179]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [180]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0            49,5        None
1          179,64        None
2           102,5        None
3           206,8      215,27
4          162,38        None
..            ...         ...
220        250,82        None
221         17,73        None
222         26,79        None
223         23,28      164,12
224          None        None

[225 rows x 2 columns]

# Escribir tabla filtros

In [181]:
data_eventos = data_eventos[~data_eventos['partido'].isna()].reset_index(drop=True)

In [182]:
data_eventos.tail()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
219,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:14:02,02:14:02,0.0,...,0,0,0,0,0,NaN,99.863459,NaN,144.813792,NaN
220,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:14:11,02:14:11,0.0,...,0,0,0,0,0,NaN,249.759303,NaN,82.223169,NaN
221,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,duelo,NaN,02:14:46,02:14:46,0.0,...,0,0,0,0,0,NaN,17.041811,NaN,72.829759,NaN
222,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,recuperacion,NaN,02:14:47,02:14:47,0.0,...,0,0,0,0,0,NaN,26.155316,NaN,79.198215,NaN
223,2022/04/20,TIGREPPDP,TIGREETIQUETADO1,15:41:13,18:05:36,perdida,NaN,02:14:52,02:14:52,0.0,...,0,0,0,0,0,13.0,23.304864,164.272478,27.514303,11.574564

In [183]:
data_eventos.to_csv("../Datos generados para la app/reserva22-fecha11-tigre-tabla_filtros.csv",index=False)

In [184]:
data_eventos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 82 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Session.Start.Date                  224 non-null    object
 1   partido                             224 non-null    object
 2   tiempo                              224 non-null    object
 3   Session.Start                       224 non-null    object
 4   Session.End                         224 non-null    object
 5   Evento                              224 non-null    object
 6   Tag.Notes                           0 non-null      float64
 7   Tag.Start                           224 non-null    object
 8   Tag.End                             224 non-null    object
 9   Tag.Duration.(secs)                 224 non-null    float64
 10  coord.inicial                       224 non-null    object
 11  Subevento                           224 non-null    object
 12  Jugador.2                           40 non-null     float64
 13  Jugador.1                           224 non-null    float64
 14  coord.final                         40 non-null     object
 15  Optional.Column                     0 non-null      float64
 16  segundos                            224 non-null    float64
 17  remate-Gol                          224 non-null    int64
 18  remate-Fuera                        224 non-null    int64
 19  remate-Al-arco                      224 non-null    int64
 20  remate-Interceptado                 224 non-null    int64
 21  remate-Cabeza                       224 non-null    int64
 22  pase-Asistencia                     224 non-null    int64
 23  pase-Completado                     224 non-null    int64
 24  pase-Interceptado                   224 non-null    int64
 25  pase-Fuera                          224 non-null    int64
 26  pase-Inteligente                    224 non-null    int64
 27  centro-Asistencia                   224 non-null    int64
 28  centro-Completado                   224 non-null    int64
 29  centro-Interceptado                 224 non-null    int64
 30  centro-Bloqueado                    224 non-null    int64
 31  centro-Fuera                        224 non-null    int64
 32  duelo-Aereo-Perdido                 224 non-null    int64
 33  duelo-Aereo-Ganado                  224 non-null    int64
 34  duelo-Disputa-suelo-Perdida         224 non-null    int64
 35  duelo-Disputa-suelo-Ganada          224 non-null    int64
 36  duelo-Gambeta-contra-Ganada         224 non-null    int64
 37  duelo-Gambeta-contra-Perdida        224 non-null    int64
 38  duelo-Gambeta-favor-Perdida         224 non-null    int64
 39  duelo-Gambeta-favor-Ganada          224 non-null    int64
 40  duelo-Pivote-Perdido                224 non-null    int64
 41  duelo-Pivote-Ganado                 224 non-null    int64
 42  falta-Cometida                      224 non-null    int64
 43  falta-Recibida                      224 non-null    int64
 44  falta-Penal-cometido                224 non-null    int64
 45  falta-Penal-recibido                224 non-null    int64
 46  falta-Offside                       224 non-null    int64
 47  falta-Tarjeta-amarilla              224 non-null    int64
 48  falta-Tarjeta-roja                  224 non-null    int64
 49  recuperacion-Robo                   224 non-null    int64
 50  recuperacion-Encontrada             224 non-null    int64
 51  recuperacion-Intercepcion-suelo     224 non-null    int64
 52  recuperacion-Intercepcion-aereo     224 non-null    int64
 53  recuperacion-Intercepcion-anticipo  224 non-null    int64
 54  recuperacion-Disputa-suelo          224 non-null    int64
 55  parado-Lateral-interceptado         224 non-null    int64
 56  parado-Lateral-completado           224 non-null    int64
 57  parado-Corner-interceptado          224 non-null    int64
 58  parado-Corner-completado            224 non-null    int64
 59  parado-Tiro-libre-incompleto        224 non-null    int64
 60  parado-Tiro-libre-completado        224 non-null    int64
 61  perdida-Gambeta-favor               224 non-null    int64
 62  perdida-Robo                        224 non-null    int64
 63  perdida-Intercepcion                224 non-null    int64
 64  perdida-Error-tecnico               224 non-null    int64
 65  perdida-Balon-fuera                 224 non-null    int64
 66  perdida-Situacion-rival             224 non-null    int64
 67  perdida-Atajada                     224 non-null    int64
 68  arquero-Gol-rival                   224 non-null    int64
 69  arquero-Gol-rival-atajable          224 non-null    int64
 70  arquero-Atajada                     224 non-null    int64
 71  arquero-Intercepcion-aerea          224 non-null    int64
 72  arquero-Intercepcion                224 non-null    int64
 73  arquero-Anticipo                    224 non-null    int64
 74  arquero-Saque-mano                  224 non-null    int64
 75  arquero-Saque-pie                   224 non-null    int64
 76  arquero-Saque-meta                  224 non-null    int64
 77  coord.final.num                     40 non-null     float64
 78  coord.inicial.x                     224 non-null    float64
 79  coord.final.x                       40 non-null     float64
 80  coord.inicial.y                     224 non-null    float64
 81  coord.final.y                       40 non-null     float64
dtypes: float64(11), int64(60), object(11)
memory usage: 143.6+ KB

In [ ]:
data_eventos[[col for col in data_eventos.columns if 'perdida' in col]].sum()

In [ ]:
data_eventos[data_eventos['Jugador.1']==3][['Jugador.1','coord.inicial','coord.final','Subevento']+[col for col in data_eventos.columns if 'perdida' in col]]

# Agregar

ARQUERO
- que siempre que hay una atajada haya un remate antes para saber desde donde proviene
- que el remate antes de gol o atajada tenga coord inicio y final
- agregar rebote
- ver como poner los mano a mano
- INTERCEPCIONES (poner antes de donde proviene del rival)

In [ ]:
data_eventos.info()

In [ ]:
data_eventos.iloc[:,12:].apply(lambda x: x.sum(), axis='rows')