In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [21]:
os.getcwd()

'd:\\BigData Pincha\\Data_Pincha\\procesamiento de etiquetas\\notebooks partidos'

In [22]:
data = pd.read_csv('../../datos etiquetas/Fecha 5 - Velez/COMPLETOVELEZ3_VELEZ RESERVA.csv')
data

,Session Start Date,Event,Session Name,Session Start,Session End,Tag Description,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Zonas,Categoria,Jugador2,Jugador,Zonas_final,Calificacion,Dificultad,Optional Column
0,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Perdida,NaN,00:19:52,00:19:58,6.0,7,Interceptado,Rival,1,7,NaN,NaN,NaN
1,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,00:19:45,00:19:45,0.0,11,corto,5,9,11,NaN,NaN,NaN
2,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,00:19:48,00:19:48,0.0,11,medio,2,5,8,NaN,NaN,NaN
3,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,00:19:51,00:19:51,0.0,8,medio,1,2,3,NaN,NaN,NaN
4,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Recuperacion,NaN,00:20:41,00:20:41,0.0,2,Intercepcion,NaN,2,Volver,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Pelota parada,NaN,02:28:37,02:28:37,0.0,12,Lateral largo,9,4,18,NaN,NaN,NaN
485,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,02:28:36,02:28:36,0.0,18,corto,18,9,14,NaN,NaN,NaN
486,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Falta,NaN,02:28:42,02:28:42,0.0,17,Recibida,NaN,18,Volver,NaN,NaN,NaN
487,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Pelota parada,NaN,02:29:29,02:29:29,0.0,17,Tiro libre,NaN,18,Volver,NaN,NaN,NaN
488,2022/04/05,COMPLETOVELEZ3,VELEZ RESERVA,20:18:22,22:53:32,Perdida,NaN,02:29:30,02:29:30,0.0,17,Interceptado,NaN,18,Volver,NaN,NaN,NaN

In [23]:
data.columns = ['Session Start Date','partido','tiempo','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Calificaciondelevento','Dificultad','Optional Column']

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Session Start Date     489 non-null    object
 1   partido                489 non-null    object
 2   tiempo                 489 non-null    object
 3   Session Start          489 non-null    object
 4   Session End            489 non-null    object
 5   Evento                 489 non-null    object
 6   Tag Notes              0 non-null      float64
 7   Tag Start              489 non-null    object
 8   Tag End                489 non-null    object
 9   Tag Duration (secs)    489 non-null    float64
 10  coord inicial          489 non-null    int64
 11  Subevento              487 non-null    object
 12  Jugador 2              272 non-null    object
 13  Jugador 1              489 non-null    int64
 14  coord final            486 non-null    object
 15  Calificaciondelevento  2 non-null      object
 16  Dificultad             2 non-null      object
 17  Optional Column        0 non-null      float64
dtypes: float64(3), int64(2), object(13)
memory usage: 68.9+ KB

In [25]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [26]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Session Start Date     489 non-null    object
 1   partido                489 non-null    object
 2   tiempo                 489 non-null    object
 3   Session Start          489 non-null    object
 4   Session End            489 non-null    object
 5   Evento                 489 non-null    object
 6   Tag Notes              0 non-null      float64
 7   Tag Start              489 non-null    object
 8   Tag End                489 non-null    object
 9   Tag Duration (secs)    489 non-null    float64
 10  coord inicial          489 non-null    float64
 11  Subevento              487 non-null    object
 12  Jugador 2              272 non-null    object
 13  Jugador 1              489 non-null    float64
 14  coord final            486 non-null    object
 15  Calificaciondelevento  2 non-null      object
 16  Dificultad             2 non-null      object
 17  Optional Column        0 non-null      float64
 18  segundos               489 non-null    float64
dtypes: float64(6), object(13)
memory usage: 72.9+ KB

In [28]:
data.partido = 'Velez'

In [29]:
data

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Calificaciondelevento,Dificultad,Optional Column,segundos
0,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Perdida,NaN,00:19:52,00:19:58,6.0,7.0,Interceptado,Rival,1.0,7,NaN,NaN,NaN,1192.0
1,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,00:19:45,00:19:45,0.0,11.0,corto,5,9.0,11,NaN,NaN,NaN,1185.0
2,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,00:19:48,00:19:48,0.0,11.0,medio,2,5.0,8,NaN,NaN,NaN,1188.0
3,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,00:19:51,00:19:51,0.0,8.0,medio,1,2.0,3,NaN,NaN,NaN,1191.0
4,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Recuperacion,NaN,00:20:41,00:20:41,0.0,2.0,Intercepcion,NaN,2.0,Volver,NaN,NaN,NaN,1241.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Pase,NaN,02:28:36,02:28:36,0.0,18.0,corto,18,9.0,14,NaN,NaN,NaN,8916.0
486,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Falta,NaN,02:28:42,02:28:42,0.0,17.0,Recibida,NaN,18.0,Volver,NaN,NaN,NaN,8922.0
487,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Pelota parada,NaN,02:29:29,02:29:29,0.0,17.0,Tiro libre,NaN,18.0,Volver,NaN,NaN,NaN,8969.0
488,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,Perdida,NaN,02:29:30,02:29:30,0.0,17.0,Interceptado,NaN,18.0,Volver,NaN,NaN,NaN,8970.0
489,NaN,Velez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [31]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [32]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [33]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Jugador 1 Evento       Subevento
1.0       arquero      remate atajable            3
                       remate no atajable         1
                       salida aerea               2
                       salvada/atajada            2
          pase         corto                      3
...                                             ...
21.0      perdida      interceptado               1
                       robo                       1
          recuperacion encontrada                 1
                       robo                       1
          tarjeta      amarilla                   1

[190 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [34]:
data_eventos = data.copy()
data_eventos.shape

(490, 19)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [35]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
data_eventos.loc[data_eventos['remate-Gol'] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Calificaciondelevento,Dificultad,Optional Column,segundos,remate-Gol
176,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:59:53,00:59:53,0.0,21.0,corta distancia,NaN,2.0,Volver,NaN,NaN,NaN,3593.0,1

In [36]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Subevento,Jugador 2,Jugador 1,coord final,Calificaciondelevento,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera
49,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:29:36,00:29:36,0.0,...,corta distancia,NaN,6.0,Volver,NaN,NaN,NaN,1776.0,0,1
163,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:56:21,00:56:21,0.0,...,media distancia,NaN,9.0,Volver,NaN,NaN,NaN,3381.0,0,1
259,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,01:32:19,01:32:19,0.0,...,media distancia,NaN,5.0,Volver,NaN,NaN,NaN,5539.0,0,1
417,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:18:00,02:18:00,0.0,...,media distancia,NaN,8.0,Volver,NaN,NaN,NaN,8280.0,0,1
436,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:21:31,02:21:31,0.0,...,media distancia,NaN,5.0,Volver,NaN,NaN,NaN,8491.0,0,1

In [37]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 2,Jugador 1,coord final,Calificaciondelevento,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco
41,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:27:52,00:27:52,0.0,...,NaN,9.0,Volver,NaN,NaN,NaN,1672.0,0,0,1
360,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:02:50,02:02:50,0.0,...,NaN,8.0,Volver,NaN,NaN,NaN,7370.0,0,0,1
478,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:26:42,02:26:42,0.0,...,NaN,9.0,Volver,NaN,NaN,NaN,8802.0,0,0,1

In [38]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado]
Index: []

[0 rows x 23 columns]

In [39]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza]
Index: []

[0 rows x 24 columns]

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [40]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                      cantidad
Evento Subevento
pase   centro aereo          4
       corto               113
       inteligente           2
       largo                55
       medio                20
       s arquero pie         7

In [41]:
data[(data.Evento=='pase')]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Calificaciondelevento,Dificultad,Optional Column,segundos
1,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:45,00:19:45,0.0,11.0,corto,5,9.0,11,NaN,NaN,NaN,1185.0
2,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:48,00:19:48,0.0,11.0,medio,2,5.0,8,NaN,NaN,NaN,1188.0
3,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:51,00:19:51,0.0,8.0,medio,1,2.0,3,NaN,NaN,NaN,1191.0
11,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:21:22,00:21:22,0.0,9.0,largo,10,2.0,14,NaN,NaN,NaN,1282.0
12,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:21:23,00:21:23,0.0,14.0,corto,9,10.0,14,NaN,NaN,NaN,1283.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:26:40,02:26:40,0.0,16.0,corto,19,3.0,20,NaN,NaN,NaN,8800.0
477,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:26:41,02:26:41,0.0,20.0,corto,9,19.0,21,NaN,NaN,NaN,8801.0
480,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:27:29,02:27:29,0.0,10.0,corto,3,18.0,10,NaN,NaN,NaN,8849.0
482,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:13,02:28:13,0.0,9.0,largo,9,19.0,12,NaN,NaN,NaN,8893.0
485,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:36,02:28:36,0.0,18.0,corto,18,9.0,14,NaN,NaN,NaN,8916.0

In [42]:
data_eventos.head()

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,coord final,Calificaciondelevento,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
0,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:19:52,00:19:58,6.0,...,7,NaN,NaN,NaN,1192.0,0,0,0,0,0
1,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:45,00:19:45,0.0,...,11,NaN,NaN,NaN,1185.0,0,0,0,0,0
2,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:48,00:19:48,0.0,...,8,NaN,NaN,NaN,1188.0,0,0,0,0,0
3,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:51,00:19:51,0.0,...,3,NaN,NaN,NaN,1191.0,0,0,0,0,0
4,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:20:41,00:20:41,0.0,...,Volver,NaN,NaN,NaN,1241.0,0,0,0,0,0

In [43]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''
colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia]
Index: []

[0 rows x 25 columns]

In [44]:
##completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='centro aereo') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='bloqueado'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) | (data_eventos.loc[i+1,'Subevento'] == 'offside' ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Dificultad,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado
1,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:45,00:19:45,0.0,...,NaN,NaN,1185.0,0,0,0,0,0,0,1
2,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:48,00:19:48,0.0,...,NaN,NaN,1188.0,0,0,0,0,0,0,1
3,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:51,00:19:51,0.0,...,NaN,NaN,1191.0,0,0,0,0,0,0,1
11,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:21:22,00:21:22,0.0,...,NaN,NaN,1282.0,0,0,0,0,0,0,1
12,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:21:23,00:21:23,0.0,...,NaN,NaN,1283.0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:26:40,02:26:40,0.0,...,NaN,NaN,8800.0,0,0,0,0,0,0,1
477,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:26:41,02:26:41,0.0,...,NaN,NaN,8801.0,0,0,0,0,0,0,1
480,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:27:29,02:27:29,0.0,...,NaN,NaN,8849.0,0,0,0,0,0,0,1
482,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:13,02:28:13,0.0,...,NaN,NaN,8893.0,0,0,0,0,0,0,1
485,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:36,02:28:36,0.0,...,NaN,NaN,8916.0,0,0,0,0,0,0,1

In [45]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

corto            97
largo            34
medio            15
s arquero pie     6
inteligente       2
Name: Subevento, dtype: int64

In [46]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado
28,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:23:10,00:23:10,0.0,...,NaN,1390.0,0,0,0,0,0,0,0,1
58,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:31:04,00:31:04,0.0,...,NaN,1864.0,0,0,0,0,0,0,0,1
95,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:37:19,00:37:19,0.0,...,NaN,2239.0,0,0,0,0,0,0,0,1
98,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:38:38,00:38:38,0.0,...,NaN,2318.0,0,0,0,0,0,0,0,1
123,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:47:25,00:47:25,0.0,...,NaN,2845.0,0,0,0,0,0,0,0,1
129,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:47:54,00:47:54,0.0,...,NaN,2874.0,0,0,0,0,0,0,0,1
142,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:51:26,00:51:26,0.0,...,NaN,3086.0,0,0,0,0,0,0,0,1
157,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:53:46,00:53:46,0.0,...,NaN,3226.0,0,0,0,0,0,0,0,1
166,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:57:58,00:57:58,0.0,...,NaN,3478.0,0,0,0,0,0,0,0,1
196,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:07:09,01:07:09,0.0,...,NaN,4029.0,0,0,0,0,0,0,0,1
200,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:07:33,01:07:33,0.0,...,NaN,4053.0,0,0,0,0,0,0,0,1
227,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:27:50,01:27:50,0.0,...,NaN,5270.0,0,0,0,0,0,0,0,1
251,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:31:11,01:31:11,0.0,...,NaN,5471.0,0,0,0,0,0,0,0,1
256,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:31:51,01:31:51,0.0,...,NaN,5511.0,0,0,0,0,0,0,0,1
265,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:33:54,01:33:54,0.0,...,NaN,5634.0,0,0,0,0,0,0,0,1
270,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:34:44,01:34:44,0.0,...,NaN,5684.0,0,0,0,0,0,0,0,1
278,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:36:20,01:36:20,0.0,...,NaN,5780.0,0,0,0,0,0,0,0,1
295,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:37:48,01:37:48,0.0,...,NaN,5868.0,0,0,0,0,0,0,0,1
309,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:53:47,01:53:47,0.0,...,NaN,6827.0,0,0,0,0,0,0,0,1
314,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:55:44,01:55:44,0.0,...,NaN,6944.0,0,0,0,0,0,0,0,1
349,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:01:04,02:01:04,0.0,...,NaN,7264.0,0,0,0,0,0,0,1,1
352,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:01:38,02:01:38,0.0,...,NaN,7298.0,0,0,0,0,0,0,0,1
364,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:04:24,02:04:24,0.0,...,NaN,7464.0,0,0,0,0,0,0,0,1
374,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:07:07,02:07:07,0.0,...,NaN,7627.0,0,0,0,0,0,0,0,1
377,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:07:17,02:07:17,0.0,...,NaN,7637.0,0,0,0,0,0,0,0,1
394,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:13:15,02:13:15,0.0,...,NaN,7995.0,0,0,0,0,0,0,0,1
400,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:14:43,02:14:43,0.0,...,NaN,8083.0,0,0,0,0,0,0,0,1
409,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:15:45,02:15:45,0.0,...,NaN,8145.0,0,0,0,0,0,0,0,1
426,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:20:03,02:20:03,0.0,...,NaN,8403.0,0,0,0,0,0,0,0,1
443,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:22:23,02:22:23,0.0,...,NaN,8543.0,0,0,0,0,0,0,0,1

In [47]:
#fuera
'''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

colname = 'pase-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera
112,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:40:34,00:40:34,0.0,...,2434.0,0,0,0,0,0,0,0,0,1
233,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:28:21,01:28:21,0.0,...,5301.0,0,0,0,0,0,0,1,0,1
262,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:33:09,01:33:09,0.0,...,5589.0,0,0,0,0,0,0,0,0,1
324,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:56:56,01:56:56,0.0,...,7016.0,0,0,0,0,0,0,1,0,1
482,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:13,02:28:13,0.0,...,8893.0,0,0,0,0,0,0,1,0,1

In [48]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente
78,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:33:28,00:33:28,0.0,...,0,0,0,0,0,0,1,0,0,1
274,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:35:01,01:35:01,0.0,...,0,0,0,0,0,0,1,0,0,1

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [49]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [50]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 30 columns]

In [51]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado
450,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:23:22,02:23:22,0.0,...,0,0,0,0,0,0,0,0,0,1

In [52]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado
79,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:33:32,00:33:32,0.0,...,0,0,0,0,0,0,0,0,0,1
132,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:48:02,00:48:02,0.0,...,0,0,0,0,0,0,0,0,0,1

In [53]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 33 columns]

In [54]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 34 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [55]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [56]:
dejar_index= []
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo'):
        dejar_index.append(i-1)
        dejar_index.append(i)
        dejar_index.append(i+1)
data_eventos.loc[dejar_index].head(100)

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera
13,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:21:29,00:21:29,0.0,...,0,1,0,0,0,0,0,0,0,0
14,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:21:33,00:21:39,6.0,...,0,0,0,0,0,0,0,0,0,0
15,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:21:37,00:21:37,0.0,...,0,0,0,0,0,0,0,0,0,0
16,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:21:54,00:22:00,6.0,...,0,0,0,0,0,0,0,0,0,0
17,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:21:56,00:22:02,6.0,...,0,0,0,0,0,0,0,0,0,0
18,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:22:01,00:22:01,0.0,...,0,0,0,0,0,0,0,0,0,0
43,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:28:40,00:28:40,0.0,...,0,0,0,0,0,0,0,0,0,0
44,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:28:43,00:28:43,0.0,...,0,0,0,0,0,0,0,0,0,0
45,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:28:43,00:28:43,0.0,...,0,0,0,0,0,0,0,0,0,0
69,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:32:52,00:32:52,0.0,...,0,1,0,0,0,0,0,0,0,0
70,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:32:55,00:32:55,0.0,...,0,0,0,0,0,0,0,0,0,0
71,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:32:56,00:32:56,0.0,...,0,0,0,0,0,0,0,0,0,0
104,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:39:33,00:39:33,0.0,...,0,1,0,0,0,0,0,0,0,0
105,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:39:39,00:39:39,0.0,...,0,0,0,0,0,0,0,0,0,0
106,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:39:39,00:39:39,0.0,...,0,0,0,0,0,0,0,0,0,0
118,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:43:37,00:43:37,0.0,...,0,0,0,0,0,0,0,0,0,0
119,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:43:43,00:43:43,0.0,...,0,0,0,0,0,0,0,0,0,0
120,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:43:44,00:43:44,0.0,...,0,0,0,0,0,0,0,0,0,0
145,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:51:40,00:51:40,0.0,...,0,0,0,0,0,0,0,0,0,0
146,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:51:47,00:51:47,0.0,...,0,0,0,0,0,0,0,0,0,0
147,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:51:48,00:51:48,0.0,...,0,1,0,0,0,0,0,0,0,0
150,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:52:21,00:52:21,0.0,...,0,0,0,0,0,0,0,0,0,0
151,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:52:24,00:52:24,0.0,...,0,0,0,0,0,0,0,0,0,0
152,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:52:30,00:52:30,0.0,...,0,0,0,0,0,0,0,0,0,0
161,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:56:08,00:56:08,0.0,...,0,0,0,0,0,0,0,0,0,0
162,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:56:13,00:56:13,0.0,...,0,0,0,0,0,0,0,0,0,0
163,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:56:21,00:56:21,0.0,...,0,0,0,0,0,0,0,0,0,0
184,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:05:46,01:05:46,0.0,...,0,0,0,0,0,0,0,0,0,0
185,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:05:53,01:05:53,0.0,...,0,0,0,0,0,0,0,0,0,0
186,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:05:54,01:05:54,0.0,...,0,0,0,0,0,0,0,0,0,0
215,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:26:52,01:26:52,0.0,...,0,1,0,0,0,0,0,0,0,0
216,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:26:56,01:26:56,0.0,...,0,0,0,0,0,0,0,0,0,0
217,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:26:59,01:26:59,0.0,...,0,1,0,0,0,0,0,0,0,0
223,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:27:35,01:27:35,0.0,...,0,1,0,0,0,0,0,0,0,0
224,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:27:40,01:27:40,0.0,...,0,0,0,0,0,0,0,0,0,0
225,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:27:41,01:27:41,0.0,...,0,1,0,0,0,0,0,0,0,0
239,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:29:19,01:29:19,0.0,...,0,0,0,0,0,0,0,0,0,0
240,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:29:38,01:29:38,0.0,...,0,0,0,0,0,0,0,0,0,0
241,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:29:39,01:29:39,0.0,...,0,0,0,0,0,0,0,0,0,0
301,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:38:15,01:38:15,0.0,...,0,0,0,0,0,0,0,0,0,0
302,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:38:43,01:38:43,0.0,...,0,0,0,0,0,0,0,0,0,0
303,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:38:45,01:38:45,0.0,...,0,1,0,0,0,0,0,0,0,0
387,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:10:46,02:10:46,0.0,...,0,0,0,0,0,0,0,0,0,0
388,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:10:51,02:10:51,0.0,...,0,0,0,0,0,0,0,0,0,0
389,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:10:55,02:10:55,0.0,...,0,0,0,0,0,0,0,0,0,0
392,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:13:09,02:13:09,0.0,...,0,0,0,0,0,0,0,0,0,0
393,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:13:12,02:13:12,0.0,...,0,0,0,0,0,0,0,0,0,0
394,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:13:15,02:13:15,0.0,...,0,0,1,0,0,0,0,0,0,0
428,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:20:10,02:20:10,0.0,...,0,0,0,0,0,0,0,0,0,0
429,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:20:38,02:20:38,0.0,...,0,0,0,0,0,0,0,0,0,0
430,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:21:03,02:21:03,0.0,...,0,1,0,0,0,0,0,0,0,0
438,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:21:53,02:21:53,0.0,...,0,0,0,0,0,0,0,0,0,0
439,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:21:55,02:21:55,0.0,...,0,0,0,0,0,0,0,0,0,0
440,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:21:58,02:21:58,0.0,...,0,0,0,0,0,0,0,0,0,0
458,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:25:27,02:25:27,0.0,...,0,0,0,0,0,0,0,0,0,0
459,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:25:30,02:25:30,0.0,...,0,0,0,0,0,0,0,0,0,0
460,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:25:33,02:25:33,0.0,...,0,1,0,0,0,0,0,0,0,0

In [57]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
151,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:52:24,00:52:24,0.0,...,0,0,0,0,0,0,0,0,0,1

In [58]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
105,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:39:39,00:39:39,0.0,...,0,0,0,0,0,0,0,0,0,1
119,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:43:43,00:43:43,0.0,...,0,0,0,0,0,0,0,0,0,1
146,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:51:47,00:51:47,0.0,...,0,0,0,0,0,0,0,0,0,1
240,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:29:38,01:29:38,0.0,...,0,0,0,0,0,0,0,0,0,1
429,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:20:38,02:20:38,0.0,...,0,0,0,0,0,0,0,0,0,1

In [59]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 40 columns]

In [60]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada
162,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:56:13,00:56:13,0.0,...,0,0,0,0,0,0,0,0,0,1
216,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:26:56,01:26:56,0.0,...,0,0,0,0,0,0,0,0,0,1
224,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:27:40,01:27:40,0.0,...,0,0,0,0,0,0,0,0,0,1
302,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,01:38:43,01:38:43,0.0,...,0,0,0,0,0,0,0,0,0,1
388,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:10:51,02:10:51,0.0,...,0,0,0,0,0,0,0,0,0,1
393,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:13:12,02:13:12,0.0,...,0,0,0,0,0,0,0,0,0,1
459,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:25:30,02:25:30,0.0,...,0,0,0,0,0,0,0,0,0,1

In [61]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 44 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [62]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [63]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida
84,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:33:47,00:33:47,0.0,...,0,0,0,0,0,0,0,0,0,1
93,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:36:52,00:36:52,0.0,...,0,0,0,0,0,0,0,0,0,1
100,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:38:50,00:38:50,0.0,...,0,0,0,0,0,0,0,0,0,1
114,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:40:51,00:40:51,0.0,...,0,0,0,0,0,0,0,0,0,1
160,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:55:51,00:55:51,0.0,...,0,0,0,0,0,0,0,0,0,1
267,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:34:04,01:34:04,0.0,...,0,0,0,0,0,0,0,0,0,1
351,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:01:30,02:01:30,0.0,...,0,0,0,0,0,0,0,0,0,1
362,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:03:01,02:03:01,0.0,...,0,0,0,0,0,0,0,0,0,1
370,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:06:32,02:06:32,0.0,...,0,0,0,0,0,0,0,0,0,1
382,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:08:18,02:08:18,0.0,...,0,0,0,0,0,0,0,0,0,1
386,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:10:10,02:10:10,0.0,...,0,0,0,0,0,0,0,0,0,1
423,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:18:39,02:18:39,0.0,...,0,0,0,0,0,0,0,0,0,1
428,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:20:10,02:20:10,0.0,...,0,0,0,0,0,0,0,0,0,1
441,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:21:59,02:21:59,0.0,...,0,0,0,0,0,0,0,0,0,1

In [64]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida
32,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:25:02,00:25:08,6.0,...,0,0,0,0,0,0,0,0,0,1
46,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:28:57,00:28:57,0.0,...,0,0,0,0,0,0,0,0,0,1
53,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:30:23,00:30:23,0.0,...,0,0,0,0,0,0,0,0,0,1
65,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:32:35,00:32:35,0.0,...,0,0,0,0,0,0,0,0,0,1
86,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:35:25,00:35:25,0.0,...,0,0,0,0,0,0,0,0,0,1
148,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:51:53,00:51:53,0.0,...,0,0,0,0,0,0,0,0,0,1
156,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:53:22,00:53:22,0.0,...,0,0,0,0,0,0,0,0,0,1
171,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:58:38,00:58:38,0.0,...,0,0,0,0,0,0,0,0,0,1
174,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:59:04,00:59:04,0.0,...,0,0,0,0,0,0,0,0,0,1
179,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:02:20,01:02:20,0.0,...,0,0,0,0,0,0,0,0,0,1
183,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:03:35,01:03:35,0.0,...,0,0,0,0,0,0,0,0,0,1
193,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:06:21,01:06:21,0.0,...,0,0,0,0,0,0,0,0,0,1
281,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:36:48,01:36:48,0.0,...,0,0,0,0,0,0,0,0,0,1
301,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:38:15,01:38:15,0.0,...,0,0,0,0,0,0,0,0,0,1
340,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,01:59:10,01:59:10,0.0,...,0,0,0,0,0,0,0,0,0,1
357,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:02:18,02:02:18,0.0,...,0,0,0,0,0,0,0,0,0,1
389,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:10:55,02:10:55,0.0,...,0,0,0,0,0,0,0,0,0,1
453,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:24:05,02:24:05,0.0,...,0,0,0,0,0,0,0,0,0,1
457,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:25:11,02:25:11,0.0,...,0,0,0,0,0,0,0,0,0,1
486,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:28:42,02:28:42,0.0,...,0,0,0,0,0,0,0,0,0,1

In [65]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 47 columns]

In [66]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 48 columns]

In [67]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside]
Index: []

[0 rows x 49 columns]

In [68]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla
100,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:38:50,00:38:50,0.0,...,0,0,0,0,1,0,0,0,0,1
114,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,00:40:51,00:40:51,0.0,...,0,0,0,0,1,0,0,0,0,1
382,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:08:18,02:08:18,0.0,...,0,0,0,0,1,0,0,0,0,1
423,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:18:39,02:18:39,0.0,...,0,0,0,0,1,0,0,0,0,1

In [69]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja]
Index: []

[0 rows x 51 columns]

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [70]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [71]:
colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo
23,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:22:55,00:22:55,0.0,...,0,0,0,0,0,0,0,0,0,1
26,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:23:03,00:23:03,0.0,...,0,0,0,0,0,0,0,0,0,1
60,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:31:11,00:31:11,0.0,...,0,0,0,0,0,0,0,0,0,1
102,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:39:23,00:39:23,0.0,...,0,0,0,0,0,0,0,0,0,1
194,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:07:05,01:07:05,0.0,...,0,0,0,0,0,0,0,0,0,1
198,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:07:28,01:07:28,0.0,...,0,0,0,0,0,0,0,0,0,1
204,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:25:47,01:25:47,0.0,...,0,0,0,0,0,0,0,0,0,1
209,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:26:05,01:26:05,0.0,...,0,0,0,0,0,0,0,0,0,1
229,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:27:58,01:27:58,0.0,...,0,0,0,0,0,0,0,0,0,1
297,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:38:08,01:38:08,0.0,...,0,0,0,0,0,0,0,0,0,1
321,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:56:25,01:56:25,0.0,...,0,0,0,0,0,0,0,0,0,1
338,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:58:57,01:58:57,0.0,...,0,0,0,0,0,0,0,0,0,1
387,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:10:46,02:10:46,0.0,...,0,0,0,0,0,0,0,0,0,1
392,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:13:09,02:13:09,0.0,...,0,0,0,0,0,0,0,0,0,1
415,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:17:45,02:17:45,0.0,...,0,0,0,0,0,0,0,0,0,1
425,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:19:56,02:19:56,0.0,...,0,0,0,0,0,0,0,0,0,1
438,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:21:53,02:21:53,0.0,...,0,0,0,0,0,0,0,0,0,1
445,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:22:42,02:22:42,0.0,...,0,0,0,0,0,0,0,0,0,1
448,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:23:10,02:23:10,0.0,...,0,0,0,0,0,0,0,0,0,1
456,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:25:04,02:25:04,0.0,...,0,0,0,0,0,0,0,0,0,1
466,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:25:55,02:25:55,0.0,...,0,0,0,0,0,0,0,0,0,1
473,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:26:23,02:26:23,0.0,...,0,0,0,0,0,0,0,0,0,1

In [72]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada
7,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:21:01,00:21:01,0.0,...,0,0,0,0,0,0,0,0,0,1
10,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:21:20,00:21:20,0.0,...,0,0,0,0,0,0,0,0,0,1
56,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:30:58,00:30:58,0.0,...,0,0,0,0,0,0,0,0,0,1
81,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:33:36,00:33:36,0.0,...,0,0,0,0,0,0,0,0,0,1
90,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:36:46,00:36:46,0.0,...,0,0,0,0,0,0,0,0,0,1
117,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:42:12,00:42:12,0.0,...,0,0,0,0,0,0,0,0,0,1
131,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:47:57,00:47:57,0.0,...,0,0,0,0,0,0,0,0,0,1
134,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:49:03,00:49:03,0.0,...,0,0,0,0,0,0,0,0,0,1
184,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:05:46,01:05:46,0.0,...,0,0,0,0,0,0,0,0,0,1
187,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:05:54,01:05:54,0.0,...,0,0,0,0,0,0,0,0,0,1
190,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:06:11,01:06:11,0.0,...,0,0,0,0,0,0,0,0,0,1
220,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:27:26,01:27:26,0.0,...,0,0,0,0,0,0,0,0,0,1
235,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:29:06,01:29:06,0.0,...,0,0,0,0,0,0,0,0,0,1
247,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:31:01,01:31:01,0.0,...,0,0,0,0,0,0,0,0,0,1
280,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:36:44,01:36:44,0.0,...,0,0,0,0,0,0,0,0,0,1
354,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:02:05,02:02:05,0.0,...,0,0,0,0,0,0,0,0,0,1
366,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:04:58,02:04:58,0.0,...,0,0,0,0,0,0,0,0,0,1
373,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:07:04,02:07:04,0.0,...,0,0,0,0,0,0,0,0,0,1
376,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:07:15,02:07:15,0.0,...,0,0,0,0,0,0,0,0,0,1
408,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:15:43,02:15:43,0.0,...,0,0,0,0,0,0,0,0,0,1
411,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:16:18,02:16:18,0.0,...,0,0,0,0,0,0,0,0,0,1
422,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:18:32,02:18:32,0.0,...,0,0,0,0,0,0,0,0,0,1

In [73]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo
4,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:20:41,00:20:41,0.0,...,0,0,0,0,0,0,0,0,0,1
51,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:30:19,00:30:19,0.0,...,0,0,0,0,0,0,0,0,0,1
94,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:37:15,00:37:15,0.0,...,0,0,0,0,0,0,0,0,0,1
137,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:50:39,00:50:39,0.0,...,0,0,0,0,0,0,0,0,0,1
144,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:51:39,00:51:39,0.0,...,0,0,0,0,0,0,0,0,0,1
153,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:53:11,00:53:11,0.0,...,0,0,0,0,0,0,0,0,0,1
161,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:56:08,00:56:08,0.0,...,0,0,0,0,0,0,0,0,0,1
168,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:58:02,00:58:02,0.0,...,0,0,0,0,0,0,0,0,0,1
264,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:33:52,01:33:52,0.0,...,0,0,0,0,0,0,0,0,0,1
344,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:00:52,02:00:52,0.0,...,0,0,0,0,0,0,0,0,0,1
398,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:14:37,02:14:37,0.0,...,0,0,0,0,0,0,0,0,0,1
468,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:26:06,02:26:06,0.0,...,0,0,0,0,0,0,0,0,0,1

In [74]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo
182,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:03:33,01:03:33,0.0,...,0,0,0,0,0,0,0,0,0,1
463,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,02:25:46,02:25:46,0.0,...,0,0,0,0,0,0,0,0,0,1

In [75]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo
272,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:34:52,01:34:52,0.0,...,0,0,0,0,0,0,0,0,0,1
311,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:53:49,01:53:49,0.0,...,0,0,0,0,0,0,0,0,0,1
333,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,01:58:22,01:58:22,0.0,...,0,0,0,0,0,0,0,0,0,1

In [76]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if (data_eventos.loc[i+1,'Evento'] == 'recuperacion') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo]
Index: []

[0 rows x 57 columns]

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [77]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [78]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
19,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:22:16,00:22:22,6.0,...,0,0,0,0,0,0,0,0,0,1
36,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:26:57,00:26:57,0.0,...,0,0,0,0,0,0,0,0,0,1
72,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:33:16,00:33:16,0.0,...,0,0,0,0,0,0,0,0,0,1
107,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:40:04,00:40:04,0.0,...,0,0,0,0,0,0,0,0,0,1
118,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:43:37,00:43:37,0.0,...,0,0,0,0,0,0,0,0,0,1
125,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:47:41,00:47:41,0.0,...,0,0,0,0,0,0,0,0,0,1
253,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,01:31:27,01:31:27,0.0,...,0,0,0,0,0,0,0,0,0,1
258,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,01:32:16,01:32:16,0.0,...,0,0,0,0,0,0,0,0,0,1
288,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,01:37:26,01:37:26,0.0,...,0,0,0,0,0,0,0,0,0,1
326,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,01:57:10,01:57:10,0.0,...,0,0,0,0,0,0,0,0,0,1
343,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:00:48,02:00:48,0.0,...,0,0,0,0,0,0,0,0,0,1
371,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:07:02,02:07:02,0.0,...,0,0,0,0,0,0,0,0,0,1
433,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:21:25,02:21:25,0.0,...,0,0,0,0,0,0,0,0,0,1
481,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:28:09,02:28:09,0.0,...,0,0,0,0,0,0,0,0,0,1
484,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:28:37,02:28:37,0.0,...,0,0,0,0,0,0,0,0,0,1

In [79]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 61 columns]

In [80]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
33,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:25:38,00:25:44,6.0,...,0,0,0,0,0,0,0,0,0,1
43,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:28:40,00:28:40,0.0,...,0,0,0,0,0,0,0,0,0,1
47,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:29:33,00:29:33,0.0,...,0,0,0,0,0,0,0,0,0,1
66,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:32:46,00:32:46,0.0,...,0,0,0,0,0,0,0,0,0,1
175,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,00:59:51,00:59:51,0.0,...,0,0,0,0,0,0,0,0,0,1
180,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,01:03:21,01:03:21,0.0,...,0,0,0,0,0,0,0,0,0,1
341,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,01:59:38,01:59:38,0.0,...,0,0,0,0,0,0,0,0,0,1
358,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:02:43,02:02:43,0.0,...,0,0,0,0,0,0,0,0,0,1
458,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:25:27,02:25:27,0.0,...,0,0,0,0,0,0,0,0,0,1

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [81]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [82]:
#gambeta a favor

colname = 'perdida-Gambeta-favor'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor
70,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,00:32:55,00:32:55,0.0,...,0,0,0,0,0,0,0,0,0,1
439,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,duelo,NaN,02:21:55,02:21:55,0.0,...,0,0,0,0,0,0,0,0,0,1

In [83]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='robo'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo
22,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:22:28,00:22:28,0.0,...,0,0,0,0,0,0,0,0,0,1
25,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:23:01,00:23:01,0.0,...,0,0,0,0,0,0,0,0,0,1
38,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:27:02,00:27:02,0.0,...,0,0,0,0,0,0,0,0,0,1
83,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:33:41,00:33:41,0.0,...,0,0,0,0,0,0,0,0,0,1
106,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:39:39,00:39:39,0.0,...,0,0,0,0,0,0,0,0,0,1
150,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:52:21,00:52:21,0.0,...,0,0,0,0,0,0,0,0,0,1
170,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:58:09,00:58:09,0.0,...,0,0,0,0,0,0,0,0,0,1
189,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:06:04,01:06:04,0.0,...,0,0,0,0,0,0,0,0,0,1
208,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:25:54,01:25:54,0.0,...,0,0,0,0,0,0,0,0,0,1
213,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:26:16,01:26:16,0.0,...,0,0,0,0,0,0,0,0,0,1
219,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:27:05,01:27:05,0.0,...,0,0,0,0,0,0,0,0,0,1
313,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:53:54,01:53:54,0.0,...,0,0,0,0,0,0,0,0,0,1
405,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:15:08,02:15:08,0.0,...,0,0,0,0,0,0,0,0,0,1

In [84]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion
0,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:19:52,00:19:58,6.0,...,0,0,0,0,0,0,0,0,0,1
9,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:21:07,00:21:07,0.0,...,0,0,0,0,0,0,0,0,0,1
29,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:23:13,00:23:13,0.0,...,0,0,0,0,0,0,0,0,0,1
59,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:31:05,00:31:05,0.0,...,0,0,0,0,0,0,0,0,0,1
80,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:33:33,00:33:33,0.0,...,0,0,0,0,0,0,0,0,0,1
88,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:35:58,00:35:58,0.0,...,0,0,0,0,0,0,0,0,0,1
96,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:37:20,00:37:20,0.0,...,0,0,0,0,0,0,0,0,0,1
99,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:38:39,00:38:39,0.0,...,0,0,0,0,0,0,0,0,0,1
120,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:43:44,00:43:44,0.0,...,0,0,0,0,0,0,0,0,0,1
124,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:47:28,00:47:28,0.0,...,0,0,0,0,0,0,0,0,0,1
130,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:47:56,00:47:56,0.0,...,0,0,0,0,0,0,0,0,0,1
133,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:48:03,00:48:03,0.0,...,0,0,0,0,0,0,0,0,0,1
143,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:51:26,00:51:26,0.0,...,0,0,0,0,0,0,0,0,0,1
152,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:52:30,00:52:30,0.0,...,0,0,0,0,0,0,0,0,0,1
158,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:53:47,00:53:47,0.0,...,0,0,0,0,0,0,0,0,0,1
167,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:58:00,00:58:00,0.0,...,0,0,0,0,0,0,0,0,0,1
197,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:07:12,01:07:12,0.0,...,0,0,0,0,0,0,0,0,0,1
201,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:07:34,01:07:34,0.0,...,0,0,0,0,0,0,0,0,0,1
203,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:08:04,01:08:04,0.0,...,0,0,0,0,0,0,0,0,0,1
228,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:27:51,01:27:51,0.0,...,0,0,0,0,0,0,0,0,0,1
252,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:31:13,01:31:13,0.0,...,0,0,0,0,0,0,0,0,0,1
257,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:31:52,01:31:52,0.0,...,0,0,0,0,0,0,0,0,0,1
266,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:33:56,01:33:56,0.0,...,0,0,0,0,0,0,0,0,0,1
271,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:34:45,01:34:45,0.0,...,0,0,0,0,0,0,0,0,0,1
276,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:35:04,01:35:04,0.0,...,0,0,0,0,0,0,0,0,0,1
279,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:36:21,01:36:21,0.0,...,0,0,0,0,0,0,0,0,0,1
296,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:37:49,01:37:49,0.0,...,0,0,0,0,0,0,0,0,0,1
305,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:38:49,01:38:49,0.0,...,0,0,0,0,0,0,0,0,0,1
310,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:53:48,01:53:48,0.0,...,0,0,0,0,0,0,0,0,0,1
315,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:55:45,01:55:45,0.0,...,0,0,0,0,0,0,0,0,0,1
350,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:01:07,02:01:07,0.0,...,0,0,0,0,0,0,0,0,0,1
353,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:01:40,02:01:40,0.0,...,0,0,0,0,0,0,0,0,0,1
365,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:04:26,02:04:26,0.0,...,0,0,0,0,0,0,0,0,0,1
372,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:07:03,02:07:03,0.0,...,0,0,0,0,0,0,0,0,0,1
375,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:07:08,02:07:08,0.0,...,0,0,0,0,0,0,0,0,0,1
378,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:07:18,02:07:18,0.0,...,0,0,0,0,0,0,0,0,0,1
391,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:11:25,02:11:25,0.0,...,0,0,0,0,0,0,0,0,0,1
395,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:13:16,02:13:16,0.0,...,0,0,0,0,0,0,0,0,0,1
401,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:14:44,02:14:44,0.0,...,0,0,0,0,0,0,0,0,0,1
410,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:15:49,02:15:49,0.0,...,0,0,0,0,0,0,0,0,0,1
427,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:20:04,02:20:04,0.0,...,0,0,0,0,0,0,0,0,0,1
444,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:22:25,02:22:25,0.0,...,0,0,0,0,0,0,0,0,0,1
455,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:24:49,02:24:49,0.0,...,0,0,0,0,0,0,0,0,0,1
488,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:29:30,02:29:30,0.0,...,0,0,0,0,0,0,0,0,0,1

In [85]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico
55,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:30:53,00:30:53,0.0,...,0,0,0,0,0,0,0,0,0,1
64,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:31:16,00:31:16,0.0,...,0,0,0,0,0,0,0,0,0,1
110,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:40:11,00:40:11,0.0,...,0,0,0,0,0,0,0,0,0,1
139,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:50:47,00:50:47,0.0,...,0,0,0,0,0,0,0,0,0,1
241,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:29:39,01:29:39,0.0,...,0,0,0,0,0,0,0,0,0,1
246,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:30:37,01:30:37,0.0,...,0,0,0,0,0,0,0,0,0,1
289,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:37:27,01:37:27,0.0,...,0,0,0,0,0,0,0,0,0,1
320,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:56:00,01:56:00,0.0,...,0,0,0,0,0,0,0,0,0,1
332,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:58:10,01:58:10,0.0,...,0,0,0,0,0,0,0,0,0,1
337,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,01:58:32,01:58:32,0.0,...,0,0,0,0,0,0,0,0,0,1
347,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:00:54,02:00:54,0.0,...,0,0,0,0,0,0,0,0,0,1
381,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:08:10,02:08:10,0.0,...,0,0,0,0,0,0,0,0,0,1
447,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:22:49,02:22:49,0.0,...,0,0,0,0,0,0,0,0,0,1
471,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:26:11,02:26:11,0.0,...,0,0,0,0,0,0,0,0,0,1

In [86]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
            data_eventos.loc[i-1,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera
5,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,despeje,NaN,00:20:52,00:20:52,0.0,...,0,0,0,0,0,0,0,0,0,1
49,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:29:36,00:29:36,0.0,...,0,0,0,0,0,0,0,0,0,1
112,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:40:34,00:40:34,0.0,...,0,0,0,0,0,0,0,0,0,1
140,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,despeje,NaN,00:51:07,00:51:07,0.0,...,0,0,0,0,0,0,0,0,0,1
144,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:51:39,00:51:39,0.0,...,0,0,0,0,0,0,0,0,0,1
163,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:56:21,00:56:21,0.0,...,0,0,0,0,0,0,0,0,0,1
233,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:28:21,01:28:21,0.0,...,0,0,0,0,0,0,0,0,0,1
259,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,01:32:19,01:32:19,0.0,...,0,0,0,0,0,0,0,0,0,1
262,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:33:09,01:33:09,0.0,...,0,0,0,0,0,0,0,0,0,1
324,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:56:56,01:56:56,0.0,...,0,0,0,0,0,0,0,0,0,1
417,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:18:00,02:18:00,0.0,...,0,0,0,0,0,0,0,0,0,1
436,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:21:31,02:21:31,0.0,...,0,0,0,0,0,0,0,0,0,1
482,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:13,02:28:13,0.0,...,0,0,0,0,0,0,0,0,0,1

In [87]:
#situacion rival

colname = 'perdida-Situacion-rival'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='situacion rival'):
        if (data_eventos.loc[i,'Subevento']=='directa'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival]
Index: []

[0 rows x 69 columns]

In [88]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='atajada'):
            data_eventos.loc[i-1,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Situacion-rival,perdida-Atajada
41,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,00:27:52,00:27:52,0.0,...,0,0,0,0,0,0,0,0,0,1
238,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,01:29:17,01:29:17,0.0,...,0,0,0,0,0,0,0,0,0,1
360,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:02:50,02:02:50,0.0,...,0,0,0,0,0,0,0,0,0,1
450,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:23:22,02:23:22,0.0,...,0,0,0,0,0,0,0,0,0,1
478,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,remate pie,NaN,02:26:42,02:26:42,0.0,...,0,0,0,0,0,0,0,0,0,1

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [89]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
arquero       remate atajable               3
              remate no atajable            1
              salida aerea                  2
              salvada/atajada               2
despeje       bloqueo                       1
              despeje                       7
duelo         aereo                         3
              disputa suelo                 7
              gambeta a favor               9
falta         hecha                        14
              recibida                     20
pase          centro aereo                  4
              corto                       113
              inteligente                   2
              largo                        55
              medio                        20
              s arquero pie                 7
pelota parada lateral corto                 5
              lateral largo                11
              tiro libre                   14
perdida       atajada                       5
              balon afuera fondo            5
              balon afuera lateral          8
              duelo                        16
              error tecnico                14
              intercepcion aereo            1
              interceptado                 43
              robo                         13
recuperacion  duelo                         5
              encontrada                   22
              intercepcion                 12
              intercepcion aereo            2
              intercepcion anticipo         3
              robo                         22
remate pie    corta distancia               8
              media distancia               4
tarjeta       amarilla                      4

In [90]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable]
Index: []

[0 rows x 72 columns]

In [91]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in data_eventos.loc[i,'Subevento']) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            if ('remate' in data_eventos.loc[i-1,'Evento']):
                data_eventos.loc[i-1,colname] = 1
            elif ('remate' in data_eventos.loc[i-2,'Evento']):
                data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Situacion-rival,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada
89,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,arquero,NaN,00:36:42,00:36:42,0.0,...,0,0,0,0,0,0,0,0,0,1
472,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,arquero,NaN,02:26:12,02:26:12,0.0,...,0,0,0,0,0,0,0,0,0,1

In [92]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [93]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 74 columns]

In [94]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 75 columns]

In [95]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 76 columns]

In [96]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano]
Index: []

[0 rows x 77 columns]

In [97]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie]
Index: []

[0 rows x 78 columns]

In [98]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Calificaciondelevento, Dificultad, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 79 columns]

In [99]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [100]:
data_eventos.iloc[:,:20]

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),coord.inicial,Subevento,Jugador.2,Jugador.1,coord.final,Calificaciondelevento,Dificultad,Optional.Column,segundos,remate-Gol
0,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,00:19:52,00:19:58,6.0,7.0,interceptado,Rival,1.0,7,NaN,NaN,NaN,1192.0,0
1,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:45,00:19:45,0.0,11.0,corto,5,9.0,11,NaN,NaN,NaN,1185.0,0
2,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:48,00:19:48,0.0,11.0,medio,2,5.0,8,NaN,NaN,NaN,1188.0,0
3,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,00:19:51,00:19:51,0.0,8.0,medio,1,2.0,3,NaN,NaN,NaN,1191.0,0
4,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,recuperacion,NaN,00:20:41,00:20:41,0.0,2.0,intercepcion,NaN,2.0,Volver,NaN,NaN,NaN,1241.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:36,02:28:36,0.0,18.0,corto,18,9.0,14,NaN,NaN,NaN,8916.0,0
486,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:28:42,02:28:42,0.0,17.0,recibida,NaN,18.0,Volver,NaN,NaN,NaN,8922.0,0
487,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:29:29,02:29:29,0.0,17.0,tiro libre,NaN,18.0,Volver,NaN,NaN,NaN,8969.0,0
488,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:29:30,02:29:30,0.0,17.0,interceptado,NaN,18.0,Volver,NaN,NaN,NaN,8970.0,0
489,NaN,Velez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [101]:
data_eventos['coord.inicial'].value_counts()

17.0    55
8.0     53
11.0    43
14.0    40
4.0     34
7.0     26
18.0    26
3.0     26
15.0    25
10.0    23
13.0    23
12.0    23
9.0     17
16.0    12
24.0    10
21.0    10
20.0     8
23.0     8
5.0      8
2.0      7
19.0     6
1.0      4
22.0     1
6.0      1
Name: coord.inicial, dtype: int64

In [102]:
data_eventos['coord.final'].value_counts()

Volver    214
17         36
14         26
15         22
18         22
11         20
16         17
8          16
10         14
13         14
12         14
21         13
9           9
4           9
7           9
23          8
24          8
20          6
3           5
19          2
22          1
2           1
Name: coord.final, dtype: int64

In [103]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [104]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [105]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [106]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,7.0,68.0,68.0,22.0,22.0
1,11.0,108.0,108.0,82.0,82.0
2,8.0,108.0,66.0,82.0,81.0
3,3.0,66.0,12.0,81.0,82.0
4,NaN,21.0,NaN,43.0,NaN
...,...,...,...,...,...
485,14.0,203.0,161.0,141.0,81.0
486,NaN,203.0,NaN,80.0,NaN
487,NaN,203.0,NaN,80.0,NaN
488,NaN,203.0,NaN,80.0,NaN
489,NaN,NaN,NaN,NaN,NaN

In [107]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    489.000000
mean     125.785276
std       71.915086
min       12.000000
25%       66.000000
50%      109.000000
75%      203.000000
max      260.000000
Name: coord.inicial.x, dtype: float64

In [108]:
# aÃ±adirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    489.000000
mean     126.503365
std       72.939459
min       -7.909287
25%       64.238084
50%      118.646230
75%      188.475612
max      270.470750
Name: coord.inicial.x, dtype: float64

In [109]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [110]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    489.000000
mean      82.364008
std       39.050283
min       18.000000
25%       80.000000
50%       81.000000
75%       83.000000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [111]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    489.000000
mean      82.899386
std       41.290904
min        0.392062
25%       63.927588
50%       81.655092
75%      100.166482
max      164.537773
Name: coord.inicial.y, dtype: float64

In [112]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [113]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [114]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [115]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,7.0,84.902533,83.778940,7.439407,27.544219
1,11.0,119.235468,103.113837,91.095038,95.459428
2,8.0,118.163083,70.837468,85.442975,98.126037
3,3.0,62.726809,28.964178,79.807722,82.941763
4,NaN,19.936075,NaN,31.117879,NaN
...,...,...,...,...,...
485,14.0,201.176631,167.487923,138.605677,61.402357
486,NaN,191.360645,NaN,68.003488,NaN
487,NaN,211.264532,NaN,69.681171,NaN
488,NaN,184.894271,NaN,73.411849,NaN
489,NaN,NaN,NaN,NaN,NaN

In [116]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0         85.0,7.0
1       119.0,91.0
2       118.0,85.0
3        63.0,80.0
4        20.0,31.0
          ...
485    201.0,139.0
486     191.0,68.0
487     211.0,70.0
488     185.0,73.0
489        nan,nan
Length: 490, dtype: object

In [117]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [118]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [119]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0            85,7       84,28
1          119,91      103,95
2          118,85       71,98
3           63,80       29,83
4           20,31        None
..            ...         ...
485       201,139      167,61
486        191,68        None
487        211,70        None
488        185,73        None
489          None        None

[490 rows x 2 columns]

# Escribir tabla filtros

In [122]:
data_eventos = data_eventos[~data_eventos['tiempo'].isna()].reset_index(drop=True)

In [123]:
data_eventos.tail()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
484,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:28:37,02:28:37,0.0,...,0,0,0,0,0,18.0,118.268832,209.117388,148.723300,159.686427
485,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pase,NaN,02:28:36,02:28:36,0.0,...,0,0,0,0,0,14.0,201.176631,167.487923,138.605677,61.402357
486,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,falta,NaN,02:28:42,02:28:42,0.0,...,0,0,0,0,0,NaN,191.360645,NaN,68.003488,NaN
487,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,pelota parada,NaN,02:29:29,02:29:29,0.0,...,0,0,0,0,0,NaN,211.264532,NaN,69.681171,NaN
488,2022/04/05,Velez,VELEZ RESERVA,20:18:22,22:53:32,perdida,NaN,02:29:30,02:29:30,0.0,...,0,0,0,0,0,NaN,184.894271,NaN,73.411849,NaN

In [239]:
data_eventos.to_csv("../Datos generados para la app/reserva22-fecha5-velez-tabla_filtros.csv",index=False)

In [ ]:
data_eventos.info()

In [ ]:
data_eventos[[col for col in data_eventos.columns if 'perdida' in col]].sum()

In [ ]:
data_eventos[data_eventos['Jugador.1']==3][['Jugador.1','coord.inicial','coord.final','Subevento']+[col for col in data_eventos.columns if 'perdida' in col]]

# Agregar

ARQUERO
- que siempre que hay una atajada haya un remate antes para saber desde donde proviene
- que el remate antes de gol o atajada tenga coord inicio y final
- agregar rebote
- ver como poner los mano a mano
- INTERCEPCIONES (poner antes de donde proviene del rival)

In [ ]:
data_eventos.info()

In [ ]:
data_eventos.iloc[:,12:].apply(lambda x: x.sum(), axis='rows')