In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import glob
import os
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [2]:
# merging the files
files_joined = os.path.join('..\\..\\datos etiquetas\\Fecha 13 - Aldosivi', "*.csv")

# Return a list of all joined files
list_files = glob.glob(files_joined)

#print("** Merging multiple csv files into a single pandas dataframe **")
# Merge files by joining all files
data = pd.concat(map(pd.read_csv, list_files), ignore_index=True)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   203 non-null    object
 1   Event                203 non-null    object
 2   Session Name         203 non-null    object
 3   Session Start        203 non-null    object
 4   Session End          203 non-null    object
 5   Tag Description      203 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            203 non-null    object
 8   Tag End              203 non-null    object
 9   Tag Duration (secs)  203 non-null    float64
 10  Zonas                203 non-null    int64
 11  Categoria            203 non-null    object
 12  Jugador2             46 non-null     float64
 13  Jugador              203 non-null    int64
 14  Zonas_final          202 non-null    object
 15  Optional Column      0 non-null      float64
dtypes: float64(4), int64(2), object(10)
memory usage: 25.5+ KB

In [4]:
data.columns = ['Session Start Date','partido','tiempo','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Optional Column']

In [5]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [6]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   203 non-null    object
 1   partido              203 non-null    object
 2   tiempo               203 non-null    object
 3   Session Start        203 non-null    object
 4   Session End          203 non-null    object
 5   Evento               203 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            203 non-null    object
 8   Tag End              203 non-null    object
 9   Tag Duration (secs)  203 non-null    float64
 10  coord inicial        203 non-null    float64
 11  Subevento            203 non-null    object
 12  Jugador 2            46 non-null     float64
 13  Jugador 1            203 non-null    float64
 14  coord final          202 non-null    object
 15  Optional Column      0 non-null      float64
 16  segundos             203 non-null    float64
dtypes: float64(7), object(10)
memory usage: 27.2+ KB

In [8]:
data

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),coord inicial,Subevento,Jugador 2,Jugador 1,coord final,Optional Column,segundos
0,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Perdida,NaN,00:22:43,00:22:43,0.0,8.0,Error tecnico,9.0,2.0,17,NaN,1363.0
1,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Duelo,NaN,00:23:10,00:23:10,0.0,13.0,Disputa suelo,NaN,7.0,Volver,NaN,1390.0
2,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Recuperacion,NaN,00:23:11,00:23:11,0.0,13.0,Robo,NaN,7.0,Volver,NaN,1391.0
3,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Pelota parada,NaN,00:24:43,00:24:43,0.0,16.0,Lateral largo,9.0,3.0,19,NaN,1483.0
4,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Recuperacion,NaN,00:25:19,00:25:19,0.0,11.0,Encontrada,NaN,9.0,Volver,NaN,1519.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Pelota parada,NaN,02:10:42,02:10:42,0.0,6.0,Lateral largo,NaN,4.0,Volver,NaN,7842.0
200,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Perdida,NaN,02:10:41,02:10:41,0.0,6.0,Interceptado,NaN,4.0,Volver,NaN,7841.0
201,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Duelo,NaN,02:13:02,02:13:02,0.0,12.0,Gambeta a favor,NaN,18.0,Volver,NaN,7982.0
202,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,Pelota parada,NaN,02:13:53,02:13:53,0.0,18.0,Tiro libre,22.0,18.0,21,NaN,8033.0
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [9]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [10]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        18
              disputa suelo                19
              gambeta a favor              17
              pivote                        1
pelota parada lateral corto                 1
              lateral largo                13
              tiro de esquina               4
              tiro libre                   11
perdida       atajada                       3
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        11
              error tecnico                14
              intercepcion aereo            2
              interceptado                 25
              robo                          1
recuperacion  duelo                         2
              encontrada                   17
              intercepcion                  4
              intercepcion aereo            7
              intercepcion anticipo         6
              robo                         15

In [11]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                               cantidad
Jugador 1 Evento        Subevento
1.0       pelota parada tiro libre                    2
          perdida       balon afuera lateral          1
                        interceptado                  1
          recuperacion  encontrada                    3
                        intercepcion aereo            1
...                                                 ...
18.0      perdida       interceptado                  1
          recuperacion  intercepcion anticipo         1
19.0      perdida       balon afuera lateral          2
                        duelo                         1
          recuperacion  encontrada                    2

[110 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [12]:
data_eventos = data.copy()
data_eventos.shape

(204, 17)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [13]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
data_eventos.loc[data_eventos['remate-Gol'] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol]
Index: []

In [14]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera]
Index: []

In [15]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco]
Index: []

In [16]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado]
Index: []

[0 rows x 21 columns]

In [17]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza]
Index: []

[0 rows x 22 columns]

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [18]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

Empty DataFrame
Columns: [cantidad]
Index: []

In [19]:
data[(data.Evento=='pase')]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos]
Index: []

In [20]:
data_eventos.head()

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 2,Jugador 1,coord final,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
0,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:22:43,00:22:43,0.0,...,9.0,2.0,17,NaN,1363.0,0,0,0,0,0
1,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:23:10,00:23:10,0.0,...,NaN,7.0,Volver,NaN,1390.0,0,0,0,0,0
2,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:23:11,00:23:11,0.0,...,NaN,7.0,Volver,NaN,1391.0,0,0,0,0,0
3,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:24:43,00:24:43,0.0,...,9.0,3.0,19,NaN,1483.0,0,0,0,0,0
4,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:25:19,00:25:19,0.0,...,NaN,9.0,Volver,NaN,1519.0,0,0,0,0,0

In [21]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''
colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia]
Index: []

[0 rows x 23 columns]

In [22]:
##completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='centro aereo') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='bloqueado'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) | (data_eventos.loc[i+1,'Subevento'] == 'offside' ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado]
Index: []

[0 rows x 24 columns]

In [23]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

Series([], Name: Subevento, dtype: int64)

In [24]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado]
Index: []

[0 rows x 25 columns]

In [25]:
#fuera
'''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

colname = 'pase-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera]
Index: []

[0 rows x 26 columns]

In [26]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida') | (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente]
Index: []

[0 rows x 27 columns]

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [27]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        18
              disputa suelo                19
              gambeta a favor              17
              pivote                        1
pelota parada lateral corto                 1
              lateral largo                13
              tiro de esquina               4
              tiro libre                   11
perdida       atajada                       3
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        11
              error tecnico                14
              intercepcion aereo            2
              interceptado                 25
              robo                          1
recuperacion  duelo                         2
              encontrada                   17
              intercepcion                  4
              intercepcion aereo            7
              intercepcion anticipo         6
              robo                         15

In [28]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 28 columns]

In [29]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado]
Index: []

[0 rows x 29 columns]

In [30]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado]
Index: []

[0 rows x 30 columns]

In [31]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 31 columns]

In [32]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 32 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [33]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        18
              disputa suelo                19
              gambeta a favor              17
              pivote                        1
pelota parada lateral corto                 1
              lateral largo                13
              tiro de esquina               4
              tiro libre                   11
perdida       atajada                       3
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        11
              error tecnico                14
              intercepcion aereo            2
              interceptado                 25
              robo                          1
recuperacion  duelo                         2
              encontrada                   17
              intercepcion                  4
              intercepcion aereo            7
              intercepcion anticipo         6
              robo                         15

In [34]:
dejar_index= []
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo'):
        dejar_index.append(i-1)
        dejar_index.append(i)
        dejar_index.append(i+1)
data_eventos.loc[dejar_index].head(100)

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Asistencia,pase-Completado,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera
0,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:22:43,00:22:43,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:23:10,00:23:10,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:23:11,00:23:11,0.0,...,0,0,0,0,0,0,0,0,0,0
4,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:25:19,00:25:19,0.0,...,0,0,0,0,0,0,0,0,0,0
5,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:25:29,00:25:29,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:31:28,01:31:28,0.0,...,0,0,0,0,0,0,0,0,0,0
122,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:33:22,01:33:22,0.0,...,0,0,0,0,0,0,0,0,0,0
123,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:33:58,01:33:58,0.0,...,0,0,0,0,0,0,0,0,0,0
124,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:34:11,01:34:11,0.0,...,0,0,0,0,0,0,0,0,0,0
124,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:34:11,01:34:11,0.0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1


data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
9,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:27:24,00:27:24,0.0,...,0,0,0,0,0,0,0,0,0,1
17,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:31:04,00:31:04,0.0,...,0,0,0,0,0,0,0,0,0,1
27,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:37:33,00:37:33,0.0,...,0,0,0,0,0,0,0,0,0,1
55,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:52:08,00:52:08,0.0,...,0,0,0,0,0,0,0,0,0,1
95,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:06:22,01:06:22,0.0,...,0,0,0,0,0,0,0,0,0,1
97,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:06:30,01:06:30,0.0,...,0,0,0,0,0,0,0,0,0,1
101,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:08:29,01:08:29,0.0,...,0,0,0,0,0,0,0,0,0,1
109,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:27:01,01:27:01,0.0,...,0,0,0,0,0,0,0,0,0,1
127,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:36:28,01:36:28,0.0,...,0,0,0,0,0,0,0,0,0,1
136,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:38:47,01:38:47,0.0,...,0,0,0,0,0,0,0,0,0,1
145,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:41:37,01:41:37,0.0,...,0,0,0,0,0,0,0,0,0,1
147,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:42:07,01:42:07,0.0,...,0,0,0,0,0,0,0,0,0,1
151,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:44:10,01:44:10,0.0,...,0,0,0,0,0,0,0,0,0,1
157,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:47:22,01:47:22,0.0,...,0,0,0,0,0,0,0,0,0,1
190,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:07:16,02:07:16,0.0,...,0,0,0,0,0,0,0,0,0,1

In [36]:
data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Interceptado,pase-Fuera,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado
18,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:31:23,00:31:23,0.0,...,0,0,0,0,0,0,0,0,1,0
60,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:52:40,00:52:40,0.0,...,0,0,0,0,0,0,0,0,1,0
91,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:04:21,01:04:21,0.0,...,0,0,0,0,0,0,0,0,1,0

In [37]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
5,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:25:29,00:25:29,0.0,...,0,0,0,0,0,0,0,0,1,0
28,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:38:49,00:38:49,0.0,...,0,0,0,0,0,0,0,0,1,0
132,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:37:08,01:37:08,0.0,...,0,0,0,0,0,0,0,0,1,0
138,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:39:13,01:39:13,0.0,...,0,0,0,0,0,0,0,0,1,0
194,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:07:53,02:07:53,0.0,...,0,0,0,0,0,0,0,0,1,0

In [38]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada
1,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:23:10,00:23:10,0.0,...,0,0,0,0,0,0,0,0,0,1
12,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:27:41,00:27:41,0.0,...,0,0,0,0,0,0,0,0,0,1
30,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:38:52,00:38:52,0.0,...,0,0,0,0,0,0,0,0,0,1
34,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:39:27,00:39:27,0.0,...,0,0,0,0,0,0,0,0,0,1
72,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:57:17,00:57:17,0.0,...,0,0,0,0,0,0,0,0,0,1
87,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:03:03,01:03:03,0.0,...,0,0,0,0,0,0,0,0,0,1
106,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:26:25,01:26:25,0.0,...,0,0,0,0,0,0,0,0,0,1
112,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:29:01,01:29:01,0.0,...,0,0,0,0,0,0,0,0,0,1
117,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:31:21,01:31:21,0.0,...,0,0,0,0,0,0,0,0,0,1
142,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:41:01,01:41:01,0.0,...,0,0,0,0,0,0,0,0,0,1
172,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:58:10,01:58:10,0.0,...,0,0,0,0,0,0,0,0,0,1
179,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:00:02,02:00:02,0.0,...,0,0,0,0,0,0,0,0,0,1
184,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:02:33,02:02:33,0.0,...,0,0,0,0,0,0,0,0,0,1
196,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:08:04,02:08:04,0.0,...,0,0,0,0,0,0,0,0,0,1

In [39]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [40]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 38 columns]

In [41]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada
40,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:45:13,00:45:13,0.0,...,0,0,0,0,0,0,0,0,1,0
80,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:59:54,00:59:54,0.0,...,0,0,0,0,0,0,0,0,1,0

In [42]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,centro-Bloqueado,centro-Fuera,duelo-Aereo-Perdido,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada
32,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:39:13,00:39:13,0.0,...,0,0,0,0,0,0,0,0,0,1
33,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:39:20,00:39:20,0.0,...,0,0,0,0,0,0,0,0,0,1
49,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:49:10,00:49:10,0.0,...,0,0,0,0,0,0,0,0,0,1
57,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:52:12,00:52:12,0.0,...,0,0,0,0,0,0,0,0,0,1
77,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:58:11,00:58:11,0.0,...,0,0,0,0,0,0,0,0,0,1
105,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:25:59,01:25:59,0.0,...,0,0,0,0,0,0,0,0,0,1
115,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:29:53,01:29:53,0.0,...,0,0,0,0,0,0,0,0,0,1
119,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:31:25,01:31:25,0.0,...,0,0,0,0,0,0,0,0,0,1
123,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:33:58,01:33:58,0.0,...,0,0,0,0,0,0,0,0,0,1
125,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:35:25,01:35:25,0.0,...,0,0,0,0,0,0,0,0,0,1
128,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,01:36:43,01:36:43,0.0,...,0,0,0,0,0,0,0,0,0,1
181,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:00:06,02:00:06,0.0,...,0,0,0,0,0,0,0,0,0,1
182,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:00:14,02:00:14,0.0,...,0,0,0,0,0,0,0,0,0,1
191,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:07:28,02:07:28,0.0,...,0,0,0,0,0,0,0,0,0,1
201,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:13:02,02:13:02,0.0,...,0,0,0,0,0,0,0,0,0,1

In [43]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 42 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [51]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        31
              disputa suelo                46
              gambeta a favor              13
falta         hecha                         1
pelota parada lateral corto                10
              lateral largo                24
              tiro de esquina               3
              tiro libre                   13
perdida       atajada                       3
              balon afuera fondo            8
              balon afuera lateral          9
              duelo                        43
              error tecnico                17
              interceptado                 20
              robo                          6
recuperacion  duelo                        15
              encontrada                   32
              intercepcion                 10
              intercepcion aereo           10
              intercepcion anticipo         8
              robo                         10

In [44]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida]
Index: []

[0 rows x 43 columns]

In [45]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida]
Index: []

[0 rows x 44 columns]

In [46]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 45 columns]

In [47]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 46 columns]

In [48]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside]
Index: []

[0 rows x 47 columns]

In [49]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla]
Index: []

[0 rows x 48 columns]

In [50]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i+1,'Evento']=='tarjeta') & (data_eventos.loc[i+1,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja]
Index: []

[0 rows x 49 columns]

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [59]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        31
              disputa suelo                46
              gambeta a favor              13
falta         hecha                         1
pelota parada lateral corto                10
              lateral largo                24
              tiro de esquina               3
              tiro libre                   13
perdida       atajada                       3
              balon afuera fondo            8
              balon afuera lateral          9
              duelo                        43
              error tecnico                17
              interceptado                 20
              robo                          6
recuperacion  duelo                        15
              encontrada                   32
              intercepcion                 10
              intercepcion aereo           10
              intercepcion anticipo         8
              robo                         10

In [51]:
colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo
2,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:23:11,00:23:11,0.0,...,0,0,0,0,0,0,0,0,0,1
13,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:27:41,00:27:41,0.0,...,0,0,0,0,0,0,0,0,0,1
31,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:38:53,00:38:53,0.0,...,0,0,0,0,0,0,0,0,0,1
45,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:47:40,00:47:40,0.0,...,0,0,0,0,0,0,0,0,0,1
62,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:52:48,00:52:48,0.0,...,0,0,0,0,0,0,0,0,0,1
73,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:57:18,00:57:18,0.0,...,0,0,0,0,0,0,0,0,0,1
108,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:26:52,01:26:52,0.0,...,0,0,0,0,0,0,0,0,0,1
114,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:29:50,01:29:50,0.0,...,0,0,0,0,0,0,0,0,0,1
118,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:31:23,01:31:23,0.0,...,0,0,0,0,0,0,0,0,0,1
143,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:41:03,01:41:03,0.0,...,0,0,0,0,0,0,0,0,0,1
163,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:54:50,01:54:50,0.0,...,0,0,0,0,0,0,0,0,0,1
173,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:58:11,01:58:11,0.0,...,0,0,0,0,0,0,0,0,0,1
180,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,02:00:02,02:00:02,0.0,...,0,0,0,0,0,0,0,0,0,1
185,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,02:02:37,02:02:37,0.0,...,0,0,0,0,0,0,0,0,0,1
197,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,02:08:05,02:08:05,0.0,...,0,0,0,0,0,0,0,0,0,1

In [52]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada
4,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:25:19,00:25:19,0.0,...,0,0,0,0,0,0,0,0,0,1
7,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:25:35,00:25:35,0.0,...,0,0,0,0,0,0,0,0,0,1
15,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:30:16,00:30:16,0.0,...,0,0,0,0,0,0,0,0,0,1
20,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:31:29,00:31:29,0.0,...,0,0,0,0,0,0,0,0,0,1
48,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:49:06,00:49:06,0.0,...,0,0,0,0,0,0,0,0,0,1
53,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:51:48,00:51:48,0.0,...,0,0,0,0,0,0,0,0,0,1
64,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:52:58,00:52:58,0.0,...,0,0,0,0,0,0,0,0,0,1
67,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:55:43,00:55:43,0.0,...,0,0,0,0,0,0,0,0,0,1
100,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:08:14,01:08:14,0.0,...,0,0,0,0,0,0,0,0,0,1
102,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:25:37,01:25:37,0.0,...,0,0,0,0,0,0,0,0,0,1
104,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:25:58,01:25:58,0.0,...,0,0,0,0,0,0,0,0,0,1
111,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:28:25,01:28:25,0.0,...,0,0,0,0,0,0,0,0,0,1
140,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:39:55,01:39:55,0.0,...,0,0,0,0,0,0,0,0,0,1
153,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:44:56,01:44:56,0.0,...,0,0,0,0,0,0,0,0,0,1
167,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:56:31,01:56:31,0.0,...,0,0,0,0,0,0,0,0,0,1
175,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:58:48,01:58:48,0.0,...,0,0,0,0,0,0,0,0,0,1
193,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,02:07:50,02:07:50,0.0,...,0,0,0,0,0,0,0,0,0,1

In [53]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo
25,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:36:37,00:36:37,0.0,...,0,0,0,0,0,0,0,0,0,1
70,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:56:36,00:56:36,0.0,...,0,0,0,0,0,0,0,0,0,1
86,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:02:58,01:02:58,0.0,...,0,0,0,0,0,0,0,0,0,1
177,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:59:47,01:59:47,0.0,...,0,0,0,0,0,0,0,0,0,1

In [54]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo
56,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:52:09,00:52:09,0.0,...,0,0,0,0,0,0,0,0,0,1
83,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:00:59,01:00:59,0.0,...,0,0,0,0,0,0,0,0,0,1
93,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:05:17,01:05:17,0.0,...,0,0,0,0,0,0,0,0,0,1
134,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:37:26,01:37:26,0.0,...,0,0,0,0,0,0,0,0,0,1
148,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:42:08,01:42:08,0.0,...,0,0,0,0,0,0,0,0,0,1
155,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:46:20,01:46:20,0.0,...,0,0,0,0,0,0,0,0,0,1
188,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,02:05:36,02:05:36,0.0,...,0,0,0,0,0,0,0,0,0,1

In [55]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo
75,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:57:42,00:57:42,0.0,...,0,0,0,0,0,0,0,0,0,1
79,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:59:46,00:59:46,0.0,...,0,0,0,0,0,0,0,0,0,1
130,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:36:49,01:36:49,0.0,...,0,0,0,0,0,0,0,0,0,1
150,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:43:05,01:43:05,0.0,...,0,0,0,0,0,0,0,0,0,1
165,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:54:57,01:54:57,0.0,...,0,0,0,0,0,0,0,0,0,1
170,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,01:57:20,01:57:20,0.0,...,0,0,0,0,0,0,0,0,0,1

In [56]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if (data_eventos.loc[i+1,'Evento'] == 'recuperacion') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo]
Index: []

[0 rows x 55 columns]

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [135]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                           cantidad
Evento        Subevento
duelo         aereo                              18
              disputa suelo                      46
              gambeta a favor                    20
pelota parada lateral corto                       8
              lateral largo                      11
              tiro de esquina                     6
              tiro libre                          4
perdida       atajada                             4
              balon afuera fondo                  9
              balon afuera lateral                9
              duelo                              22
              error tecnico                       9
              intercepcion aereo                  5
              interceptado                       20
              robo                                1
recuperacion  duelo                               6
              intercepcion                        1
              intercepcion aereo                  4
              intercepcion anticipo               3
              intercepcion anticipo aereo         1
              robo                               17

In [57]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
59,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:52:35,00:52:35,0.0,...,0,0,0,0,0,0,0,0,1,0
90,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:04:19,01:04:19,0.0,...,0,0,0,0,0,0,0,0,1,0
131,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:37:04,01:37:04,0.0,...,0,0,0,0,0,0,0,0,1,0

In [58]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,falta-Tarjeta-amarilla,falta-Tarjeta-roja,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado
3,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:24:43,00:24:43,0.0,...,0,0,0,0,0,0,0,0,0,1
21,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:32:12,00:32:12,0.0,...,0,0,0,0,0,0,0,0,0,1
36,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:40:07,00:40:07,0.0,...,0,0,0,0,0,0,0,0,0,1
46,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:48:13,00:48:13,0.0,...,0,0,0,0,0,0,0,0,0,1
50,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:49:37,00:49:37,0.0,...,0,0,0,0,0,0,0,0,0,1
51,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:50:02,00:50:02,0.0,...,0,0,0,0,0,0,0,0,0,1
65,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:54:02,00:54:02,0.0,...,0,0,0,0,0,0,0,0,0,1
121,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:33:12,01:33:12,0.0,...,0,0,0,0,0,0,0,0,0,1
144,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:41:34,01:41:34,0.0,...,0,0,0,0,0,0,0,0,0,1
168,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:57:00,01:57:00,0.0,...,0,0,0,0,0,0,0,0,0,1
199,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:10:42,02:10:42,0.0,...,0,0,0,0,0,0,0,0,0,1

In [59]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado
84,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:02:07,01:02:07,0.0,...,0,0,0,0,0,0,0,0,1,0

In [60]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Robo,recuperacion-Encontrada,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado
38,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:42:15,00:42:15,0.0,...,0,0,0,0,0,0,0,0,0,1
52,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:50:42,00:50:42,0.0,...,0,0,0,0,0,0,0,0,0,1
159,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:49:16,01:49:16,0.0,...,0,0,0,0,0,0,0,0,0,1

In [61]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
23,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:35:56,00:35:56,0.0,...,0,0,0,0,0,0,0,0,1,0
43,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:47:32,00:47:32,0.0,...,0,0,0,0,0,0,0,0,1,0
68,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:56:24,00:56:24,0.0,...,0,0,0,0,0,0,0,0,1,0
88,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:03:38,01:03:38,0.0,...,0,0,0,0,0,0,0,0,1,0
98,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:07:50,01:07:50,0.0,...,0,0,0,0,0,0,0,0,1,0
186,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:03:32,02:03:32,0.0,...,0,0,0,0,0,0,0,0,1,0

In [62]:
data_eventos.loc[data_eventos[colname2] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
42,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:46:43,00:46:43,0.0,...,0,0,0,0,0,0,0,0,0,1
156,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:47:21,01:47:21,0.0,...,0,0,0,0,0,0,0,0,0,1
158,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,01:48:38,01:48:38,0.0,...,0,0,0,0,0,0,0,0,0,1
189,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:07:16,02:07:16,0.0,...,0,0,0,0,0,0,0,0,0,1
202,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:13:53,02:13:53,0.0,...,0,0,0,0,0,0,0,0,0,1

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [63]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        18
              disputa suelo                19
              gambeta a favor              17
              pivote                        1
pelota parada lateral corto                 1
              lateral largo                13
              tiro de esquina               4
              tiro libre                   11
perdida       atajada                       3
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        11
              error tecnico                14
              intercepcion aereo            2
              interceptado                 25
              robo                          1
recuperacion  duelo                         2
              encontrada                   17
              intercepcion                  4
              intercepcion aereo            7
              intercepcion anticipo         6
              robo                         15

In [64]:
#gambeta a favor

colname = 'perdida-Gambeta-favor'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor
40,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:45:13,00:45:13,0.0,...,0,0,0,0,0,0,0,0,0,1

In [65]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='robo'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo
154,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:45:10,01:45:10,0.0,...,0,0,0,0,0,0,0,0,0,1

In [66]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
        data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion
8,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:26:50,00:26:50,0.0,...,0,0,0,0,0,0,0,0,0,1
14,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:27:43,00:27:43,0.0,...,0,0,0,0,0,0,0,0,0,1
24,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:35:59,00:35:59,0.0,...,0,0,0,0,0,0,0,0,0,1
26,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:36:51,00:36:51,0.0,...,0,0,0,0,0,0,0,0,0,1
37,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:40:09,00:40:09,0.0,...,0,0,0,0,0,0,0,0,0,1
44,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:47:35,00:47:35,0.0,...,0,0,0,0,0,0,0,0,0,1
47,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:48:14,00:48:14,0.0,...,0,0,0,0,0,0,0,0,0,1
54,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:52:05,00:52:05,0.0,...,0,0,0,0,0,0,0,0,0,1
58,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:52:15,00:52:15,0.0,...,0,0,0,0,0,0,0,0,0,1
63,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:52:54,00:52:54,0.0,...,0,0,0,0,0,0,0,0,0,1
69,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:56:24,00:56:24,0.0,...,0,0,0,0,0,0,0,0,0,1
71,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:56:43,00:56:43,0.0,...,0,0,0,0,0,0,0,0,0,1
78,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:58:21,00:58:21,0.0,...,0,0,0,0,0,0,0,0,0,1
85,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:02:12,01:02:12,0.0,...,0,0,0,0,0,0,0,0,0,1
89,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:03:43,01:03:43,0.0,...,0,0,0,0,0,0,0,0,0,1
94,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:05:40,01:05:40,0.0,...,0,0,0,0,0,0,0,0,0,1
110,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:27:03,01:27:03,0.0,...,0,0,0,0,0,0,0,0,0,1
129,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:36:44,01:36:44,0.0,...,0,0,0,0,0,0,0,0,0,1
135,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:37:47,01:37:47,0.0,...,0,0,0,0,0,0,0,0,0,1
137,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:38:58,01:38:58,0.0,...,0,0,0,0,0,0,0,0,0,1
146,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:41:41,01:41:41,0.0,...,0,0,0,0,0,0,0,0,0,1
164,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:54:53,01:54:53,0.0,...,0,0,0,0,0,0,0,0,0,1
171,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:58:05,01:58:05,0.0,...,0,0,0,0,0,0,0,0,0,1
174,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:58:15,01:58:15,0.0,...,0,0,0,0,0,0,0,0,0,1
178,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:59:52,01:59:52,0.0,...,0,0,0,0,0,0,0,0,0,1
192,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,02:07:37,02:07:37,0.0,...,0,0,0,0,0,0,0,0,0,1
200,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,02:10:41,02:10:41,0.0,...,0,0,0,0,0,0,0,0,0,1

In [67]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico
0,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:22:43,00:22:43,0.0,...,0,0,0,0,0,0,0,0,0,1
16,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:30:19,00:30:19,0.0,...,0,0,0,0,0,0,0,0,0,1
22,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:34:06,00:34:06,0.0,...,0,0,0,0,0,0,0,0,0,1
74,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:57:21,00:57:21,0.0,...,0,0,0,0,0,0,0,0,0,1
82,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:00:48,01:00:48,0.0,...,0,0,0,0,0,0,0,0,0,1
116,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:29:56,01:29:56,0.0,...,0,0,0,0,0,0,0,0,0,1
120,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:31:28,01:31:28,0.0,...,0,0,0,0,0,0,0,0,0,1
124,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:34:11,01:34:11,0.0,...,0,0,0,0,0,0,0,0,0,1
126,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:35:36,01:35:36,0.0,...,0,0,0,0,0,0,0,0,0,1
149,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:42:13,01:42:13,0.0,...,0,0,0,0,0,0,0,0,0,1
152,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:44:19,01:44:19,0.0,...,0,0,0,0,0,0,0,0,0,1
162,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:51:39,01:51:39,0.0,...,0,0,0,0,0,0,0,0,0,1
169,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:57:11,01:57:11,0.0,...,0,0,0,0,0,0,0,0,0,1
176,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:58:53,01:58:53,0.0,...,0,0,0,0,0,0,0,0,0,1

In [68]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera
11,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:27:27,00:27:27,0.0,...,0,0,0,0,0,0,0,0,0,1
35,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:39:29,00:39:29,0.0,...,0,0,0,0,0,0,0,0,0,1
39,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:42:17,00:42:17,0.0,...,0,0,0,0,0,0,0,0,0,1
66,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:54:12,00:54:12,0.0,...,0,0,0,0,0,0,0,0,0,1
81,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:00:18,01:00:18,0.0,...,0,0,0,0,0,0,0,0,0,1
99,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:08:00,01:08:00,0.0,...,0,0,0,0,0,0,0,0,0,1
103,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:25:52,01:25:52,0.0,...,0,0,0,0,0,0,0,0,0,1
107,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:26:26,01:26:26,0.0,...,0,0,0,0,0,0,0,0,0,1
113,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:29:02,01:29:02,0.0,...,0,0,0,0,0,0,0,0,0,1
122,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:33:22,01:33:22,0.0,...,0,0,0,0,0,0,0,0,0,1
166,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:55:12,01:55:12,0.0,...,0,0,0,0,0,0,0,0,0,1
187,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,02:03:44,02:03:44,0.0,...,0,0,0,0,0,0,0,0,0,1

In [69]:
#situacion rival

colname = 'perdida-Situacion-rival'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='situacion rival'):
        if (data_eventos.loc[i,'Subevento']=='directa'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival]
Index: []

[0 rows x 67 columns]

In [70]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='perdida'):
        if (data_eventos.loc[i,'Subevento']=='atajada'):
            data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,partido,tiempo,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado,perdida-Gambeta-favor,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Situacion-rival,perdida-Atajada
76,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:57:54,00:57:54,0.0,...,0,0,0,0,0,0,0,0,0,1
160,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,01:49:18,01:49:18,0.0,...,0,0,0,0,0,0,0,0,0,1
183,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,02:00:32,02:00:32,0.0,...,0,0,0,0,0,0,0,0,0,1

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [71]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                     cantidad
Evento        Subevento
duelo         aereo                        18
              disputa suelo                19
              gambeta a favor              17
              pivote                        1
pelota parada lateral corto                 1
              lateral largo                13
              tiro de esquina               4
              tiro libre                   11
perdida       atajada                       3
              balon afuera fondo            6
              balon afuera lateral          6
              duelo                        11
              error tecnico                14
              intercepcion aereo            2
              interceptado                 25
              robo                          1
recuperacion  duelo                         2
              encontrada                   17
              intercepcion                  4
              intercepcion aereo            7
              intercepcion anticipo         6
              robo                         15

In [72]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable]
Index: []

[0 rows x 70 columns]

In [73]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in data_eventos.loc[i,'Subevento']) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            if ('remate' in data_eventos.loc[i-1,'Evento']):
                data_eventos.loc[i-1,colname] = 1
            elif ('remate' in data_eventos.loc[i-2,'Evento']):
                data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada]
Index: []

[0 rows x 71 columns]

In [153]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [74]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 72 columns]

In [75]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 73 columns]

In [76]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 74 columns]

In [77]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano]
Index: []

[0 rows x 75 columns]

In [78]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie]
Index: []

[0 rows x 76 columns]

In [79]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']=='1'):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, partido, tiempo, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), coord inicial, Subevento, Jugador 2, Jugador 1, coord final, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Interceptado, pase-Fuera, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta-favor, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Situacion-rival, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 77 columns]

In [80]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [81]:
data_eventos.iloc[:,:20]

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),coord.inicial,Subevento,Jugador.2,Jugador.1,coord.final,Optional.Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco
0,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,00:22:43,00:22:43,0.0,8.0,error tecnico,9.0,2.0,17,NaN,1363.0,0,0,0
1,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,00:23:10,00:23:10,0.0,13.0,disputa suelo,NaN,7.0,Volver,NaN,1390.0,0,0,0
2,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:23:11,00:23:11,0.0,13.0,robo,NaN,7.0,Volver,NaN,1391.0,0,0,0
3,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,00:24:43,00:24:43,0.0,16.0,lateral largo,9.0,3.0,19,NaN,1483.0,0,0,0
4,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,recuperacion,NaN,00:25:19,00:25:19,0.0,11.0,encontrada,NaN,9.0,Volver,NaN,1519.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:10:42,02:10:42,0.0,6.0,lateral largo,NaN,4.0,Volver,NaN,7842.0,0,0,0
200,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,02:10:41,02:10:41,0.0,6.0,interceptado,NaN,4.0,Volver,NaN,7841.0,0,0,0
201,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:13:02,02:13:02,0.0,12.0,gambeta a favor,NaN,18.0,Volver,NaN,7982.0,0,0,0
202,2022/05/02,ALDOSIVICOMPLETO,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:13:53,02:13:53,0.0,18.0,tiro libre,22.0,18.0,21,NaN,8033.0,0,0,0
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [82]:
data_eventos['coord.inicial'].value_counts()

17.0    21
7.0     18
16.0    17
13.0    16
11.0    16
9.0     16
14.0    16
10.0    13
2.0     10
19.0     9
24.0     8
8.0      8
18.0     7
15.0     6
12.0     5
6.0      4
21.0     3
4.0      3
20.0     2
5.0      2
1.0      2
3.0      1
Name: coord.inicial, dtype: int64

In [83]:
data_eventos['coord.final'].value_counts()

Volver    156
17          7
18          6
21          6
20          5
16          4
11          2
14          2
23          2
15          2
13          2
19          2
10          2
22          1
1           1
12          1
24          1
Name: coord.final, dtype: int64

In [84]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [85]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [86]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [87]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,17.0,66.0,203.0,81.0,80.0
1,NaN,162.0,NaN,21.0,NaN
2,NaN,162.0,NaN,21.0,NaN
3,19.0,205.0,251.0,23.0,20.0
4,NaN,108.0,NaN,82.0,NaN
...,...,...,...,...,...
199,NaN,20.0,NaN,147.0,NaN
200,NaN,20.0,NaN,147.0,NaN
201,NaN,105.0,NaN,138.0,NaN
202,21.0,203.0,238.0,141.0,80.0
203,NaN,NaN,NaN,NaN,NaN

In [88]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    203.000000
mean     136.546798
std       71.291839
min       12.000000
25%       68.000000
50%      160.000000
75%      203.000000
max      251.000000
Name: coord.inicial.x, dtype: float64

In [89]:
# añadirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    203.000000
mean     136.743560
std       71.536798
min        5.304146
25%       78.237891
50%      148.315663
75%      197.569690
max      269.616035
Name: coord.inicial.x, dtype: float64

In [90]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [91]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    203.000000
mean      71.108374
std       46.543050
min       18.000000
25%       22.000000
50%       80.000000
75%       82.500000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [92]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    203.000000
mean      71.935292
std       48.070096
min        1.040248
25%       26.905396
50%       70.693378
75%       99.394268
max      160.054437
Name: coord.inicial.y, dtype: float64

In [93]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [94]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [95]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [96]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,17.0,84.816521,185.770536,70.538952,72.716172
1,NaN,142.256635,NaN,13.409490,NaN
2,NaN,144.935257,NaN,28.140080,NaN
3,19.0,193.443449,270.418737,21.426489,8.602968
4,NaN,97.905671,NaN,83.472949,NaN
...,...,...,...,...,...
199,NaN,30.287425,NaN,148.751597,NaN
200,NaN,39.928996,NaN,130.606836,NaN
201,NaN,93.235290,NaN,126.846103,NaN
202,21.0,199.759737,239.756377,140.868860,84.966017
203,NaN,NaN,NaN,NaN,NaN

In [97]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0        85.0,71.0
1       142.0,13.0
2       145.0,28.0
3       193.0,21.0
4        98.0,83.0
          ...
199     30.0,149.0
200     40.0,131.0
201     93.0,127.0
202    200.0,141.0
203        nan,nan
Length: 204, dtype: object

In [98]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [99]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [100]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0           85,71      186,73
1          142,13        None
2          145,28        None
3          193,21       270,9
4           98,83        None
..            ...         ...
199        30,149        None
200        40,131        None
201        93,127        None
202       200,141      240,85
203          None        None

[204 rows x 2 columns]

# Escribir tabla filtros

In [101]:
data_eventos = data_eventos[~data_eventos['partido'].isna()].reset_index(drop=True)

In [102]:
data_eventos['partido'] = 'Aldosivi'

In [103]:
data_eventos.tail()

,Session.Start.Date,partido,tiempo,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
198,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,02:09:23,02:09:23,0.0,...,0,0,0,0,0,NaN,127.521397,NaN,90.220872,NaN
199,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:10:42,02:10:42,0.0,...,0,0,0,0,0,NaN,30.287425,NaN,148.751597,NaN
200,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,perdida,NaN,02:10:41,02:10:41,0.0,...,0,0,0,0,0,NaN,39.928996,NaN,130.606836,NaN
201,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,duelo,NaN,02:13:02,02:13:02,0.0,...,0,0,0,0,0,NaN,93.235290,NaN,126.846103,NaN
202,2022/05/02,Aldosivi,ALDOSIVI_COMPLETO,15:22:33,17:43:53,pelota parada,NaN,02:13:53,02:13:53,0.0,...,0,0,0,0,0,21.0,199.759737,239.756377,140.868860,84.966017

In [104]:
data_eventos.to_csv("../Datos generados para la app/reserva22-fecha13-aldosivi-tabla_filtros.csv",index=False)

In [105]:
data_eventos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 82 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Session.Start.Date                  203 non-null    object
 1   partido                             203 non-null    object
 2   tiempo                              203 non-null    object
 3   Session.Start                       203 non-null    object
 4   Session.End                         203 non-null    object
 5   Evento                              203 non-null    object
 6   Tag.Notes                           0 non-null      float64
 7   Tag.Start                           203 non-null    object
 8   Tag.End                             203 non-null    object
 9   Tag.Duration.(secs)                 203 non-null    float64
 10  coord.inicial                       203 non-null    object
 11  Subevento                           203 non-null    object
 12  Jugador.2                           46 non-null     float64
 13  Jugador.1                           203 non-null    float64
 14  coord.final                         46 non-null     object
 15  Optional.Column                     0 non-null      float64
 16  segundos                            203 non-null    float64
 17  remate-Gol                          203 non-null    int64
 18  remate-Fuera                        203 non-null    int64
 19  remate-Al-arco                      203 non-null    int64
 20  remate-Interceptado                 203 non-null    int64
 21  remate-Cabeza                       203 non-null    int64
 22  pase-Asistencia                     203 non-null    int64
 23  pase-Completado                     203 non-null    int64
 24  pase-Interceptado                   203 non-null    int64
 25  pase-Fuera                          203 non-null    int64
 26  pase-Inteligente                    203 non-null    int64
 27  centro-Asistencia                   203 non-null    int64
 28  centro-Completado                   203 non-null    int64
 29  centro-Interceptado                 203 non-null    int64
 30  centro-Bloqueado                    203 non-null    int64
 31  centro-Fuera                        203 non-null    int64
 32  duelo-Aereo-Perdido                 203 non-null    int64
 33  duelo-Aereo-Ganado                  203 non-null    int64
 34  duelo-Disputa-suelo-Perdida         203 non-null    int64
 35  duelo-Disputa-suelo-Ganada          203 non-null    int64
 36  duelo-Gambeta-contra-Ganada         203 non-null    int64
 37  duelo-Gambeta-contra-Perdida        203 non-null    int64
 38  duelo-Gambeta-favor-Perdida         203 non-null    int64
 39  duelo-Gambeta-favor-Ganada          203 non-null    int64
 40  duelo-Pivote-Perdido                203 non-null    int64
 41  duelo-Pivote-Ganado                 203 non-null    int64
 42  falta-Cometida                      203 non-null    int64
 43  falta-Recibida                      203 non-null    int64
 44  falta-Penal-cometido                203 non-null    int64
 45  falta-Penal-recibido                203 non-null    int64
 46  falta-Offside                       203 non-null    int64
 47  falta-Tarjeta-amarilla              203 non-null    int64
 48  falta-Tarjeta-roja                  203 non-null    int64
 49  recuperacion-Robo                   203 non-null    int64
 50  recuperacion-Encontrada             203 non-null    int64
 51  recuperacion-Intercepcion-suelo     203 non-null    int64
 52  recuperacion-Intercepcion-aereo     203 non-null    int64
 53  recuperacion-Intercepcion-anticipo  203 non-null    int64
 54  recuperacion-Disputa-suelo          203 non-null    int64
 55  parado-Lateral-interceptado         203 non-null    int64
 56  parado-Lateral-completado           203 non-null    int64
 57  parado-Corner-interceptado          203 non-null    int64
 58  parado-Corner-completado            203 non-null    int64
 59  parado-Tiro-libre-incompleto        203 non-null    int64
 60  parado-Tiro-libre-completado        203 non-null    int64
 61  perdida-Gambeta-favor               203 non-null    int64
 62  perdida-Robo                        203 non-null    int64
 63  perdida-Intercepcion                203 non-null    int64
 64  perdida-Error-tecnico               203 non-null    int64
 65  perdida-Balon-fuera                 203 non-null    int64
 66  perdida-Situacion-rival             203 non-null    int64
 67  perdida-Atajada                     203 non-null    int64
 68  arquero-Gol-rival                   203 non-null    int64
 69  arquero-Gol-rival-atajable          203 non-null    int64
 70  arquero-Atajada                     203 non-null    int64
 71  arquero-Intercepcion-aerea          203 non-null    int64
 72  arquero-Intercepcion                203 non-null    int64
 73  arquero-Anticipo                    203 non-null    int64
 74  arquero-Saque-mano                  203 non-null    int64
 75  arquero-Saque-pie                   203 non-null    int64
 76  arquero-Saque-meta                  203 non-null    int64
 77  coord.final.num                     46 non-null     float64
 78  coord.inicial.x                     203 non-null    float64
 79  coord.final.x                       46 non-null     float64
 80  coord.inicial.y                     203 non-null    float64
 81  coord.final.y                       46 non-null     float64
dtypes: float64(11), int64(60), object(11)
memory usage: 130.2+ KB

In [ ]:
data_eventos[[col for col in data_eventos.columns if 'perdida' in col]].sum()

In [ ]:
data_eventos[data_eventos['Jugador.1']==3][['Jugador.1','coord.inicial','coord.final','Subevento']+[col for col in data_eventos.columns if 'perdida' in col]]

# Agregar

ARQUERO
- que siempre que hay una atajada haya un remate antes para saber desde donde proviene
- que el remate antes de gol o atajada tenga coord inicio y final
- agregar rebote
- ver como poner los mano a mano
- INTERCEPCIONES (poner antes de donde proviene del rival)

In [ ]:
data_eventos.info()

In [ ]:
data_eventos.iloc[:,12:].apply(lambda x: x.sum(), axis='rows')