In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import glob
import os
#pd.set_option('display.max_rows', 200)

# Carga de datos

In [80]:
# merging the files
files_joined = os.path.join('..\\..\\datos etiquetas\\Tem2-2022\\Fecha 9 - Barracas', "*.csv")

# Return a list of all joined files
list_files = glob.glob(files_joined)

#print("** Merging multiple csv files into a single pandas dataframe **")
# Merge files by joining all files
data = pd.concat(map(pd.read_csv, list_files), ignore_index=True)

In [81]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   245 non-null    object
 1   Event                245 non-null    object
 2   Session Name         245 non-null    object
 3   Session Start        245 non-null    object
 4   Session End          245 non-null    object
 5   Tag Description      245 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            245 non-null    object
 8   Tag End              245 non-null    object
 9   Tag Duration (secs)  245 non-null    float64
 10  Dificultad           3 non-null      object
 11  Zonas_final          245 non-null    object
 12  Jugador2             149 non-null    object
 13  Jugador              241 non-null    float64
 14  Calificacion         3 non-null      object
 15  Zonas                241 non-null    float64
 16  Categoria            241 non-null    object
 17  Optional Column      0 non-null      float64
dtypes: float64(5), object(13)
memory usage: 34.6+ KB

In [82]:
# data.columns = ['Session Start Date','partido','tiempo','Session Start',
#        'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
#        'Tag Duration (secs)','coord inicial','Subevento','Jugador 2','Jugador 1','coord final','Optional Column']

data.columns = ['Session Start Date','tiempo','partido','Session Start',
       'Session End','Evento','Tag Notes','Tag Start', 'Tag End',
       'Tag Duration (secs)','Dificultad','coord final','Jugador 2','Jugador 1','Calificacion','coord inicial','Subevento','Optional Column']

In [83]:
'''TIEMPO'''

from datetime import timedelta

def seconder(x):
    hr, mins, secs = map(float, x.split(':'))
    td = timedelta(hours= hr, minutes=mins, seconds=secs)
    return td.total_seconds()
data['segundos'] = data['Tag Start'].apply(seconder)

In [84]:
data = data.append(data.iloc[-1,:]).reset_index(drop=True)
data.loc[-1,'Evento'] = np.nan
data.loc[-1,'Subevento'] = np.nan
data = data.drop_duplicates()
data = data.reset_index(drop=True)

In [85]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Session Start Date   245 non-null    object
 1   tiempo               245 non-null    object
 2   partido              245 non-null    object
 3   Session Start        245 non-null    object
 4   Session End          245 non-null    object
 5   Evento               245 non-null    object
 6   Tag Notes            0 non-null      float64
 7   Tag Start            245 non-null    object
 8   Tag End              245 non-null    object
 9   Tag Duration (secs)  245 non-null    float64
 10  Dificultad           3 non-null      object
 11  coord final          245 non-null    object
 12  Jugador 2            149 non-null    object
 13  Jugador 1            241 non-null    float64
 14  Calificacion         3 non-null      object
 15  coord inicial        241 non-null    float64
 16  Subevento            241 non-null    object
 17  Optional Column      0 non-null      float64
 18  segundos             245 non-null    float64
dtypes: float64(6), object(13)
memory usage: 36.6+ KB

In [86]:
data

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Dificultad,coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos
0,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Pase,NaN,00:01:33,00:01:33,0.0,NaN,21,11,5.0,NaN,11.0,largo,NaN,93.0
1,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Perdida,NaN,00:01:33,00:01:33,0.0,NaN,Volver,NaN,5.0,NaN,11.0,Atajada,NaN,93.0
2,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Arquero,NaN,00:01:49,00:01:49,0.0,Facil,Volver,NaN,1.0,NaN,16.0,Salvada/Atajada,NaN,109.0
3,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Pase,NaN,00:01:57,00:01:57,0.0,NaN,5,2,1.0,NaN,3.0,S arquero mano,NaN,117.0
4,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Pase,NaN,00:02:03,00:02:03,0.0,NaN,2,6,2.0,NaN,5.0,corto,NaN,123.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Perdida,NaN,01:52:24,01:52:24,0.0,NaN,Volver,NaN,15.0,NaN,23.0,Interceptado,NaN,6744.0
242,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Pase,NaN,01:53:35,01:53:35,0.0,NaN,24,23,15.0,NaN,18.0,corto,NaN,6815.0
243,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Remate pie,NaN,01:53:40,01:53:40,0.0,NaN,22,Rival,23.0,NaN,21.0,Corta distancia,NaN,6820.0
244,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,Perdida,NaN,01:53:41,01:53:41,0.0,NaN,Volver,NaN,23.0,NaN,21.0,Interceptado,NaN,6821.0
245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
#data['segundos'] = np.random.randint(1, 600, data.shape[0])
#data

In [88]:
'''CORREGIR MAYUSCULAS Y COSAS DE EVENTOS'''

data['Evento'] = data['Evento'].str.lower().str.strip()
data['Subevento'] = data['Subevento'].str.lower().str.strip()

# Estadisticas basicas

In [89]:
# data.Evento = data.Evento.str.replace('tag','pase')

In [90]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
arquero       rebote/despeje             2
              remate atajable            1
              salvada/atajada            6
falta         hecha                     16
              offside                    7
              recibida                  17
gol           directa                    1
pase          centro aereo               4
              corto                     89
              largo                      9
              medio                     15
              s arquero mano             2
              s arquero pie             17
perdida       atajada                    5
              balon afuera fondo         8
              interceptado              29
remate cabeza dificil                    1
              facil                      1
remate pie    corta distancia            8
tarjeta       amarilla                   2
              roja                       1

In [91]:
data.groupby(['Jugador 1','Evento','Subevento']).size().to_frame('cantidad')

                                      cantidad
Jugador 1 Evento     Subevento
1.0       arquero    rebote/despeje          2
                     remate atajable         1
                     salvada/atajada         6
          pase       corto                   7
                     largo                   3
...                                        ...
23.0      pase       centro aereo            1
                     corto                   4
          perdida    interceptado            1
          remate pie corta distancia         1
          tarjeta    amarilla                1

[91 rows x 1 columns]

# Filtros para la app

Disparos
---
- gol
- fuera
- al arco
- interceptado
- cabeza

Pase
---
- asistencia
- completado
- interceptado
- fuera
- inteligente

Centros
---
- asistencia
- completado
- interceptado
- bloqueado
- fuera

Duelos
---
- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

Faltas
---
- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

Recuperacion
---
- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

Pelota parada
---
- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

Perdida
---
- gambeta a favor
- robo
- intercepcion suelo
- intercepcion aereo
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

Arquero
---
- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


LO QUE HAY QUE HACER ES CREAR UNA COLUMNA POR CADA UNO DE ESOS FILTROS CON 0-1. QUEDAR CON UNA SOLA FILA POR ACCION.

In [92]:
data_eventos = data.copy()
data_eventos.shape

(246, 19)

# Disparos

- gol: siempre tiene que haber un disparo antes de un gol? Que pasa cuando es en contra, por ejemplo. Asegurarse que siempre antes de un gol poner disparo porque si no no lo toma aca
- fuera: asegurarse de poner que pasa siempre despues de los remates
- al arco: tiene que haber una perdida en evento y atajada en subevento, desupes de un remate
- interceptado
- cabeza

In [93]:
#gol
'''si data[i] es remate y data[i+1] es gol'''

data_eventos['remate-Gol'] = 0
for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') | (data_eventos.loc[i,'Evento']=='pelota parada'):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i+1,'Evento']=='gol'):
            data_eventos.loc[i,'remate-Gol'] = 1
            
data_eventos.loc[data_eventos['remate-Gol'] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Dificultad,coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol
129,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:04:49,01:04:49,0.0,NaN,22,Rival,9.0,NaN,22.0,corta distancia,NaN,3889.0,1

In [94]:
#fuera
'''si data[i] es remate y data[i+1] es perdida balon fuera'''
colname = 'remate-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'):
            if('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera
31,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate cabeza,NaN,00:07:47,00:07:47,0.0,...,22,Rival,3.0,NaN,22.0,dificil,NaN,467.0,0,1
139,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:13:42,01:13:42,0.0,...,22,Rival,9.0,NaN,21.0,corta distancia,NaN,4422.0,0,1
179,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:32:33,01:32:33,0.0,...,Volver,NaN,7.0,NaN,23.0,corta distancia,NaN,5553.0,0,1
188,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:33:57,01:33:57,0.0,...,22,Rival,3.0,NaN,21.0,corta distancia,NaN,5637.0,0,1
224,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:46:24,01:46:24,0.0,...,22,Rival,8.0,NaN,21.0,corta distancia,NaN,6384.0,0,1

In [95]:
#al arco
'''si data[i] es remate y data[i+1] es perdida atajada'''

colname = 'remate-Al-arco'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza'):
        if (data_eventos.loc[i+1,'Evento']=='perdida'): 
            if('atajada' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco
161,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:24:43,01:24:43,0.0,...,Rival,11.0,NaN,21.0,corta distancia,NaN,5083.0,0,0,1
175,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:30:27,01:30:27,0.0,...,Rival,10.0,NaN,17.0,corta distancia,NaN,5427.0,0,0,1

In [96]:
#bloqueado
'''si data[i] es remate y data[i] es remate bloqueado o data[i+1] es perdida error tecnico'''

colname = 'remate-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='remate pie') | (data_eventos.loc[i,'Evento']=='remate cabeza') :
        if (data_eventos.loc[i,'Subevento'] == 'remate bloqueado'): 
            data_eventos.loc[i,colname] = 1
        elif(data_eventos.loc[i+1,'Evento']=='perdida'):
            if('error tecnico' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado]
Index: []

[0 rows x 23 columns]

In [97]:
#cabeza
'''si data[i] es remate cabeza'''

colname = 'remate-Cabeza'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='remate cabeza'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
11,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate cabeza,NaN,00:02:28,00:02:28,0.0,...,NaN,21.0,facil,NaN,148.0,0,0,0,0,1
31,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate cabeza,NaN,00:07:47,00:07:47,0.0,...,NaN,22.0,dificil,NaN,467.0,0,1,0,0,1

# Pase

- asistencia
- completado
- interceptado
- fuera
- inteligente

In [98]:
data[data.Evento=='pase'].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                       cantidad
Evento Subevento
pase   centro aereo           4
       corto                 89
       largo                  9
       medio                 15
       s arquero mano         2
       s arquero pie         17

In [99]:
data[(data.Evento=='pase') ]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),Dificultad,coord final,Jugador 2,Jugador 1,Calificacion,coord inicial,Subevento,Optional Column,segundos
0,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:33,00:01:33,0.0,NaN,21,11,5.0,NaN,11.0,largo,NaN,93.0
3,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:57,00:01:57,0.0,NaN,5,2,1.0,NaN,3.0,s arquero mano,NaN,117.0
4,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:03,00:02:03,0.0,NaN,2,6,2.0,NaN,5.0,corto,NaN,123.0
5,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:07,00:02:07,0.0,NaN,4,1,6.0,NaN,2.0,corto,NaN,127.0
6,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:13,00:02:13,0.0,NaN,9,2,1.0,NaN,4.0,corto,NaN,133.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:51:10,01:51:10,0.0,NaN,4,1,18.0,NaN,11.0,medio,NaN,6670.0
236,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:51:13,01:51:13,0.0,NaN,6,6,1.0,NaN,5.0,corto,NaN,6673.0
237,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:51:18,01:51:18,0.0,NaN,15,23,6.0,NaN,6.0,medio,NaN,6678.0
240,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:52:22,01:52:22,0.0,NaN,22,4,15.0,NaN,23.0,corto,NaN,6742.0
242,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:53:35,01:53:35,0.0,NaN,24,23,15.0,NaN,18.0,corto,NaN,6815.0

In [100]:
data_eventos.head()

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Calificacion,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza
0,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:33,00:01:33,0.0,...,NaN,11.0,largo,NaN,93.0,0,0,0,0,0
1,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:01:33,00:01:33,0.0,...,NaN,11.0,atajada,NaN,93.0,0,0,0,0,0
2,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,00:01:49,00:01:49,0.0,...,NaN,16.0,salvada/atajada,NaN,109.0,0,0,0,0,0
3,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:57,00:01:57,0.0,...,NaN,3.0,s arquero mano,NaN,117.0,0,0,0,0,0
4,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:03,00:02:03,0.0,...,NaN,5.0,corto,NaN,123.0,0,0,0,0,0

In [101]:
#asistencia
'''si data[i] es pase, data[i+1] es remate y data[i+2] es gol'''
colname = 'pase-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pase'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,coord inicial,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia
128,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:04:47,01:04:47,0.0,...,22.0,corto,NaN,3887.0,0,0,0,0,0,1

In [102]:
##completado
'''si data[i] es pase no bloqueado y data[i+1] no es perdida interceptado o balon afuera'''

colname = 'pase-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') & (data_eventos.loc[i,'Jugador 2'] != 'Rival')):
        if ((data_eventos.loc[i+1,'Evento'] != 'perdida') ):
            data_eventos.loc[i,colname] = 1
        
        #elif ('intercep' not in data_eventos.loc[i+1,'Subevento']) & ('balon afuera' not in data_eventos.loc[i+1,'Subevento']) & ('encontrad' not in data_eventos.loc[i+1,'Subevento']):
        #    data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Subevento,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado
4,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:03,00:02:03,0.0,...,corto,NaN,123.0,0,0,0,0,0,0,1
5,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:07,00:02:07,0.0,...,corto,NaN,127.0,0,0,0,0,0,0,1
6,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:13,00:02:13,0.0,...,corto,NaN,133.0,0,0,0,0,0,0,1
9,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:26,00:02:26,0.0,...,corto,NaN,146.0,0,0,0,0,0,0,1
10,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:28,00:02:28,0.0,...,corto,NaN,148.0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:46:24,01:46:24,0.0,...,corto,NaN,6384.0,0,0,0,0,0,0,1
235,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:51:10,01:51:10,0.0,...,medio,NaN,6670.0,0,0,0,0,0,0,1
236,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:51:13,01:51:13,0.0,...,corto,NaN,6673.0,0,0,0,0,0,0,1
237,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:51:18,01:51:18,0.0,...,medio,NaN,6678.0,0,0,0,0,0,0,1
242,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:53:35,01:53:35,0.0,...,corto,NaN,6815.0,0,0,0,0,0,0,1

In [103]:
data_eventos.loc[data_eventos[colname] == 1].Subevento.value_counts()

corto           76
medio            7
largo            3
centro aereo     2
Name: Subevento, dtype: int64

In [104]:
#Incompleto
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'pase-Incompleto'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if ((data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='s arquero mano') & (data_eventos.loc[i,'Subevento']!='s arquero pie') ):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') ):
            #if ((data_eventos.loc[i,'pase-Completado'] != 1)):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,Optional Column,segundos,remate-Gol,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto
0,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:33,00:01:33,0.0,...,NaN,93.0,0,0,0,0,0,0,0,1
7,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:18,00:02:18,0.0,...,NaN,138.0,0,0,0,0,0,0,0,1
14,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:03:18,00:03:18,0.0,...,NaN,198.0,0,0,0,0,0,0,0,1
18,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:04:36,00:04:36,0.0,...,NaN,276.0,0,0,0,0,0,0,0,1
24,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:05:52,00:05:52,0.0,...,NaN,352.0,0,0,0,0,0,0,0,1
36,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:08:32,00:08:32,0.0,...,NaN,512.0,0,0,0,0,0,0,0,1
43,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:09:46,00:09:46,0.0,...,NaN,586.0,0,0,0,0,0,0,0,1
52,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:16:06,00:16:06,0.0,...,NaN,966.0,0,0,0,0,0,0,0,1
54,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:16:24,00:16:24,0.0,...,NaN,984.0,0,0,0,0,0,0,0,1
59,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:20:22,00:20:22,0.0,...,NaN,1222.0,0,0,0,0,0,0,0,1
67,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:23:50,00:23:50,0.0,...,NaN,1430.0,0,0,0,0,0,0,0,1
75,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:26:33,00:26:33,0.0,...,NaN,1593.0,0,0,0,0,0,0,0,1
84,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:28:16,00:28:16,0.0,...,NaN,1696.0,0,0,0,0,0,0,0,1
89,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:29:09,00:29:09,0.0,...,NaN,1749.0,0,0,0,0,0,0,0,1
97,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:32:21,00:32:21,0.0,...,NaN,1941.0,0,0,0,0,0,0,0,1
114,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:42:28,00:42:28,0.0,...,NaN,2548.0,0,0,0,0,0,0,0,1
117,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:43:35,00:43:35,0.0,...,NaN,2615.0,0,0,0,0,0,0,0,1
120,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:44:13,00:44:13,0.0,...,NaN,2653.0,0,0,0,0,0,0,0,1
124,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:46:30,00:46:30,0.0,...,NaN,2790.0,0,0,0,0,0,0,0,1
142,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:14:07,01:14:07,0.0,...,NaN,4447.0,0,0,0,0,0,0,0,1
148,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:17:31,01:17:31,0.0,...,NaN,4651.0,0,0,0,0,0,0,0,1
152,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:20:46,01:20:46,0.0,...,NaN,4846.0,0,0,0,0,0,0,0,1
154,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:21:12,01:21:12,0.0,...,NaN,4872.0,0,0,0,0,0,0,0,1
168,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:26:37,01:26:37,0.0,...,NaN,5197.0,0,0,0,0,0,0,0,1
184,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:33:11,01:33:11,0.0,...,NaN,5591.0,0,0,0,0,0,0,0,1
195,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:36:18,01:36:18,0.0,...,NaN,5778.0,0,0,0,0,0,0,0,1
200,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:36:37,01:36:37,0.0,...,NaN,5797.0,0,0,0,0,0,0,0,1
206,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:38:15,01:38:15,0.0,...,NaN,5895.0,0,0,0,0,0,0,0,1
240,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:52:22,01:52:22,0.0,...,NaN,6742.0,0,0,0,0,0,0,0,1

In [105]:
# #fuera
# '''si data[i] es pase no bloqueado y data[i+1] es perdida fuera'''

# colname = 'pase-Fuera'
# data_eventos[colname] = 0
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']!='pase bloqueado') & (data_eventos.loc[i,'Subevento']!='centro aereo'):
#         if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
#             if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
#                 data_eventos.loc[i,colname] = 1
            
# data_eventos.loc[data_eventos[colname] == 1]

In [106]:
#inteligente

colname = 'pase-Inteligente'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Subevento']=='inteligente'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente]
Index: []

[0 rows x 28 columns]

# Centros

- asistencia
- completado
- interceptado
- bloqueado
- fuera

In [107]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
arquero       rebote/despeje             2
              remate atajable            1
              salvada/atajada            6
falta         hecha                     16
              offside                    7
              recibida                  17
gol           directa                    1
pase          centro aereo               4
              corto                     89
              largo                      9
              medio                     15
              s arquero mano             2
              s arquero pie             17
perdida       atajada                    5
              balon afuera fondo         8
              interceptado              29
remate cabeza dificil                    1
              facil                      1
remate pie    corta distancia            8
tarjeta       amarilla                   2
              roja                       1

In [108]:
#asistencia

colname = 'centro-Asistencia'
data_eventos[colname] = 0
for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if ('remate' in data_eventos.loc[i+1,'Evento']):
            if (data_eventos.loc[i+2,'Evento']=='gol'):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia]
Index: []

[0 rows x 29 columns]

In [109]:
#completado

colname = 'centro-Completado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] != 'perdida')| (data_eventos.loc[i,'Jugador 1'] != data_eventos.loc[i+1,'Jugador 1']) :
            data_eventos.loc[i,colname] = 1

            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Fuera,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado
30,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:07:45,00:07:45,0.0,...,0,0,0,0,0,1,0,0,0,1
216,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:39:48,01:39:48,0.0,...,0,0,0,0,0,1,0,0,0,1

In [110]:
#interceptado
'''si data[i] es pase no bloqueado y data[i+1] es perdida interceptado'''

colname = 'centro-Interceptado'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,remate-Al-arco,remate-Interceptado,remate-Cabeza,pase-Asistencia,pase-Completado,pase-Incompleto,pase-Inteligente,centro-Asistencia,centro-Completado,centro-Interceptado
18,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:04:36,00:04:36,0.0,...,0,0,0,0,0,1,0,0,0,1

In [111]:
#bloqueado

colname = 'centro-Bloqueado'
data_eventos[colname] = 0
# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Subevento']=='centro bloqueado'):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado]
Index: []

[0 rows x 32 columns]

In [112]:
#fuera

colname = 'centro-Fuera'
data_eventos[colname] = 0
for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Subevento']=='centro aereo'):
        if (data_eventos.loc[i+1,'Evento'] == 'perdida'):
            if ('balon afuera' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera]
Index: []

[0 rows x 33 columns]

# Duelos

- ganado
- perdido
- duelo aereo
- disputa suelo
- gambeta en contra
- gambeta a favor
- pivote

In [113]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
arquero       rebote/despeje             2
              remate atajable            1
              salvada/atajada            6
falta         hecha                     16
              offside                    7
              recibida                  17
gol           directa                    1
pase          centro aereo               4
              corto                     89
              largo                      9
              medio                     15
              s arquero mano             2
              s arquero pie             17
perdida       atajada                    5
              balon afuera fondo         8
              interceptado              29
remate cabeza dificil                    1
              facil                      1
remate pie    corta distancia            8
tarjeta       amarilla                   2
              roja                       1

In [114]:
# dejar_index= []
# for i in range(len(data_eventos)-1):
#     if (data_eventos.loc[i,'Evento']=='duelo'):
#         dejar_index.append(i-1)
#         dejar_index.append(i)
#         dejar_index.append(i+1)
# data_eventos.loc[dejar_index].head(10)

In [115]:
#duelo aereo

colname1 = 'duelo-Aereo-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Aereo-Ganado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='aereo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1


data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado]
Index: []

[0 rows x 35 columns]

In [116]:
data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado]
Index: []

[0 rows x 35 columns]

In [117]:
#disputa suelo

colname1 = 'duelo-Disputa-suelo-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Disputa-suelo-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada]
Index: []

[0 rows x 37 columns]

In [118]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada]
Index: []

[0 rows x 37 columns]

In [119]:
#gambeta en contra

colname1 = 'duelo-Gambeta-contra-Ganada'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-contra-Perdida'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta en contra'):
        if ((data_eventos.loc[i+1,'Evento'] == 'recuperacion') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') )): 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 39 columns]

In [120]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida]
Index: []

[0 rows x 39 columns]

In [121]:
#gambeta a favor

colname1 = 'duelo-Gambeta-favor-Perdida'
data_eventos[colname1] = 0
colname2 = 'duelo-Gambeta-favor-Ganada'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='gambeta a favor'):
        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & ((data_eventos.loc[i+1,'Subevento'] == 'duelo') | ('balon afuera' in data_eventos.loc[i+1,'Subevento']))) : 
            data_eventos.loc[i,colname1] = 1
        else:
            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada]
Index: []

[0 rows x 41 columns]

In [122]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada]
Index: []

[0 rows x 41 columns]

In [123]:
#pivote

colname1 = 'duelo-Pivote-Perdido'
data_eventos[colname1] = 0
colname2 = 'duelo-Pivote-Ganado'
data_eventos[colname2] = 0

#for i in range(len(data_eventos)):
#    if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='pivote'):
#        if ((data_eventos.loc[i+1,'Evento'] == 'perdida') & (data_eventos.loc[i+1,'Subevento'] == 'duelo')) : 
#            data_eventos.loc[i,colname1] = 1
#        else:
#            data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado]
Index: []

[0 rows x 43 columns]

# Faltas

- falta cometida
- falta recibida
- penal
- tarjeta amarilla
- tarjeta roja
- off-side

In [124]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
arquero       rebote/despeje             2
              remate atajable            1
              salvada/atajada            6
falta         hecha                     16
              offside                    7
              recibida                  17
gol           directa                    1
pase          centro aereo               4
              corto                     89
              largo                      9
              medio                     15
              s arquero mano             2
              s arquero pie             17
perdida       atajada                    5
              balon afuera fondo         8
              interceptado              29
remate cabeza dificil                    1
              facil                      1
remate pie    corta distancia            8
tarjeta       amarilla                   2
              roja                       1

In [125]:
#falta cometida

colname = 'falta-Cometida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Aereo-Ganado,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida
45,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:10:11,00:10:11,0.0,...,0,0,0,0,0,0,0,0,0,1
61,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:22:06,00:22:06,0.0,...,0,0,0,0,0,0,0,0,0,1
86,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:28:21,00:28:21,0.0,...,0,0,0,0,0,0,0,0,0,1
93,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:30:03,00:30:03,0.0,...,0,0,0,0,0,0,0,0,0,1
103,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:33:46,00:33:46,0.0,...,0,0,0,0,0,0,0,0,0,1
104,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:34:49,00:34:49,0.0,...,0,0,0,0,0,0,0,0,0,1
131,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:06:28,01:06:28,0.0,...,0,0,0,0,0,0,0,0,0,1
132,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:07:07,01:07:07,0.0,...,0,0,0,0,0,0,0,0,0,1
134,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:08:23,01:08:23,0.0,...,0,0,0,0,0,0,0,0,0,1
163,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:24:53,01:24:53,0.0,...,0,0,0,0,0,0,0,0,0,1
166,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:26:02,01:26:02,0.0,...,0,0,0,0,0,0,0,0,0,1
191,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:34:57,01:34:57,0.0,...,0,0,0,0,0,0,0,0,0,1
192,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:35:14,01:35:14,0.0,...,0,0,0,0,0,0,0,0,0,1
202,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:36:43,01:36:43,0.0,...,0,0,0,0,0,0,0,0,0,1
219,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:43:42,01:43:42,0.0,...,0,0,0,0,0,0,0,0,0,1
227,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:47:36,01:47:36,0.0,...,0,0,0,0,0,0,0,0,0,1

In [126]:
#falta recibida

colname = 'falta-Recibida'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='recibida'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Disputa-suelo-Perdida,duelo-Disputa-suelo-Ganada,duelo-Gambeta-contra-Ganada,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida
20,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:05:23,00:05:23,0.0,...,0,0,0,0,0,0,0,0,0,1
29,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:06:50,00:06:50,0.0,...,0,0,0,0,0,0,0,0,0,1
46,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:12:17,00:12:17,0.0,...,0,0,0,0,0,0,0,0,0,1
56,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:18:01,00:18:01,0.0,...,0,0,0,0,0,0,0,0,0,1
57,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:18:21,00:18:21,0.0,...,0,0,0,0,0,0,0,0,0,1
70,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:23:55,00:23:55,0.0,...,0,0,0,0,0,0,0,0,0,1
80,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:27:00,00:27:00,0.0,...,0,0,0,0,0,0,0,0,0,1
99,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:32:58,00:32:58,0.0,...,0,0,0,0,0,0,0,0,0,1
106,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:36:22,00:36:22,0.0,...,0,0,0,0,0,0,0,0,0,1
110,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:41:39,00:41:39,0.0,...,0,0,0,0,0,0,0,0,0,1
122,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:45:20,00:45:20,0.0,...,0,0,0,0,0,0,0,0,0,1
127,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:04:11,01:04:11,0.0,...,0,0,0,0,0,0,0,0,0,1
138,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:13:03,01:13:03,0.0,...,0,0,0,0,0,0,0,0,0,1
145,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:14:23,01:14:23,0.0,...,0,0,0,0,0,0,0,0,0,1
156,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:21:49,01:21:49,0.0,...,0,0,0,0,0,0,0,0,0,1
172,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:28:47,01:28:47,0.0,...,0,0,0,0,0,0,0,0,0,1
239,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:52:09,01:52:09,0.0,...,0,0,0,0,0,0,0,0,0,1

In [127]:
#penal cometido

colname = 'falta-Penal-cometido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal cometido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido]
Index: []

[0 rows x 46 columns]

In [128]:
#penal_recibido

colname = 'falta-Penal-recibido'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='penal recibido'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido]
Index: []

[0 rows x 47 columns]

In [129]:
#offside

colname = 'falta-Offside'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='offside'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-contra-Perdida,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside
28,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:06:06,00:06:06,0.0,...,0,0,0,0,0,0,0,0,0,1
50,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:13:40,00:13:40,0.0,...,0,0,0,0,0,0,0,0,0,1
105,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,00:35:39,00:35:39,0.0,...,0,0,0,0,0,0,0,0,0,1
146,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:16:22,01:16:22,0.0,...,0,0,0,0,0,0,0,0,0,1
171,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:27:58,01:27:58,0.0,...,0,0,0,0,0,0,0,0,0,1
212,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:38:36,01:38:36,0.0,...,0,0,0,0,0,0,0,0,0,1
238,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,falta,NaN,01:51:18,01:51:18,0.0,...,0,0,0,0,0,0,0,0,0,1

In [130]:
#tarjeta amarilla

colname = 'falta-Tarjeta-amarilla'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    # if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i,'Evento']=='tarjeta') & (data_eventos.loc[i,'Subevento']=='amarilla'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-favor-Perdida,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla
126,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,tarjeta,NaN,00:48:18,00:48:18,0.0,...,0,0,0,0,0,0,0,0,0,1
228,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,tarjeta,NaN,01:47:36,01:47:36,0.0,...,0,0,0,0,0,0,0,0,0,1

In [131]:
#tarjeta roja

colname = 'falta-Tarjeta-roja'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    # if (data_eventos.loc[i,'Evento']=='falta') & (data_eventos.loc[i,'Subevento']=='hecha'):
        if (data_eventos.loc[i,'Evento']=='tarjeta') & (data_eventos.loc[i,'Subevento']=='roja'):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,duelo-Gambeta-favor-Ganada,duelo-Pivote-Perdido,duelo-Pivote-Ganado,falta-Cometida,falta-Recibida,falta-Penal-cometido,falta-Penal-recibido,falta-Offside,falta-Tarjeta-amarilla,falta-Tarjeta-roja
220,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,tarjeta,NaN,01:43:42,01:43:42,0.0,...,0,0,0,0,0,0,0,0,0,1

# Recuperacion

- robo
- encontradas
- intercepcion suelo
- intercepcion aereo
- intercepcion anticipo
- disputa suelo

In [132]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
arquero       rebote/despeje             2
              remate atajable            1
              salvada/atajada            6
falta         hecha                     16
              offside                    7
              recibida                  17
gol           directa                    1
pase          centro aereo               4
              corto                     89
              largo                      9
              medio                     15
              s arquero mano             2
              s arquero pie             17
perdida       atajada                    5
              balon afuera fondo         8
              interceptado              29
remate cabeza dificil                    1
              facil                      1
remate pie    corta distancia            8
tarjeta       amarilla                   2
              roja                       1

In [133]:
colname = 'recuperacion-Robo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if ((data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='robo')):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo]
Index: []

[0 rows x 51 columns]

In [134]:
#encontrada

colname = 'recuperacion-Encontrada'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='encontrada'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada]
Index: []

[0 rows x 52 columns]

In [135]:
#intercepcion suelo

colname = 'recuperacion-Intercepcion-suelo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo]
Index: []

[0 rows x 53 columns]

In [136]:
#intercepcion aereo

colname = 'recuperacion-Intercepcion-aereo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Subevento']=='intercepcion aereo'):
        data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo]
Index: []

[0 rows x 54 columns]

In [137]:
#intercepcion anticipo

colname = 'recuperacion-Intercepcion-anticipo'
data_eventos[colname] = 0
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion'):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1
            
data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo]
Index: []

[0 rows x 55 columns]

In [138]:
#disputa suelo

colname = 'recuperacion-Disputa-suelo'
data_eventos[colname] = 0

for i in range(len(data_eventos)-1):
    #if (data_eventos.loc[i,'Evento']=='duelo') & (data_eventos.loc[i,'Subevento']=='disputa suelo'):
    if (data_eventos.loc[i,'Evento'] == 'recuperacion') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo]
Index: []

[0 rows x 56 columns]

# Pelota parada

- lateral completado
- lateral interceptado
- corner completado
- corner interceptado
- tiro libre

In [139]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
arquero       rebote/despeje             2
              remate atajable            1
              salvada/atajada            6
falta         hecha                     16
              offside                    7
              recibida                  17
gol           directa                    1
pase          centro aereo               4
              corto                     89
              largo                      9
              medio                     15
              s arquero mano             2
              s arquero pie             17
perdida       atajada                    5
              balon afuera fondo         8
              interceptado              29
remate cabeza dificil                    1
              facil                      1
remate pie    corta distancia            8
tarjeta       amarilla                   2
              roja                       1

In [140]:
#lateral

colname1 = 'parado-Lateral-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Lateral-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):

            if ((data_eventos.loc[i+1,'Evento']=='perdida') & (data_eventos.loc[i+1,'Subevento']=='intercepcion')):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if ('lateral' in data_eventos.loc[i,'Subevento']):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado]
Index: []

[0 rows x 58 columns]

In [141]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado]
Index: []

[0 rows x 58 columns]

In [142]:
#corner

colname1 = 'parado-Corner-interceptado'
data_eventos[colname1] = 0
colname2 = 'parado-Corner-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-2):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):

            if ('intercep' in data_eventos.loc[i+1,'Subevento']):
                data_eventos.loc[i,colname1] = 1
            if (data_eventos.loc[i+1,'Evento']=='duelo') & ((data_eventos.loc[i+1,'Subevento']=='aereo') | (data_eventos.loc[i+1,'Subevento']=='disputa suelo')):
                if (data_eventos.loc[i+2,'Evento']=='perdida') & (data_eventos.loc[i+2,'Subevento']=='duelo'):
                    data_eventos.loc[i,colname1] = 1
                
for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro de esquina'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 60 columns]

In [143]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado]
Index: []

[0 rows x 60 columns]

In [144]:
#tiro libre
colname1 = 'parado-Tiro-libre-incompleto'
data_eventos[colname1] = 0
colname2 = 'parado-Tiro-libre-completado'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Subevento']=='tiro libre') :
        if(data_eventos.loc[i+1,'Evento'] == 'perdida'):
            data_eventos.loc[i,colname1] = 1

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada'):
        if (data_eventos.loc[i,'Subevento']=='tiro libre'):
            if (data_eventos.loc[i,colname1]!= 1):
                data_eventos.loc[i,colname2] = 1

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado]
Index: []

[0 rows x 62 columns]

In [145]:
data_eventos.loc[data_eventos[colname2] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado]
Index: []

[0 rows x 62 columns]

# Perdida

- gambeta a favor
- robo
- intercepcion
- error tecnico
- balon afuera
- genero situacion rival
- genero gol rival
- atajada rival

In [146]:
data.groupby(['Evento','Subevento']).size().to_frame('cantidad')

                                  cantidad
Evento        Subevento
arquero       rebote/despeje             2
              remate atajable            1
              salvada/atajada            6
falta         hecha                     16
              offside                    7
              recibida                  17
gol           directa                    1
pase          centro aereo               4
              corto                     89
              largo                      9
              medio                     15
              s arquero mano             2
              s arquero pie             17
perdida       atajada                    5
              balon afuera fondo         8
              interceptado              29
remate cabeza dificil                    1
              facil                      1
remate pie    corta distancia            8
tarjeta       amarilla                   2
              roja                       1

In [ ]:
# data_eventos = data_eventos[~data_eventos.Subevento.isna()].reset_index(drop=True)

In [64]:
data_eventos[data_eventos.Evento == 'perdida']

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,recuperacion-Intercepcion-suelo,recuperacion-Intercepcion-aereo,recuperacion-Intercepcion-anticipo,recuperacion-Disputa-suelo,parado-Lateral-interceptado,parado-Lateral-completado,parado-Corner-interceptado,parado-Corner-completado,parado-Tiro-libre-incompleto,parado-Tiro-libre-completado
1,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:01:33,00:01:33,0.0,...,0,0,0,0,0,0,0,0,0,0
8,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:02:19,00:02:19,0.0,...,0,0,0,0,0,0,0,0,0,0
12,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:02:29,00:02:29,0.0,...,0,0,0,0,0,0,0,0,0,0
15,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:03:19,00:03:19,0.0,...,0,0,0,0,0,0,0,0,0,0
19,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:04:36,00:04:36,0.0,...,0,0,0,0,0,0,0,0,0,0
25,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:05:52,00:05:52,0.0,...,0,0,0,0,0,0,0,0,0,0
32,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:07:47,00:07:47,0.0,...,0,0,0,0,0,0,0,0,0,0
37,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:08:32,00:08:32,0.0,...,0,0,0,0,0,0,0,0,0,0
44,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:09:46,00:09:46,0.0,...,0,0,0,0,0,0,0,0,0,0
53,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:16:06,00:16:06,0.0,...,0,0,0,0,0,0,0,0,0,0
55,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:16:27,00:16:27,0.0,...,0,0,0,0,0,0,0,0,0,0
60,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:20:22,00:20:22,0.0,...,0,0,0,0,0,0,0,0,0,0
68,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:23:51,00:23:51,0.0,...,0,0,0,0,0,0,0,0,0,0
76,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:26:33,00:26:33,0.0,...,0,0,0,0,0,0,0,0,0,0
85,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:28:16,00:28:16,0.0,...,0,0,0,0,0,0,0,0,0,0
90,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:29:09,00:29:09,0.0,...,0,0,0,0,0,0,0,0,0,0
92,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:29:50,00:29:50,0.0,...,0,0,0,0,0,0,0,0,0,0
98,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:32:22,00:32:22,0.0,...,0,0,0,0,0,0,0,0,0,0
115,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:42:28,00:42:28,0.0,...,0,0,0,0,0,0,0,0,0,0
118,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:43:38,00:43:38,0.0,...,0,0,0,0,0,0,0,0,0,0
121,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:44:16,00:44:16,0.0,...,0,0,0,0,0,0,0,0,0,0
125,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:46:30,00:46:30,0.0,...,0,0,0,0,0,0,0,0,0,0
137,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:10:49,01:10:49,0.0,...,0,0,0,0,0,0,0,0,0,0
140,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:13:42,01:13:42,0.0,...,0,0,0,0,0,0,0,0,0,0
143,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:14:07,01:14:07,0.0,...,0,0,0,0,0,0,0,0,0,0
149,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:17:30,01:17:30,0.0,...,0,0,0,0,0,0,0,0,0,0
153,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:20:48,01:20:48,0.0,...,0,0,0,0,0,0,0,0,0,0
155,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:21:15,01:21:15,0.0,...,0,0,0,0,0,0,0,0,0,0
162,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:24:43,01:24:43,0.0,...,0,0,0,0,0,0,0,0,0,0
169,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:26:37,01:26:37,0.0,...,0,0,0,0,0,0,0,0,0,0
176,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:30:27,01:30:27,0.0,...,0,0,0,0,0,0,0,0,0,0
180,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:32:34,01:32:34,0.0,...,0,0,0,0,0,0,0,0,0,0
185,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:33:13,01:33:13,0.0,...,0,0,0,0,0,0,0,0,0,0
189,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:33:57,01:33:57,0.0,...,0,0,0,0,0,0,0,0,0,0
196,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:36:18,01:36:18,0.0,...,0,0,0,0,0,0,0,0,0,0
201,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:36:37,01:36:37,0.0,...,0,0,0,0,0,0,0,0,0,0
207,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:38:16,01:38:16,0.0,...,0,0,0,0,0,0,0,0,0,0
225,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:46:24,01:46:24,0.0,...,0,0,0,0,0,0,0,0,0,0
231,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:49:18,01:49:18,0.0,...,0,0,0,0,0,0,0,0,0,0
234,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:50:34,01:50:34,0.0,...,0,0,0,0,0,0,0,0,0,0
241,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:52:24,01:52:24,0.0,...,0,0,0,0,0,0,0,0,0,0
244,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:53:41,01:53:41,0.0,...,0,0,0,0,0,0,0,0,0,0

In [65]:
# data_eventos = data_eventos[data_eventos.Evento != 'perdida'].reset_index(drop=True)

In [147]:
#gambeta a favor

colname = 'perdida-Gambeta'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     #if (data_eventos.loc[i-1,'Evento']=='duelo') & (data_eventos.loc[i-1,'Subevento']=='gambeta a favor'):
#         if (data_eventos.loc[i,'Evento'] == 'perdida') & (data_eventos.loc[i,'Subevento'] == 'duelo'): 
#             data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta]
Index: []

[0 rows x 63 columns]

In [148]:
#robo

colname = 'perdida-Robo'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida') & ((data_eventos.loc[i,'Subevento']=='robo')):
#             data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo]
Index: []

[0 rows x 64 columns]

In [149]:
#intercepcion

colname = 'perdida-Intercepcion'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida') & ('intercep' in str(data_eventos.loc[i,'Subevento'])):
#         data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion]
Index: []

[0 rows x 65 columns]

In [150]:
#error tecnico

colname = 'perdida-Error-tecnico'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida') & (data_eventos.loc[i,'Subevento']=='error tecnico'):
#             data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico]
Index: []

[0 rows x 66 columns]

In [151]:
#balon afuera

colname = 'perdida-Balon-fuera'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida'):
#         if ('balon afuera' in str(data_eventos.loc[i,'Subevento'])):
#             data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera]
Index: []

[0 rows x 67 columns]

In [152]:
#situacion rival

colname = 'perdida-Error-tactico'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida'):
#         if (data_eventos.loc[i,'Subevento']=='error tactico'):
#             data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico]
Index: []

[0 rows x 68 columns]

In [153]:
#atajada

colname = 'perdida-Atajada'
data_eventos[colname] = 0

# for i in range(len(data_eventos)):
#     if (data_eventos.loc[i,'Evento']=='perdida'):
#         if (data_eventos.loc[i,'Subevento']=='atajada'):
#             data_eventos.loc[i,colname] = 1
            

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada]
Index: []

[0 rows x 69 columns]

# Arquero

- gol en contra
- atajada facil
- atajada dificil
- mano a mano
- rebote
- intercepcion aereo
- intercepcion aereo anticipo
- completado
- interceptado
- saque arquero pie
- saque arquero mano
- saque meta
- pase


Cuando pongo el gol rival, atajadas y rebotes, tengo q poner q todas las cosas se marquen como arquero-x:
- el remate rival (coordenadas inicial y final)
- la atajada (coordenada inicial)
- rebote (coordenada incial y final)
- el centro (si hay intercepcion aereo) , etc

In [154]:
data[data['Jugador 1'] == 1].groupby(['Evento','Subevento']).size().to_frame('cantidad')

                            cantidad
Evento  Subevento
arquero rebote/despeje             2
        remate atajable            1
        salvada/atajada            6
pase    corto                      7
        largo                      3
        medio                      5
        s arquero mano             2
        s arquero pie             17
perdida atajada                    1
        balon afuera fondo         1
        interceptado               7

In [155]:
#gol rival

colname1 = 'arquero-Gol-rival'
data_eventos[colname1] = 0
colname2 = 'arquero-Gol-rival-atajable'
data_eventos[colname2] = 0

for i in range(len(data_eventos)-1):
    if (data_eventos.loc[i,'Evento']=='gol rival'):
        data_eventos.loc[i,colname1] = 1
        if ('remate atajable' in data_eventos.loc[i+1,'Subevento']):
            data_eventos.loc[i,colname2] = 1
        

data_eventos.loc[data_eventos[colname1] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable]
Index: []

[0 rows x 71 columns]

In [156]:
#atajada

colname = 'arquero-Atajada'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='arquero'):
        if ('atajada' in data_eventos.loc[i,'Subevento']) | (data_eventos.loc[i,'Subevento']=='mano a mano'):
            data_eventos.loc[i,colname] = 1
            if ('remate' in data_eventos.loc[i-1,'Evento']):
                data_eventos.loc[i-1,colname] = 1
            elif ('remate' in data_eventos.loc[i-2,'Evento']):
                data_eventos.loc[i-2,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Gambeta,perdida-Robo,perdida-Intercepcion,perdida-Error-tecnico,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada
2,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,00:01:49,00:01:49,0.0,...,0,0,0,0,0,0,0,0,0,1
94,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,00:31:53,00:31:53,0.0,...,0,0,0,0,0,0,0,0,0,1
135,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,01:10:39,01:10:39,0.0,...,0,0,0,0,0,0,0,0,0,1
164,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,01:25:49,01:25:49,0.0,...,0,0,0,0,0,0,0,0,0,1
229,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,01:48:29,01:48:29,0.0,...,0,0,0,0,0,0,0,0,0,1
232,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,01:50:08,01:50:08,0.0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# #mano a mano
# data_eventos_con_rival = data.copy().reset_index(drop=True)

# colname = 'arquero-mano_a_mano'
# data_eventos_con_rival[colname] = 0

# for i in range(len(data_eventos_con_rival)):
#     if (data_eventos_con_rival.loc[i,'Evento']=='arquero'):
#         if ('mano a mano' in data_eventos_con_rival.loc[i,'Subevento']):
#             data_eventos_con_rival.loc[i,colname] = 1
#             if ('remate' in data_eventos_con_rival.loc[i-1,'Evento']):
#                 data_eventos_con_rival.loc[i,'Posicion incial'] = data_eventos_con_rival.loc[i-1,'Posicion incial']
#                 data_eventos_con_rival.loc[i,'Posicion final'] = data_eventos_con_rival.loc[i-1,'Posicion final']
#                 data_eventos_con_rival.loc[i,'coord inicial'] = data_eventos_con_rival.loc[i-1,'coord inicial']
#                 data_eventos_con_rival.loc[i,'coord final'] = data_eventos_con_rival.loc[i-1,'coord final']


# data_eventos_con_rival.loc[data_eventos_con_rival[colname] == 1]

In [157]:
#intercepcion aereo

colname = 'arquero-Intercepcion-aerea'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('intercepcion aereo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea]
Index: []

[0 rows x 73 columns]

In [158]:
#intercepcion

colname = 'arquero-Intercepcion'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if (data_eventos.loc[i,'Subevento']=='intercepcion'):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion]
Index: []

[0 rows x 74 columns]

In [159]:
#anticipo

colname = 'arquero-Anticipo'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='recuperacion') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('anticipo' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo]
Index: []

[0 rows x 75 columns]

In [160]:
#saque arquero mano

colname = 'arquero-Saque-mano'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero mano' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Balon-fuera,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano
3,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:57,00:01:57,0.0,...,0,0,0,0,0,0,0,0,0,1
95,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:32:02,00:32:02,0.0,...,0,0,0,0,0,0,0,0,0,1

In [161]:
#saque arquero pie

colname = 'arquero-Saque-pie'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pase') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('s arquero pie' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

,Session Start Date,tiempo,partido,Session Start,Session End,Evento,Tag Notes,Tag Start,Tag End,Tag Duration (secs),...,perdida-Error-tactico,perdida-Atajada,arquero-Gol-rival,arquero-Gol-rival-atajable,arquero-Atajada,arquero-Intercepcion-aerea,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie
13,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:03:07,00:03:07,0.0,...,0,0,0,0,0,0,0,0,0,1
38,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:09:28,00:09:28,0.0,...,0,0,0,0,0,0,0,0,0,1
51,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:15:59,00:15:59,0.0,...,0,0,0,0,0,0,0,0,0,1
62,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:23:37,00:23:37,0.0,...,0,0,0,0,0,0,0,0,0,1
72,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:26:25,00:26:25,0.0,...,0,0,0,0,0,0,0,0,0,1
78,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:26:55,00:26:55,0.0,...,0,0,0,0,0,0,0,0,0,1
91,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:29:50,00:29:50,0.0,...,0,0,0,0,0,0,0,0,0,1
116,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:43:31,00:43:31,0.0,...,0,0,0,0,0,0,0,0,0,1
133,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:08:17,01:08:17,0.0,...,0,0,0,0,0,0,0,0,0,1
136,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:10:47,01:10:47,0.0,...,0,0,0,0,0,0,0,0,0,1
147,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:17:24,01:17:24,0.0,...,0,0,0,0,0,0,0,0,0,1
157,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:23:39,01:23:39,0.0,...,0,0,0,0,0,0,0,0,0,1
165,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:26:00,01:26:00,0.0,...,0,0,0,0,0,0,0,0,0,1
167,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:26:30,01:26:30,0.0,...,0,0,0,0,0,0,0,0,0,1
170,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:27:56,01:27:56,0.0,...,0,0,0,0,0,0,0,0,0,1
230,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:49:18,01:49:18,0.0,...,0,0,0,0,0,0,0,0,0,1
233,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:50:31,01:50:31,0.0,...,0,0,0,0,0,0,0,0,0,1

In [162]:
#saque de meta

colname = 'arquero-Saque-meta'
data_eventos[colname] = 0

for i in range(len(data_eventos)):
    if (data_eventos.loc[i,'Evento']=='pelota parada') & (data_eventos.loc[i,'Jugador 1']==1):
        if ('saque de meta' in data_eventos.loc[i,'Subevento']):
            data_eventos.loc[i,colname] = 1

data_eventos.loc[data_eventos[colname] == 1]

Empty DataFrame
Columns: [Session Start Date, tiempo, partido, Session Start, Session End, Evento, Tag Notes, Tag Start, Tag End, Tag Duration (secs), Dificultad, coord final, Jugador 2, Jugador 1, Calificacion, coord inicial, Subevento, Optional Column, segundos, remate-Gol, remate-Fuera, remate-Al-arco, remate-Interceptado, remate-Cabeza, pase-Asistencia, pase-Completado, pase-Incompleto, pase-Inteligente, centro-Asistencia, centro-Completado, centro-Interceptado, centro-Bloqueado, centro-Fuera, duelo-Aereo-Perdido, duelo-Aereo-Ganado, duelo-Disputa-suelo-Perdida, duelo-Disputa-suelo-Ganada, duelo-Gambeta-contra-Ganada, duelo-Gambeta-contra-Perdida, duelo-Gambeta-favor-Perdida, duelo-Gambeta-favor-Ganada, duelo-Pivote-Perdido, duelo-Pivote-Ganado, falta-Cometida, falta-Recibida, falta-Penal-cometido, falta-Penal-recibido, falta-Offside, falta-Tarjeta-amarilla, falta-Tarjeta-roja, recuperacion-Robo, recuperacion-Encontrada, recuperacion-Intercepcion-suelo, recuperacion-Intercepcion-aereo, recuperacion-Intercepcion-anticipo, recuperacion-Disputa-suelo, parado-Lateral-interceptado, parado-Lateral-completado, parado-Corner-interceptado, parado-Corner-completado, parado-Tiro-libre-incompleto, parado-Tiro-libre-completado, perdida-Gambeta, perdida-Robo, perdida-Intercepcion, perdida-Error-tecnico, perdida-Balon-fuera, perdida-Error-tactico, perdida-Atajada, arquero-Gol-rival, arquero-Gol-rival-atajable, arquero-Atajada, arquero-Intercepcion-aerea, arquero-Intercepcion, arquero-Anticipo, arquero-Saque-mano, arquero-Saque-pie, arquero-Saque-meta]
Index: []

[0 rows x 78 columns]

In [163]:
data_eventos.columns = [col.replace(' ','.') for col in data_eventos.columns]

In [164]:
data_eventos.iloc[:,:20]

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),Dificultad,coord.final,Jugador.2,Jugador.1,Calificacion,coord.inicial,Subevento,Optional.Column,segundos,remate-Gol
0,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:33,00:01:33,0.0,NaN,21,11,5.0,NaN,11.0,largo,NaN,93.0,0
1,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,00:01:33,00:01:33,0.0,NaN,Volver,NaN,5.0,NaN,11.0,atajada,NaN,93.0,0
2,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,arquero,NaN,00:01:49,00:01:49,0.0,Facil,Volver,NaN,1.0,NaN,16.0,salvada/atajada,NaN,109.0,0
3,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:01:57,00:01:57,0.0,NaN,5,2,1.0,NaN,3.0,s arquero mano,NaN,117.0,0
4,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,00:02:03,00:02:03,0.0,NaN,2,6,2.0,NaN,5.0,corto,NaN,123.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:52:24,01:52:24,0.0,NaN,Volver,NaN,15.0,NaN,23.0,interceptado,NaN,6744.0,0
242,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,pase,NaN,01:53:35,01:53:35,0.0,NaN,24,23,15.0,NaN,18.0,corto,NaN,6815.0,0
243,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,remate pie,NaN,01:53:40,01:53:40,0.0,NaN,22,Rival,23.0,NaN,21.0,corta distancia,NaN,6820.0,0
244,2022/07/24,pases barracas central,pases barracas central,13:43:45,15:43:30,perdida,NaN,01:53:41,01:53:41,0.0,NaN,Volver,NaN,23.0,NaN,21.0,interceptado,NaN,6821.0,0
245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

# Crear coordenadas

- Primero mapear la media de coordenadas para cada sector
- Segundo agregar aleatoriedad

In [165]:
data_eventos['coord.inicial'].value_counts()

3.0     27
9.0     17
8.0     15
7.0     14
17.0    14
18.0    13
11.0    12
21.0    12
4.0     10
13.0    10
24.0    10
16.0    10
15.0     9
10.0     9
14.0     9
12.0     9
2.0      7
23.0     7
5.0      6
1.0      6
20.0     5
22.0     5
6.0      3
19.0     2
Name: coord.inicial, dtype: int64

In [166]:
data_eventos['coord.final'].value_counts()

Volver    101
17         16
22         15
16         11
18         11
15         10
21          9
8           7
5           7
14          6
4           6
2           6
13          6
24          5
12          5
7           5
9           5
3           4
23          3
1           2
10          2
20          1
11          1
6           1
Name: coord.final, dtype: int64

In [167]:
map_zona_coord_x = {  
1:22,
2:21,
3:12,
4:33,
5:21,
6:20,
7:68,
8:66,
9:65,
10:109,
11:108,
12:105,
13:162,
14:161,
15:160,
16:205,
17:203,
18:203,
19:251,
20:250,
21:238,
22:260,
23:250,
24:250
}

In [168]:
map_zona_coord_y = {  
1:18,
2:43,
3:82,
4:83,
5:117,
6:147,
7:22,
8:81,
9:141,
10:22,
11:82,
12:138,
13:21,
14:81,
15:142,
16:23,
17:80,
18:141,
19:20,
20:45,
21:80,
22:81,
23:119,
24:147
}

In [169]:
data_eventos['coord.final.num'] = np.where(data_eventos['coord.final'] == 'Volver',None, data_eventos['coord.final']).astype('float')

In [170]:
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial'].map(map_zona_coord_x)
data_eventos['coord.final.x'] = data_eventos['coord.final.num'].map(map_zona_coord_x)
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial'].map(map_zona_coord_y)
data_eventos['coord.final.y'] = data_eventos['coord.final.num'].map(map_zona_coord_y)
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,21.0,108.0,238.0,82.0,80.0
1,NaN,108.0,NaN,82.0,NaN
2,NaN,205.0,NaN,23.0,NaN
3,5.0,12.0,21.0,82.0,117.0
4,2.0,21.0,21.0,117.0,43.0
...,...,...,...,...,...
241,NaN,250.0,NaN,119.0,NaN
242,24.0,203.0,250.0,141.0,147.0
243,22.0,238.0,260.0,80.0,81.0
244,NaN,238.0,NaN,80.0,NaN
245,NaN,NaN,NaN,NaN,NaN

In [171]:
data_eventos['coord.inicial.x'].describe() # de 0 a 272

count    241.000000
mean     122.763485
std       84.614555
min       12.000000
25%       65.000000
50%      108.000000
75%      203.000000
max      260.000000
Name: coord.inicial.x, dtype: float64

In [172]:
# añadirles aleatoriedad
data_eventos['coord.inicial.x'] = data_eventos['coord.inicial.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.x'].describe()

count    241.000000
mean     123.021511
std       84.794799
min       -6.581032
25%       52.970851
50%      108.620001
75%      203.795953
max      273.523016
Name: coord.inicial.x, dtype: float64

In [173]:
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']<0, 0, data_eventos['coord.inicial.x'])
data_eventos['coord.inicial.x'] = np.where(data_eventos['coord.inicial.x']>272, 272, data_eventos['coord.inicial.x'])

In [174]:
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    241.000000
mean      84.120332
std       42.844073
min       18.000000
25%       45.000000
50%       82.000000
75%      138.000000
max      147.000000
Name: coord.inicial.y, dtype: float64

In [175]:
data_eventos['coord.inicial.y'] = data_eventos['coord.inicial.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.inicial.y'].describe() # de 0 a 162

count    241.000000
mean      85.122874
std       45.141369
min        0.808351
25%       47.837772
50%       84.203999
75%      126.454520
max      166.669184
Name: coord.inicial.y, dtype: float64

In [176]:
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']<0, 0, data_eventos['coord.inicial.y'])
data_eventos['coord.inicial.y'] = np.where(data_eventos['coord.inicial.y']>162, 162, data_eventos['coord.inicial.y'])

In [177]:
data_eventos['coord.final.x'] = data_eventos['coord.final.x'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']<0, 0, data_eventos['coord.final.x'])
data_eventos['coord.final.x'] = np.where(data_eventos['coord.final.x']>272, 272, data_eventos['coord.final.x'])

In [178]:
data_eventos['coord.final.y'] = data_eventos['coord.final.y'] + np.random.uniform(-20,20,len(data_eventos))
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']<0, 0, data_eventos['coord.final.y'])
data_eventos['coord.final.y'] = np.where(data_eventos['coord.final.y']>162, 162, data_eventos['coord.final.y'])

In [179]:
data_eventos.iloc[:,-5:]

,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
0,21.0,123.757639,229.752415,64.635924,65.514192
1,NaN,115.158265,NaN,78.012548,NaN
2,NaN,216.362810,NaN,30.747521,NaN
3,5.0,16.067100,7.959203,98.953429,136.057524
4,2.0,22.621981,8.420868,124.103161,26.740428
...,...,...,...,...,...
241,NaN,244.845884,NaN,106.271849,NaN
242,24.0,193.142951,232.357031,135.325424,133.127731
243,22.0,219.201092,271.282025,74.080259,87.891630
244,NaN,228.280793,NaN,69.300882,NaN
245,NaN,NaN,NaN,NaN,NaN

In [180]:
round(data_eventos['coord.inicial.x'],0).astype('str')+','+round(data_eventos['coord.inicial.y'],0).astype('str')

0       124.0,65.0
1       115.0,78.0
2       216.0,31.0
3        16.0,99.0
4       23.0,124.0
          ...
241    245.0,106.0
242    193.0,135.0
243     219.0,74.0
244     228.0,69.0
245        nan,nan
Length: 246, dtype: object

In [181]:
# pasar en ambos formatos. Crear las dos cols originales q sean strings

data_eventos['coord.inicial'] = round(data_eventos['coord.inicial.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.inicial.y'],0).astype('str').str.split('.').str[0]
data_eventos['coord.final'] = round(data_eventos['coord.final.x'],0).astype('str').str.split('.').str[0]+','+round(data_eventos['coord.final.y'],0).astype('str').str.split('.').str[0]

In [182]:
data_eventos['coord.inicial'] = np.where(data_eventos['coord.inicial']=='nan,nan', None, data_eventos['coord.inicial'])
data_eventos['coord.final'] = np.where(data_eventos['coord.final']=='nan,nan', None, data_eventos['coord.final'])

In [183]:
data_eventos[['coord.inicial','coord.final']]

    coord.inicial coord.final
0          124,65      230,66
1          115,78        None
2          216,31        None
3           16,99       8,136
4          23,124        8,27
..            ...         ...
241       245,106        None
242       193,135     232,133
243        219,74      271,88
244        228,69        None
245          None        None

[246 rows x 2 columns]

# Escribir tabla filtros

In [184]:
data_eventos = data_eventos[~data_eventos['partido'].isna()].reset_index(drop=True)

In [185]:
data_eventos['partido'] = 'Barracas'

In [186]:
data_eventos.tail()

,Session.Start.Date,tiempo,partido,Session.Start,Session.End,Evento,Tag.Notes,Tag.Start,Tag.End,Tag.Duration.(secs),...,arquero-Intercepcion,arquero-Anticipo,arquero-Saque-mano,arquero-Saque-pie,arquero-Saque-meta,coord.final.num,coord.inicial.x,coord.final.x,coord.inicial.y,coord.final.y
240,2022/07/24,pases barracas central,Barracas,13:43:45,15:43:30,pase,NaN,01:52:22,01:52:22,0.0,...,0,0,0,0,0,22.0,253.938986,272.000000,123.937373,95.348396
241,2022/07/24,pases barracas central,Barracas,13:43:45,15:43:30,perdida,NaN,01:52:24,01:52:24,0.0,...,0,0,0,0,0,NaN,244.845884,NaN,106.271849,NaN
242,2022/07/24,pases barracas central,Barracas,13:43:45,15:43:30,pase,NaN,01:53:35,01:53:35,0.0,...,0,0,0,0,0,24.0,193.142951,232.357031,135.325424,133.127731
243,2022/07/24,pases barracas central,Barracas,13:43:45,15:43:30,remate pie,NaN,01:53:40,01:53:40,0.0,...,0,0,0,0,0,22.0,219.201092,271.282025,74.080259,87.891630
244,2022/07/24,pases barracas central,Barracas,13:43:45,15:43:30,perdida,NaN,01:53:41,01:53:41,0.0,...,0,0,0,0,0,NaN,228.280793,NaN,69.300882,NaN

In [187]:
data_eventos.to_csv("../Datos generados para la app/reserva02-22-fecha9_barracas-tabla_filtros2.csv",index=False)